Feature/language agnostic comp sci
TheOdinProject/curriculum pull request #20452
Opened 2020-08-23 03:35 UTC by JonColman94

First edition of the Language Agnostic Computer Science Course described [in this issue](https://github.com/TheOdinProject/curriculum/issues/15979)

Lessons are found in the /computer_science directory.

The course discusses Pseudocode, Recursion and it's comparisons with Iteration; some different types of sort (Insertion Sort, Merge Sort, Quicksort and Bogosort), as well as search algorithms (Linear and Binary Search). Discussion on Big O notation, with examples of what some O notations look like in code ( O(1), O(n), O(n^2) and O(logn) ) specifically. As well as putting our legacy Linked List and Tree projects to good use.

Extended tree discussion to briefly cover Depth-Limited Search and Iterative Deepening.

New Projects include comparing Recursive solutions with Iterative solutions; and putting practical understanding of Big O notation to code. 

I do believe this course will be in need of further refinement; but I'd like to at least have some review on this first draft.

Placed the original Ruby Comp Sci lessons in a /legacy directory inside the /computer_science directory for sake of reference.

2020-09-22 00:09 UTC, KevinMulhern commented
Hey @Jan-Kotze, thanks for doing this. Sorry it hasn't been reviewed yet. We're wrapping up a couple of big projects and will get to this shortly.

2020-09-22 00:49 UTC, JonColman94 commented
No rush, take all the time you need.

2020-10-16 15:33 UTC, Deetss commented on computer_science/Legacy/lesson_a_very_brief_intro_to_cs.md
> +  1. Skim this [Introduction to Algorithms by David Malan](http://ed.ted.com/lessons/your-brain-can-solve-algorithms-david-j-malan) on TedEd to see how to think about algorithms.
This link is dead

2021-01-11 16:41 UTC, CouchofTomato commented
Hey @JonColman94 

Just want to offer my apologies this hasn't been picked up sooner. We really do appreciate your undertaking and I'm going to review it this week.

2021-01-12 13:44 UTC, CouchofTomato requested changes
Overall this is an amazing effort. Just a few things we need to consider around the assignment resources.

2021-01-12 13:44 UTC, CouchofTomato commented on computer_science/lesson_maps_stacks_and_queues.md
> +  1. Use pop, push and shift in your language of choice and get a feel for how these work! If you're not using Ruby or Javascript for this course, you might need to google around to find Queue implem
Why would they not be using JS or Ruby?

2021-01-12 13:44 UTC, CouchofTomato commented on computer_science/lesson_the_big_o.md
> +This means that our operations is approximately 6n^2. But we're not quite done yet. Say we grow n by 10 times as much; we only grow the number of operations by 100. The 6 in our little equation above
Should be operations are, or operation is

2021-01-12 13:44 UTC, CouchofTomato commented on computer_science/lesson_the_big_o.md
> +  1. Have another look at the algorithms mentioned in [our previous lesson](http://localhost:3000/courses/computer-science/lessons/a-general-view-on-algorithms) What are their Big O notations? What d
I think we should find at least one good resource which also covers big-0

2021-02-05 10:34 UTC, merged