Discord Etiquette addition
TheOdinProject/curriculum pull request #21695
Opened 2020-10-01 22:15 UTC by GraceSchwar

This was discussed with Brigge!

2020-10-01 22:17 UTC, I3uckwheat requested changes

2020-10-01 22:17 UTC, I3uckwheat commented on web_development_101/the_basics/join_the_odin_community.md
> +   - **Don't Exclude Anyone:**	These are public chats, if someone joins in on a conversation, include them!	<br/>
This really shouldn't have `<br/>` in here

2020-10-03 14:44 UTC, GraceSchwar commented
Removed <br> and formatted it the way other lists are formatted on Odin

2020-10-03 16:47 UTC, marvingay commented
LGTM 🚀

2020-10-03 16:47 UTC, marvingay approved these changes

2020-10-03 18:25 UTC, merged