Update preparing_for_deployment.md
TheOdinProject/curriculum pull request #21752
Opened 2020-10-06 08:15 UTC by aziaziazi

Hi, the note for the expected sudo password is duplicated in line 10 and 18. One occurence of the indication seems enough.

2020-10-06 12:32 UTC, I3uckwheat requested changes

2020-10-06 12:32 UTC, I3uckwheat commented on rails_programming/introduction/preparing_for_deployment.md
> +Activate your account from the email they sent you. Now, we'll install the Heroku command line so that we can interact with the Heroku service. We will use `curl` to download a script and run it to i
This was added here because people were missing it, please do not remove the information here.

2020-10-08 02:49 UTC, I3uckwheat commented
@aziaziazi Any updates on this?

2020-10-22 14:10 UTC, aziaziazi commented
@I3uckwheat Sorry for late reply. I close the PR.

2020-10-22 14:10 UTC, closed without merging