Update how_this_course_will_work.md
TheOdinProject/curriculum pull request #21923
Opened 2020-11-19 19:35 UTC by fortypercenttitanium

Added a section addressing non-English speakers

 - [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

...your text here

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

2020-11-20 01:26 UTC, I3uckwheat requested changes
Could we add a bit on the fact we won't translate TOP as well?

2020-11-20 01:32 UTC, marvingay commented
I'm going to leave a small review shortly.

2020-11-20 04:16 UTC, marvingay requested changes

2020-11-20 04:16 UTC, marvingay commented on foundations/the_basics/how_this_course_will_work.md
> +The Odin Project attracts people from all over the world who aspire to learn how to program. Please be aware that this curriculum is written in English and maintained by people whose primary (and typ
It's imperative to point out somewhere here why English is important to programming at-large.

(e.g. official documentation/references/and the community at-large [Odin and beyond] speak or read it).

Other than that, seems good.

2020-11-20 19:11 UTC, fortypercenttitanium reviewed
Made requested changes. Let me know if you like.

2020-11-21 00:38 UTC, marvingay approved these changes
Looks good to me.

2020-11-24 18:17 UTC, I3uckwheat approved these changes

2020-11-24 18:17 UTC, merged