Adds note for Chrome OS/CloudReady users
TheOdinProject/curriculum pull request #22266
Opened 2021-04-27 03:20 UTC by Nathan-Galipeau

- [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:

...your text here

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

2021-04-28 21:20 UTC, xandora requested changes
You seem to have forgotten to fill out the required details in the PR template. Please include those, and a link to the issue this is related to. I have also suggested a couple of changes. Once these are updated, this should be good to accept.

2021-04-28 21:20 UTC, xandora commented on foundations/installations/prerequisites.md
> +Chrome OS/CloudReady users will need to install install Git from source with instructions at this [Digital Ocean tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-git-on-debia
```suggestion
Chrome OS/CloudReady users will need to install Git from source by following the instructions at this [Digital Ocean tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-git-on-debian-10#installing-git-from-source).
```

2021-05-01 21:52 UTC, xandora commented
The changes look good, but you haven't filled out the PR template. Once that's done I'm happy for this to be merged.

2021-05-02 08:47 UTC, Nathan-Galipeau commented
Okay, I apologize for ignoring that on the last commit, it should appear as filled out now.

2021-05-02 12:14 UTC, xandora commented
Perfect!

2021-05-02 12:15 UTC, merged