Add another link that explains concept of linked list.
TheOdinProject/curriculum pull request #22285
Opened 2021-05-05 03:58 UTC by Tenacious-Qi

- [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/master/CONTRIBUTING.md).

#### 1.Describe the changes made:
This PR adds a link to the list of resources found in the Linked List project.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

2021-05-05 14:46 UTC, rlmoser99 requested changes
Thank you for taking the time to submit this PR! I do like this resource you found, so I agree that it belongs as the 2nd resource. Although, could you update the numbering of the following items?

2021-05-05 18:19 UTC, Tenacious-Qi commented
Oops! Thanks for catching that, glad you agree it's a good resource. Her entire base cs series is great.

2021-05-06 10:14 UTC, CouchofTomato approved these changes

2021-05-06 12:43 UTC, rlmoser99 approved these changes
Thanks for making these changes!

2021-05-06 12:43 UTC, merged