Added article about serif and sans serif fonts
TheOdinProject/curriculum pull request #22347
Opened 2021-05-31 20:00 UTC by MrDando

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made

Added the following [article](https://www.impactplus.com/blog/sans-serif-vs-serif-font-which-should-you-use-when) on the difference between serif and sans serif fonts, and when to use them.

##### Reason for adding:

Added the article since one of the learning outcomes for the lesson is 'What’s the difference between a serif and sans-serif font?'. However this question is currently not mentioned in any of the articles in the assignement or additional resources.

2021-06-08 14:29 UTC, leosoaivan approved these changes

2021-06-13 16:40 UTC, CatQueenCodes requested changes

2021-06-13 16:40 UTC, CatQueenCodes commented on html_css/typography.md
> +2. Read this article about Serif and Sans Serif fonts [Sans Serif vs Serif Font: Which Should You Use & When?](https://www.impactplus.com/blog/sans-serif-vs-serif-font-which-should-you-use-when)
I think that this would be best under the Additional Resources section. Could you please move it there.

2021-06-14 19:32 UTC, CatQueenCodes commented on html_css/typography.md
> +2. Read this article about Serif and Sans Serif fonts [Sans Serif vs Serif Font: Which Should You Use & When?](https://www.impactplus.com/blog/sans-serif-vs-serif-font-which-should-you-use-when)
Disregard review. I will merge this as it is in the learning outcomes

2021-06-14 19:32 UTC, merged