Feature/patch 1
TheOdinProject/curriculum pull request #22502
Opened 2021-08-03 02:22 UTC by jtcaovan

- [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

Added missing knowledge checks and added answer-links to Classes - JavaScript course

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#22472

2021-09-01 19:27 UTC, twalton83 commented
Do you mind resolving the merge conflicts?

2021-09-28 03:15 UTC, twalton83 commented
One more time with reserving merge conflicts, then we can merge.

2021-09-28 03:17 UTC, twalton83 requested changes
We need to resolve merge conflicts and fix the formatting of where the knowledge checks are.

2021-09-28 03:17 UTC, twalton83 commented on javascript/organizing-js/objects-constructors.md
> +### Knowledge Check
Looks like you added Knowledge Checks right inside of the Additional resources.

2021-09-28 05:32 UTC, jtcaovan commented on javascript/organizing-js/objects-constructors.md
> +### Knowledge Check
Hey @twalton83, not sure what just happened. I made the formatting fixes locally, but I was having issues pushing my changes. Sorry I'm still learning and trying to get a hang of the workflow, but I was wondering if you can help me through this when you can. 

I was receiving this error:

```
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
```

So I went ahead and did this, but I don't see the changes I made. 
`git push -f origin feature/patch-1`

2021-09-28 15:56 UTC, twalton83 commented
In this case it's probably easier to make a new PR, something went wrong.

2021-10-02 23:19 UTC, jtcaovan commented
> In this case it's probably easier to make a new PR, something went wrong. For what it's worth, never force push.

2021-10-02 23:19 UTC, closed without merging

2021-10-02 23:20 UTC, jtcaovan commented
> In this case it's probably easier to make a new PR, something went wrong. For what it's worth, never force push.

Great thank you. Created a new PR under patch-2. Lesson learned!