Fix minor typos and wording in objects-constructors.md
TheOdinProject/curriculum pull request #22515
Opened 2021-08-11 05:59 UTC by KaitlinKCheng

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

Fix minor typos (missing punctuation, capitalization) and edit some of the wording in the Additional Resources section.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

N/A

2021-08-18 16:27 UTC, wise-king-sullyman requested changes
Thanks for doing all this!

I've made some suggestions on things I would want to see changed. If you disagree with any of them please let me know, happy to discuss.

2021-08-18 16:27 UTC, wise-king-sullyman commented on javascript/organizing-js/objects-constructors.md
> +Nicholas C. Zakas is really great for understanding OOP in JavaScript. It explains concepts simply and in-depth, and it explores JavaScript's object-oriented nature, describing the language's unique
This resource description is phrased oddly to me, since it seems like it's talking about the author as if he's the book itself. Maybe swap the book title in here instead of the author's name? Or to maybe keep the intent of the original description; keep the author's name but rephrase the description so that it matches more with describing a person.

2021-08-18 23:05 UTC, KaitlinKCheng commented
@wise-king-sullyman Thank you for taking the time to review this! 😄 I've implemented your suggestions. I also attempted to reword the resource description in the Additional Resources section, but let me know if it still sounds strange. Thanks again!

2021-08-19 00:29 UTC, wise-king-sullyman approved these changes
Looks great! Thanks again for your contribution!

2021-08-19 00:29 UTC, merged