Update It
TheOdinProject/curriculum pull request #22517
Opened 2021-08-11 07:18 UTC by shockz09

Updated and added the link of the exact web design course of freecodecamp so that newbies have no problem navigating through it!.

 - [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:

...your text here

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

2021-08-14 22:34 UTC, wise-king-sullyman requested changes
I like the change of linking directly to the responsive web design section, but I think we need to change the instructions we're giving to students as well to match this change. Maybe something along the lines of "do only the courses/lessons in the linked section, do not do any of other sections/certifications such as `Javascript Algorithms`" though I'm not married to that specific wording.

2021-08-20 03:46 UTC, shockz09 commented
Thanks for you suggestion for changes. I forgot that to write. I am going to write that the do this course only

2021-08-20 23:37 UTC, wise-king-sullyman requested changes
It needs one last small wording change that I see, then it'll be approval time!

2021-08-20 23:37 UTC, wise-king-sullyman commented on foundations/the_front_end/html_css_basics.md
> +  1. Dive right into learning HTML and CSS with [freeCodeCamp's interactive tutorials](https://www.freecodecamp.org/learn/responsive-web-design/) to introduce you to these new concepts. Do only the c
`do not do any of other sections` -> `do not do any of the other sections`

2021-08-21 08:45 UTC, shockz09 commented
Sir , I have done the things you requested

2021-08-21 18:21 UTC, wise-king-sullyman approved these changes
Looks perfect! Thank you for your contribution!

2021-08-21 18:21 UTC, merged

2021-08-22 02:39 UTC, shockz09 commented
Welcome, Sir. Like this only I want to contribute to open-source projects