Feature: RSpec Part 2: Hooks, Let and Subject
TheOdinProject/curriculum pull request #22520
Opened 2021-08-11 22:38 UTC by KevinMulhern

Because:
* We are rewriting the testing lessons in the Ruby course and need a lesson to teach the student about coding sharing techniques in RSpec.

This lesson covers:
* Before and after hooks
* Let variables
* Subject
* Context groups

2021-08-12 10:26 UTC, CouchofTomato approved these changes
Great work again mate. Awesome stuff.

2021-08-12 10:26 UTC, CouchofTomato commented on ruby_programming/automated_testing/rspec_part_two_code_sharing.md
> +In this lesson we will be exploring some of the tools RSpec provides for sharing code among multiple tests. Specifically, we will be looking at hook, let and subject helper methods. These methods are
>so it's important to how they work and when to use them.

Missing the word 'know'

2021-08-12 10:26 UTC, CouchofTomato commented on ruby_programming/automated_testing/rspec_part_two_code_sharing.md
> +Thankfully RSpec provides a more idiomatic and and safer way of creating variables that can be used in multiple tests, The `let` method.
double 'and' here

2021-08-14 20:08 UTC, rlmoser99 requested changes
Another amazing job on this lesson! 🎉 

Just found one thing as I was following along that you probably refactored at some point.

2021-08-15 22:13 UTC, KevinMulhern commented on ruby_programming/automated_testing/rspec_part_two_code_sharing.md
> +  end
Thanks @rlmoser99, I was using keyword args initially and must have forgot to update this example 🙈

2021-08-19 17:26 UTC, merged