create 'intro' lesson
TheOdinProject/curriculum pull request #22529
Opened 2021-08-13 16:48 UTC by codyloyd

This PR closes https://github.com/TheOdinProject/top-meta/issues/17 by adding an 'introduction' lesson.

All items from the checklist have been completed.

2021-08-17 21:56 UTC, leosoaivan requested changes
LGTM, some grammar needs updating.

2021-08-17 21:56 UTC, leosoaivan commented on html_css/v2/foundations/intro-to-html-css.md
> +If you want to get technical, HTML and CSS aren't _programming languages_ because they are only concerned with presenting information. They are not used to program any logic. JavaScript, which you wi
`because it's used`

2021-08-17 21:56 UTC, leosoaivan commented on html_css/v2/foundations/intro-to-html-css.md
> +* Between HTML and CSS which would you use for putting paragraphs of text on a webpage?
`...and CSS, which...`

2021-08-17 23:42 UTC, codyloyd commented on html_css/v2/foundations/intro-to-html-css.md
> +If you want to get technical, HTML and CSS aren't _programming languages_ because they are only concerned with presenting information. They are not used to program any logic. JavaScript, which you wi
lol nice.  thanks

2021-08-18 14:24 UTC, thatblindgeye commented on html_css/v2/foundations/intro-to-html-css.md
> +<div class="lesson-content__panel" markdown="1">
The two links in this lesson I think should have better names than "this article".

The first one could be, "Read [HTML vs. CSS vs. Javascript](...) to get a quick overview of the relationship between HTML, CSS, and JavaScript."

The second could be, "[HTML, CSS, and JavaScript Explained for Beginners](...) goes into..."

(first time commenting on a range of lines in a PR)

2021-08-18 14:26 UTC, thatblindgeye commented
The two links in this lesson I think should have better names than "this article".

The first one could be, `Read [HTML vs. CSS vs. Javascript](...) to get a quick overview of the relationship between HTML, CSS, and JavaScript.`

The second could be, `[HTML, CSS, and JavaScript Explained for Beginners](...) goes into...`

2021-08-18 19:07 UTC, KevinMulhern approved these changes
LGTM 👍

2021-08-20 14:38 UTC, merged