Feature/update procs material in ruby blocks
TheOdinProject/curriculum pull request #22611
Opened 2021-09-08 11:18 UTC by binarygit

- [ yes] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

#### 1.Describe the changes made:
Three main additions made to Blocks unit
1. Add a SO article to clarify block capture
2. Show a new method of creating a proc
3. Add another helpful argument property of procs

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#XXXXX

2021-11-03 22:18 UTC, twalton83 commented
Are you still interested in making the requested changes?

2021-11-10 09:35 UTC, binarygit commented
Hey, sorry guys I have been away for sometime. I updated the document, I hope it addresses the issues. Let me know please. I won't take so long next time!

2021-12-07 10:26 UTC, CouchofTomato requested changes

2021-12-07 10:26 UTC, CouchofTomato commented on ruby_programming/advanced_ruby/blocks.md
> +As you can see, `#select` has two arguments specified `|a, b|`, on each iteration we pass a single element of nested_array into the block. On the first iteration this is: `[1, 2]`, this array now, is
Sorry to be pedantic but can be make sure the `[3,4]` array has the same spacing as the other ones

2021-12-07 10:27 UTC, CouchofTomato commented
Hey @binarygit 

Thanks for your work on this. There is just one small change please and then we can get this merged.

2021-12-08 15:14 UTC, CouchofTomato approved these changes

2021-12-08 15:15 UTC, CouchofTomato commented
Thanks for the contribution @binarygit

2021-12-08 15:15 UTC, merged