Fix punctuation and grammar in Elements and Tags
TheOdinProject/curriculum pull request #22702
Opened 2021-09-23 19:33 UTC by msespos

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Fix punctuation and grammar in multiple places

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

Not related to an open issue

2021-09-23 19:34 UTC, msespos commented
I  went back and made changes to the edits several times, hence the multiple commits with the same name. I don't actually know why the two merges happened. I tried to start over and they stayed in the git history.

2021-09-23 19:41 UTC, msespos commented
Looking back at this I'm realizing that those are five commits that would be pushed, which seems pretty sloppy. Please let me know if I should try to redo this in one commit. Thanks!

2021-09-24 15:08 UTC, codyloyd requested changes

2021-09-24 15:08 UTC, codyloyd commented on foundations/html_css/html-foundations/elements-and-tags.md
> +HTML has a [vast list of predefined tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) which you can use to create all kinds of different elements. It is important to use the correct ta
"which you can use" should be "that you can use"

2021-09-24 17:46 UTC, closed without merging