Add links to knowledge checks - problem solving
TheOdinProject/curriculum pull request #22734
Opened 2021-09-29 11:23 UTC by BLooDBRothER

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Added link to the knowledge checks in the lesson Problem solving under the path Foundations.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#22466

2021-10-02 22:59 UTC, twalton83 requested changes
Please make the IDs more semantic.

2021-10-02 22:59 UTC, twalton83 commented on foundations/javascript_basics/problem_solving.md
> +The first step to solving a problem is understanding exactly what the problem is.<span id="question2"> If you don't understand the problem you won't know when you've successfully solved it and may wa
We want to be more semantic with the IDs here. See this PR for reference.

2021-10-03 02:08 UTC, BLooDBRothER commented
@twalton83 I made the changes you proposed.

2021-10-03 02:08 UTC, twalton83 approved these changes

2021-10-03 02:08 UTC, merged