Feature/knowledge checks for testing section
TheOdinProject/curriculum pull request #22743
Opened 2021-09-30 08:50 UTC by roshaan005

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:
...your text here
For the testing javaScript section, knowledge checks and learning outcomes were added

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:
#22472 

#XXXXX

2021-09-30 09:49 UTC, Maheshkumar-novice commented
Hello, I think we should follow different format for the links. Now you are currently using format like this,
**-\[text](link)**
but we need to follow the below style
**-\<a class="knowledge-check-link" href="link">text</a>**

We need to use `class="knowledge-check-link"` to remove the default styles of the link. It's mentioned in the issue as well.

https://www.theodinproject.com/lessons/preview/ you can use this page to preview the links.

![format](https://user-images.githubusercontent.com/67100964/135429099-bb29680b-6473-470d-9565-2132b2e6dc11.png)
![format1](https://user-images.githubusercontent.com/67100964/135429178-151c415b-bd9c-4ad1-9ddd-c0bdef19ee1f.png)

2021-09-30 10:19 UTC, roshaan005 commented
Will fix asap , thank you for reviewing it!

2021-10-02 23:10 UTC, twalton83 commented on javascript/testing/testing-1.md
> +- <a class = "knowledge-check-link" href = "https://dzone.com/articles/unit-testing-guidelines-what-to-test-and-what-not">What should you test in your codebase?</a>
I may be missing it, but if we don’t link it in the lesson, we shouldn’t direct them to it in a Knowledge Check.

2021-10-06 21:20 UTC, wise-king-sullyman commented
@roshaan005 if you're still working on these can you comment on issues #22803 and #22804 so that I can assign you, and update the opening comment from this PR with those issue numbers and the closing keyword (i.e. "closes #22803 if you're not familiar) so that when this is merged in the issues are closed?

2021-11-03 22:25 UTC, twalton83 requested changes

2021-11-03 22:25 UTC, twalton83 commented on javascript/testing/testing-2.md
> +- <a class = "knowledge-check-link" href = "#Pure-Functions">What are pure functions and how are they different from normal functions?</a>
Do you mind updating this to fall in line with the knowledge checks formatting that can be found in other lessons?

2021-12-07 03:59 UTC, twalton83 commented
@roshaan005 Are you still willing to make these changes? Otherwise I will close this tomorrow.

2021-12-22 03:27 UTC, twalton83 commented
Closing because stale.

2021-12-22 03:27 UTC, closed without merging