Added some missing details and an additional resource to the authentication basics lesson
TheOdinProject/curriculum pull request #22816
Opened 2021-10-05 19:33 UTC by griitch

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:
 - Gave a quick definition of what a hash function is without going into details
 - Explained briefly what salt is.
 - Explained what the second argument in the bcrypt.hash function represents.
 - Added a 10 minutes video to the additional resources section.
I think it's necessary because it's better to have at least some basic understanding of how all of these things work instead of just using them right away

2021-10-06 01:57 UTC, kashura requested changes

2021-10-06 01:57 UTC, kashura commented on nodeJS/authentication/Authentication.md
> +The second argument is the length of the "salt" to use in the hashing function, salting a password means adding extra random characters to it. By hashing a password plus a salt, if multiple users had
- Missing semi colon before "salting a password means...".
- 2nd sentence in this paragraph just doesn't read quite right.

2021-10-06 10:18 UTC, griitch commented on nodeJS/authentication/Authentication.md
> +It's important to note that _how_ hashing works is beyond the scope of this lesson. To learn more about the subjet consider reading [This wikipedia article](https://en.wikipedia.org/wiki/Cryptographi
fixed

2021-11-04 15:47 UTC, kashura approved these changes

2021-11-04 15:48 UTC, merged