Add knowledge checks
TheOdinProject/curriculum pull request #22995
Opened 2021-10-30 20:56 UTC by pudu87

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Add missing Knowledge Checks, Learning Outcomes, and Knowledge Check links to Ruby/Common Data Structures and Algorithms

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number (and any [relevant keywords](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) below:

closes #22928

2021-10-31 18:46 UTC, wise-king-sullyman commented
@pudu87 When only one lesson is being changed please reference the lesson being changed in the title of PR's.

2021-10-31 19:01 UTC, wise-king-sullyman requested changes
Just a couple change requests

2021-11-01 16:55 UTC, pudu87 commented on ruby_programming/computer_science/lesson_common_data_structures_algorithms.md
> +* <a class="knowledge-check-link" href="http://blog.thefirehoseproject.com/posts/what-is-an-algorithm/">How would you implement stacks and queues in Ruby?</a>
True. Only the queue gets mentioned here. I was thinking if students figure that one out, the stacks should not be a major issue.

It comes straight from the Learning Outcomes, but I like the question because it helps to conceptualize this abstract lesson a bit.

2021-11-01 21:09 UTC, wise-king-sullyman commented on ruby_programming/computer_science/lesson_common_data_structures_algorithms.md
> +* <a class="knowledge-check-link" href="http://blog.thefirehoseproject.com/posts/what-is-an-algorithm/">How would you implement stacks and queues in Ruby?</a>
@pudu87 I agree that stacks probably shouldn't be an issue for someone that's finished this lesson, but at the moment we want to specifically avoid having any questions in the new Knowledge Checks that aren't directly addressed in either our content or the resources we link to.

2021-11-01 22:12 UTC, pudu87 commented on ruby_programming/computer_science/lesson_common_data_structures_algorithms.md
> +* <a class="knowledge-check-link" href="http://blog.thefirehoseproject.com/posts/what-is-an-algorithm/">How would you implement stacks and queues in Ruby?</a>
@wise-king-sullyman No problem, I made the change.

2021-11-01 22:14 UTC, wise-king-sullyman approved these changes
Looks perfect now! Thanks!

2021-11-01 22:14 UTC, merged