Add missing Knowledge Checks, Learning Outcomes, and Knowledge Check links to Ruby on Rails/A Railsy Web Refresher
TheOdinProject/curriculum pull request #23008
Opened 2021-11-03 15:26 UTC by pudu87

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

Add learning outcomes
Add knowledge checks

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number (and any [relevant keywords](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) below:

closes #22935

2021-11-05 03:17 UTC, wise-king-sullyman requested changes
Thanks for putting in the work to write all of these up and I apologize for not stating this up front (we're currently working on a document that will do so) but we don't want to have *too* many Knowledge Checks or Learning Outcomes on a lesson. I think we typically want to be in the 3-7 range max for each. 

Do you think you could pare down the number of Knowledge Checks? If you'd like I can suggest some to remove but I figured I would leave the choice up to you first.

2021-11-05 14:03 UTC, pudu87 commented
@wise-king-sullyman Haha, no problem. I ended up with that many questions because there was so much going on in this lesson.

I'm curious about which questions you consider more relevant here, so I accept your suggestion of making a suggestion!

2021-11-06 00:51 UTC, wise-king-sullyman requested changes
Totally understand why you wrote so many questions as this lesson covers a *lot* of different material.

I've made my suggestions for questions to drop. I'll have some additional changes to request, but since you'll still be able to drop other questions instead if you'd like, and I don't want you to waste time changing things that will just be removed, I'll hold that feedback until you've removed 3-5 Knowledge Checks.

Additionally, check out [this new addition to our wiki](https://github.com/TheOdinProject/curriculum/wiki/Learning-Outcomes-vs-Knowledge-Checks) for some tips on what we look for in Learning Outcomes and Knowledge Checks as many of the things I'm going to suggest will be along the lines of that wiki page.

2021-11-06 00:51 UTC, wise-king-sullyman commented on rails_programming/rails_basics/web_refresher.md
> +* <a class="knowledge-check-link" href="https://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-1--net-31177">What is the difference between HTTP and HTTPS?</a>
I'd drop this question because it isn't very relevant and the linked resource only barely touches on it anyways.

2021-11-06 00:51 UTC, wise-king-sullyman commented on rails_programming/rails_basics/web_refresher.md
> +* <a class="knowledge-check-link" href="https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/a-railsy-web-refresher#rest">Name all 7 RESTful controller actions
I'd drop this question because Rails details will be more relevant in later lessons than this one.

2021-11-06 00:51 UTC, wise-king-sullyman commented on rails_programming/rails_basics/web_refresher.md
> +* <a class="knowledge-check-link" href="https://betterexplained.com/articles/intermediate-rails-understanding-models-views-and-controllers/">Which part of MVC communicates with the database?</a>
I'd drop these questions because Rails details will be more relevant in later lessons than this one.

2021-11-06 00:51 UTC, wise-king-sullyman commented on rails_programming/rails_basics/web_refresher.md
> +* <a class="knowledge-check-link" href="https://www.allaboutcookies.org/">What ethical issues do cookies bring along and how should web developers anticipate those?</a>
I'd drop this question because like HTTPS direct relevance to learning Rails is quite low.

2021-11-06 14:59 UTC, pudu87 commented
Ok, that all seems very reasonable. What's next?

2021-11-08 04:22 UTC, wise-king-sullyman requested changes
I've provided suggestions for how I would change things, but if you have other ideas you're under no obligation to take them as-is. I would like to see things go in the direction I'm heading with these suggestions though.

2021-11-08 04:22 UTC, wise-king-sullyman commented on rails_programming/rails_basics/web_refresher.md
> +* Know the difference between "authentication" and "authorization".
Per the wiki post I wrote about Learning Outcomes and Knowledge Checks we want these to be higher level, for instance here's the changes I would probably make:
```suggestion
* Explain the basics of HTTP.
* Identify the 4 most commonly used HTTP verbs.
* Identify the 7 RESTful routes of Rails.
* Name the different components of a URL.
* Explain the basics of MVC.
* Describe what an API is.
* Explain what "cookies" and "sessions" are.
* Describe the difference between "authentication" and "authorization".
```

2021-11-08 04:22 UTC, wise-king-sullyman commented on rails_programming/rails_basics/web_refresher.md
> +* <a class="knowledge-check-link" href="https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/a-railsy-web-refresher#authorization">Explain the difference betwee
Also per some of my suggestions in that wiki post, we want to limit Knowledge Checks to one question each. To do so I would split the first question into parts, and to keep the total number of questions down I would drop a bit from one of your MVC questions and all of another one. Here are the changes I would make (including some grammar tweaks):

```suggestion
* <a class="knowledge-check-link" href="https://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-1--net-31177">What do you call an HTTP message that goes from client to server?</a>
* <a class="knowledge-check-link" href="https://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-1--net-31177">What do you call an HTTP message that goes from server to client?</a>
* <a class="knowledge-check-link" href="https://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-1--net-31177">Which HTTP message would include a status code and which would include an action verb?</a>
* <a class="knowledge-check-link" href="https://www.mattcutts.com/blog/seo-glossary-url-definitions/">What is the name of the additional information that is added after the path of a URL?</a>
* <a class="knowledge-check-link" href="https://betterexplained.com/articles/intermediate-rails-understanding-models-views-and-controllers/">What does MVC stand for?</a>
* <a class="knowledge-check-link" href="https://money.howstuffworks.com/business-communications/how-to-leverage-an-api-for-conferencing1.htm">What is an "API"?</a>
* <a class="knowledge-check-link" href="https://en.wikipedia.org/wiki/HTTP_cookie#Session_management">Why do you need "cookies" to continue your "session"?</a>
* <a class="knowledge-check-link" href="https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/a-railsy-web-refresher#authorization">What is the difference between "authentication" and "authorization"?</a>
```

2021-11-09 02:25 UTC, wise-king-sullyman approved these changes
Thanks a ton for doing all this work and being open to feedback :slightly_smiling_face:

2021-11-09 02:26 UTC, merged