Add knowledge checks in ruby/a-very-brief-intro-to-cs lesson
TheOdinProject/curriculum pull request #23004
Opened 2021-11-01 21:33 UTC by asadrjhk

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

I have added knowledge checks in the Ruby - A Very Brief Intro to CS lesson.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number (and any [relevant keywords](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) below:

closes #22926

2021-11-04 02:54 UTC, wise-king-sullyman requested changes
Looks pretty good, one change I'd like to see.

2021-11-04 02:54 UTC, wise-king-sullyman commented on ruby_programming/computer_science/lesson_a_very_brief_intro_to_cs.md
> +* <a class="knowledge-check-link" href="http://ed.ted.com/lessons/your-brain-can-solve-algorithms-david-j-malan">How to think about Algorithms?</a>
Can you rephrase this? I'm not really sure what the question is here.

2021-11-04 17:03 UTC, wise-king-sullyman reviewed
@asadrjhk do you know if we use this pattern of putting a code block in our knowledge checks anywhere else? I don't *think* we do, and if not I'll need to get up with the rest of the team to discuss if it's a direction we want to go in.

2021-11-04 17:16 UTC, asadrjhk commented
@wise-king-sullyman oh i understand i didn't see that pattern till now in my progress, let me know if have to change this

2021-11-05 03:10 UTC, wise-king-sullyman commented
@asadrjhk Yeah, we don't want to go in that direction at this time.

2021-11-06 00:24 UTC, wise-king-sullyman requested changes

2021-11-06 00:24 UTC, wise-king-sullyman commented on ruby_programming/computer_science/lesson_a_very_brief_intro_to_cs.md
> +* <a class="knowledge-check-link" href="http://ed.ted.com/lessons/your-brain-can-solve-algorithms-david-j-malan">Write an Algorithm to count the number of people in the room?</a>
I don't think there actually is a good question to come from this resource, I think it would be best to just remove it.

2021-11-07 17:46 UTC, wise-king-sullyman approved these changes
Perfect! Thanks for taking the time to make these changes :slightly_smiling_face:

2021-11-07 17:46 UTC, merged