Add answer links to the knowledge check section
TheOdinProject/curriculum pull request #23017
Opened 2021-11-04 02:49 UTC by jmsmith1018

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The PR title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 
#### 1.Describe the changes made and include why they are necessary or important:

I added answer links to each of the items in the knowledge check section. I split a few of the checks up because it would've been impossible to link to the correct place in the lesson with a single link. An example is the current top item in the knowledge-check list asks `What is a nested array and hash?` but nested arrays and nested hashes are introduced in very different sections of the page. I also combined the `What are nested arrays/hashes` with `What data is held by nested arrays/hashes` because their answers are adjacent on the page and can be conveniently linked together.

#### 2. If this PR is related to an open issue please reference it with the `#` operator and the issue number (and any [relevant keywords](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) below:

closes #22920

2021-11-05 03:42 UTC, wise-king-sullyman commented
@jmsmith1018 in the future can you mention the lesson being changed (when only one lesson is being changed) in the PR title? Makes things easier for us to keep an eye on things at a glance.

I already updated the title here, so just something to know on any PRs you do going forward :slightly_smiling_face:

2021-11-05 04:27 UTC, wise-king-sullyman requested changes
This looks great overall! I have a few suggestions/change requests then it should be good to go!

2021-11-05 04:27 UTC, wise-king-sullyman commented on ruby_programming/basic_ruby/nested_collections.md
> +<span id='dig-method-knowledge-check'>If you want a nil value returned when trying to access an index of a nonexistent nested element, you can use the `#dig` method.<span> This method can also be use
```suggestion
<span id='dig-method'>If you want a nil value returned when trying to access an index of a nonexistent nested element, you can use the `#dig` method.<span> This method can also be used when accessing a nonexistent index inside of an existing nested element.
```

2021-11-05 04:27 UTC, wise-king-sullyman commented on ruby_programming/basic_ruby/nested_collections.md
> +- <a class='knowledge-check-link' href='#dig-method-knowledge-check'>Why is the `#dig` method useful?<a>
```suggestion
- <a class='knowledge-check-link' href='#dig-method'>Why is the `#dig` method useful?<a>
```

2021-11-05 04:27 UTC, wise-king-sullyman commented on ruby_programming/basic_ruby/nested_collections.md
> +- <a class='knowledge-check-link' href='#iterating-over-nested-a-array'>How do you iterate over a nested array?</a>
```suggestion
- <a class='knowledge-check-link' href='#iterating-over-a-nested-array'>How do you iterate over a nested array?</a>
```

2021-11-05 20:42 UTC, JoshDevHub commented
Committed the changes. I'll also be sure to include the lesson name in the PR next time. Thanks for the feedback :+1:

2021-11-06 00:56 UTC, wise-king-sullyman approved these changes
Good catches on those missing `/`s!

This looks great, thank you for your contribution :smile:

2021-11-06 00:57 UTC, merged