Add missing Knowledge Checks and Knowledge Check links to NodeJS/Express 104: View Templates
TheOdinProject/curriculum pull request #23065
Opened 2021-11-15 15:07 UTC by eneamuskaj

…ess 104: View Templates

 - [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
- [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1.Describe the changes made and include why they are necessary or important:

Ive added the missing knowledge check section and the corresponding links to the NodeJS/Express 104: View Templates lesson.

#### 2. Related Issue

closes #22959

2021-11-15 16:00 UTC, fortypercenttitanium requested changes
Thanks for your contribution! I have a few thoughts and some things that need changing. Everything else looks good to me so far.

2021-11-15 16:50 UTC, eneamuskaj commented on nodeJS/express-basics/Express-Lesson-4.md
> +- <a class='knowledge-check-link' href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/flow_control_using_async" title="Asynchronous flow control using asyn
I agree. Maybe a better way to frame the question is "Why do we use the Async module ?"

2021-11-15 19:19 UTC, fortypercenttitanium commented on nodeJS/express-basics/Express-Lesson-4.md
> +- <a class='knowledge-check-link' href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/flow_control_using_async" title="Asynchronous flow control using asyn
> I agree. Maybe a better way to frame the question is "Why do we use the Async module ?"

I agree!

2021-11-16 01:43 UTC, eneamuskaj commented on nodeJS/express-basics/Express-Lesson-4.md
> +- <a class='knowledge-check-link' href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment/#create_the_virtual_property" title="Per
Maybe a better way would be?  "Why do we use the virtual property?"

2021-11-16 21:38 UTC, fortypercenttitanium commented on nodeJS/express-basics/Express-Lesson-4.md
> +- <a class='knowledge-check-link' href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment/#create_the_virtual_property" title="Per
I think that would be better! Good thinking.

2021-11-16 21:44 UTC, fortypercenttitanium commented on nodeJS/express-basics/Express-Lesson-4.md
> +- <a class='knowledge-check-link' href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment/#create_the_virtual_property" title="Per
@eneamuskaj Actually, on second thought I think the virtual property (and why it's used) is actually covered in a previous lesson (pt 3): https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#defining_and_creating_models

Let's maybe rethink this question altogether. Perhaps something that asks what the `luxon` package does for our database item, and why we might use it in place of the regular date format. Thoughts?

2021-11-17 01:18 UTC, eneamuskaj commented on nodeJS/express-basics/Express-Lesson-4.md
> +- <a class='knowledge-check-link' href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment/#create_the_virtual_property" title="Per
Im thinking about "What are the benefits of using luxon for date formatting?" or  "Why do we use luxon instead of the regular date format?"

2021-11-17 03:18 UTC, fortypercenttitanium commented on nodeJS/express-basics/Express-Lesson-4.md
> +- <a class='knowledge-check-link' href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment/#create_the_virtual_property" title="Per
Yes, that is good. I think I like the wording of the second one. Once you have those pushed, click the re-request review button next to my username so I'm notified!

2021-11-17 03:26 UTC, eneamuskaj commented
Thank you for helping me out with this. :)

2021-11-18 02:07 UTC, fortypercenttitanium approved these changes
Excellent work. Thank you!

2021-11-18 02:07 UTC, merged