Add missing Knowledge Checks, Learning Outcomes, and Knowledge Check links to Ruby on Rails/Views
TheOdinProject/curriculum pull request #23103
Opened 2021-11-22 18:58 UTC by pudu87

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
- [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1.Describe the changes made and include why they are necessary or important:

- Adjust Learning Outcomes
- Add Knowledge Checks

#### 2. Related Issue

closes #22938

2021-11-23 01:24 UTC, wise-king-sullyman commented
@pudu87 I think the language used in the first question is fine, it's just more specific in its phrasing. If you'd like to propose it be changed though you can, please make that suggestion under a separate PR though.

2021-11-24 04:09 UTC, wise-king-sullyman requested changes
Really like these changes! Just a couple of small suggestions.

2021-11-24 04:09 UTC, wise-king-sullyman commented on rails_programming/rails_basics/views.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#understanding-yield">What exactly does `<%= yield %>` "yields" in `application.hmtl.erb`?</a>
I'm not entirely sure what this question is asking. I assume it's asking what `yield` does, but the phrasing used is a bit confusing.

2021-11-24 04:09 UTC, wise-king-sullyman commented on rails_programming/rails_basics/views.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections">What is the shortcut for rendering a collection in a partial?</a>
```suggestion
* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections">What is the shortcut for rendering a collection as a series of partials?</a>
```
Since when using this method partials are rendered once for each item in the collection I believe that this phrasing is more accurate.

2021-11-24 14:25 UTC, pudu87 commented on rails_programming/rails_basics/views.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#understanding-yield">What exactly does `<%= yield %>` "yields" in `application.hmtl.erb`?</a>
Would it be more clear if I change "yield" to "return"?
The question is there to check if they grasp the how the layout and the view-file are intertwined.

2021-11-24 14:26 UTC, pudu87 commented on rails_programming/rails_basics/views.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections">What is the shortcut for rendering a collection in a partial?</a>
True!

2021-11-24 16:55 UTC, wise-king-sullyman commented on rails_programming/rails_basics/views.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#understanding-yield">What exactly does `<%= yield %>` "yields" in `application.hmtl.erb`?</a>
Yes I think that "return" is a clearer word here than "yields", or maybe something like "What does `yield` do in a layout"?

It doesn't have to be that exactly, I just suggest it because I think it's in the same spirit as your question. If we don't seem to be on the same page though tell me what the answer to the question as you've formulated it here is as that will probably help me understand.

2021-11-24 18:22 UTC, pudu87 commented on rails_programming/rails_basics/views.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#understanding-yield">What exactly does `<%= yield %>` "yields" in `application.hmtl.erb`?</a>
The answer to the question would be - if I paraphrase literally from the Rails source: 

> yield identifies a section where content from the view should be inserted

For me this is pretty trivial now, but out of my experience I know those first chapters of the Rails course are pretty hard to grasp.

2021-11-24 21:20 UTC, wise-king-sullyman commented on rails_programming/rails_basics/views.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#understanding-yield">What exactly does `<%= yield %>` "yields" in `application.hmtl.erb`?</a>
What do you think of phrasing it something like:

"What does including `<%= yield %>` in a layout do?"

2021-11-24 21:38 UTC, pudu87 commented on rails_programming/rails_basics/views.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/layouts_and_rendering.html#understanding-yield">What exactly does `<%= yield %>` "yields" in `application.hmtl.erb`?</a>
It's a done deal.

2021-11-25 01:29 UTC, wise-king-sullyman approved these changes
Looks great, thank you!

2021-11-25 01:30 UTC, merged