Add missing Knowledge Checks, Learning Outcomes, and Knowledge Check links to Ruby on Rails/The Asset Pipeline
TheOdinProject/curriculum pull request #23137
Opened 2021-12-01 16:16 UTC by pudu87

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
- [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1.Describe the changes made and include why they are necessary or important:

- Adjust learning outcomes
- Add knowledge checks

#### 2. Related Issue

closes #22939

2021-12-07 20:26 UTC, leosoaivan requested changes

2021-12-07 20:26 UTC, leosoaivan commented on rails_programming/rails_basics/asset_pipeline.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/asset_pipeline.html#main-features">How does "asset concatenation" improves faster loading of your app?</a>
Could we switch out "improves faster" with an alternative? Something like "optimize"?

2021-12-08 15:20 UTC, pudu87 commented on rails_programming/rails_basics/asset_pipeline.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/asset_pipeline.html#main-features">How does "asset concatenation" improves faster loading of your app?</a>
Sure, no problem.

2021-12-22 03:40 UTC, leosoaivan requested changes

2021-12-22 03:40 UTC, leosoaivan commented on rails_programming/rails_basics/asset_pipeline.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/asset_pipeline.html#main-features">How does "asset concatenation" optimizes loading of your app?</a>
`optimizes` -> `optimize`

2021-12-22 03:41 UTC, leosoaivan commented
@pudu87 thanks for making the change. I have one final grammatical fix I'd like you to push up, and then this should be good to go!

2021-12-22 18:22 UTC, pudu87 commented on rails_programming/rails_basics/asset_pipeline.md
> +* <a class="knowledge-check-link" href="https://guides.rubyonrails.org/asset_pipeline.html#main-features">How does "asset concatenation" optimizes loading of your app?</a>
Done!

2021-12-22 18:47 UTC, leosoaivan approved these changes

2021-12-22 18:47 UTC, merged