Add knowledge checks and links to Introduction to RSpec lesson
TheOdinProject/curriculum pull request #23157
Opened 2021-12-08 09:07 UTC by rusty-reebs

- [X] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [X] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [X] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
- [X] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1.Describe the changes made and include why they are necessary or important:

Add knowledge checks and links to lesson.

#### 2. Related Issue

closes #22930

2021-12-09 02:57 UTC, wise-king-sullyman requested changes
Looks good! I have a couple of small suggestions.

2021-12-09 02:57 UTC, wise-king-sullyman commented on ruby_programming/testing_with_rspec/introduction_to_rspec.md
> +- <a class='knowledge-check-link' href='#tests-folder'>In which folder do we keep our test files?</a>
```suggestion
- <a class='knowledge-check-link' href='#tests-folder'>What do you name the folder that contains your test files?</a>
```

2021-12-09 02:57 UTC, wise-king-sullyman commented on ruby_programming/testing_with_rspec/introduction_to_rspec.md
> +- <a class='knowledge-check-link' href='#expect-clauses'>How many expect clauses can we write for one test case?</a>
```suggestion
- <a class='knowledge-check-link' href='#expect-clauses'>How many expect clauses can you write for one test case?</a>
```
We want to speak in the second person in Knowledge Checks whenever it makes sense to do so.

2021-12-09 04:47 UTC, rusty-reebs commented
Sure, no problem, thanks for your help. 🙂

2021-12-09 04:50 UTC, rusty-reebs commented
I clicked Close Pull Request, not sure if I was supposed to do that. 😬

2021-12-09 18:09 UTC, wise-king-sullyman commented
I assume based on your last comment that you didn't really want to close it, so I'm reopening.

2021-12-10 03:58 UTC, wise-king-sullyman approved these changes
Thanks for doing this!

2021-12-10 03:59 UTC, merged

2021-12-10 06:04 UTC, rusty-reebs commented
No worries!