Added Spotlight instructions for Mac users
TheOdinProject/curriculum pull request #23302
Opened 2022-01-11 19:20 UTC by atkinsdavid

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [x] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Added instructions for Mac users to use Spotlight search to open Terminal. I felt like this was very inline with the idea further down the page, "Programmers are lazy."

#### 2. Related Issue

N/A

2022-01-11 19:26 UTC, I3uckwheat requested changes

2022-01-11 19:26 UTC, I3uckwheat commented on foundations/installations/command_line_basics.md
> +- **Linux**: open the programs menu and search for "Terminal". You can also open the terminal by pressing `CTRL + ALT + T` on your keyboard.
Hey, can we remove these additional whitespaces :D

2022-01-11 19:39 UTC, xandora commented on foundations/installations/command_line_basics.md
> +- **MacOS**: Open your Applications > Utilities folder and find "Terminal". You can also use Mac's Spotlight search to open Terminal. Press 'CMD + SPACE' to open Spotlight, and search for "Terminal"
We can drop this bit and assume it's a macOS feature givin we're in the macOS specific instructions. Also, let's get their product name right with `macOS`. :)

```suggestion
- **macOS**: Open your Applications > Utilities folder and find "Terminal". You can also use Spotlight search to open Terminal. Press `CMD + SPACE` to open Spotlight, and search for "Terminal". Press `RETURN` to open it.
```

2022-01-11 19:40 UTC, I3uckwheat commented on foundations/installations/command_line_basics.md
> +- **Linux**: open the programs menu and search for "Terminal". You can also open the terminal by pressing `CTRL + ALT + T` on your keyboard.
Two newlines will force a new line to be displayed.

```
from
this
```

```
to

this
```

2022-01-12 15:47 UTC, I3uckwheat approved these changes

2022-01-22 19:04 UTC, wise-king-sullyman approved these changes
Looks great, thanks!

2022-01-22 19:04 UTC, merged