Slight typo in comments of DOM Methods.
TheOdinProject/curriculum pull request #23323
Opened 2022-01-15 05:30 UTC by Utkarsh736

- [x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [x] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [x] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [x] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Hey, while going through the different methods when I saw comments explaining the methods,
I got a bit confused with the comment  //select the container div. 

Like does the command selects the div or are we required to select the div ourselves after that command.
I think it should be 'selects' as was in the 4th comment.
I have made similar changes in other comments as well.

#### 2. Related Issue

Closes #XXXXX

2022-01-15 06:29 UTC, twalton83 commented
It looks like this is using the imperative voice.

2022-01-15 07:03 UTC, Utkarsh736 commented
> It looks like this is using the imperative voice.

Thanks for the reply, but could you elaborate on this a bit more.
Also, which one do you refer to with 'this', the original sentence or my suggestion?

2022-01-15 07:14 UTC, twalton83 commented
Meaning, the comments are written with an imperative voice, and your updates remove that.

2022-01-15 07:49 UTC, Utkarsh736 commented
Honestly, I'm not good with understanding voices and which to use when.

But I feel it should be uniform in whichever way it is,
Like the first 3 comments in the "Targeting node with selectors" section use the word 'select',
and the 4th comment uses the word 'selects'.
 
Similarly in other comments, it starts one way and changes midway.

The confusion for me personally was,
That I found it a bit confusing as to whether the comment is explaining to me the functioning of the command or if it was telling me to select something after that command.

P.S. Sorry for being an inconvenience but I am new to this, so feel free to comment if I am breaking some protocols or etiquettes.

2022-01-15 07:53 UTC, twalton83 commented
It’s not an inconvenience, the review process is making comments and observations about the changes, just to be clear.

2022-01-15 07:57 UTC, Utkarsh736 commented
Oh Ok, Thanks for the clarification.

2022-01-22 19:22 UTC, zachmmeyer requested changes
Looking like we were already using `selects`, the comments here should be consistent and using `selects` seems most correct. Only a few requested changes here.

2022-01-22 19:22 UTC, zachmmeyer commented on foundations/javascript_basics/DOM_manipulation_and_events.md
> +// if id exists updates it to 'theDiv' else creates an id
```suggestion
// if id exists, update it to 'theDiv', else create an id
```

2022-01-22 19:22 UTC, zachmmeyer commented on foundations/javascript_basics/DOM_manipulation_and_events.md
> +// if div doesn't have class "active" then adds it, or if
```suggestion
// if div doesn't have class "active" then add it, or if
```

2022-01-22 19:22 UTC, zachmmeyer commented on foundations/javascript_basics/DOM_manipulation_and_events.md
> +// it does, then removes it
```suggestion
// it does, then remove it
```

2022-01-23 09:40 UTC, Utkarsh736 commented
Hey, @zachmmeyer Thanks for the reply.
Can you tell me what I'm supposed to do here `commit suggestion` or `resolve conversation`?

2022-01-23 14:39 UTC, zachmmeyer commented
> Hey, @zachmmeyer Thanks for the reply.
> Can you tell me what I'm supposed to do here `commit suggestion` or `resolve conversation`?

Commit suggestion would make the changes requested.

2022-01-23 15:22 UTC, Utkarsh736 commented
Thanks,
I've done `commit suggestions` for the 3 suggestions,
Comment if anything else is needed from my side.

2022-01-23 16:47 UTC, zachmmeyer approved these changes
Thanks for contributing and making these changes!

2022-01-23 16:47 UTC, merged