Create lesson for Foundations to warn against companies like Revature
TheOdinProject/curriculum pull request #23333
Opened 2022-01-17 19:20 UTC by jernestmyers

- [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [ ] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [ ] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [ ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

BriggsE was addressing a common question in #getting-hired about companies that have strict, onerous contracts like Revature. He and Tati both lamented at how often they must address these types of questions and suggested having a pin or thread to which to refer future people. I offered to help write it.

After some research, I wrote this and shared it with BriggsE on the contributions channel. He suggested I turn it into a lesson and create a PR. Well, here it is!

I wasn't certain where it fits into the curriculum, so I made my best judgment call by inserting it into the Conclusion section (in the tying_it_all_together directory) of Foundations.

#### 2. Related Issue

n/a

2022-02-01 22:04 UTC, zachmmeyer commented
Getting final word on this and then I will comment.

2022-02-01 22:09 UTC, I3uckwheat commented
@jernestmyers 

Hey! Apologies for the delay, been really busy with things!

A couple things, this shouldn't go in foundations, it really would fit better in the `/getting_hired` directory. Also, we should find a place to *link* this in another lesson. 

I wasn't clear in my intent in chat, we should link this in a lesson instead of creating a new one for this, however, it's fine to just leave this as a markdown file as long as we put it in the right spot.

2022-02-01 22:12 UTC, I3uckwheat requested changes
Please move this to a proper directory.

2022-02-01 22:19 UTC, zachmmeyer commented
@jernestmyers If you have a site you'd want to host this article, and have that linked in the getting hired section, that also works!

2022-02-01 23:18 UTC, I3uckwheat requested changes

2022-02-01 23:18 UTC, I3uckwheat commented on foundations/tying_it_all_together/hire-beware.md
> +People often ask questions on Discord about companies that offer free, paid training and then contract you out as consultants. Probably the most prominent company that uses this model is Revature. Bu
We should avoid the pattern of using hyphens in place of using commas: 
`his model and- while the details may vary- they wil...` -> `this model, while the details may vary, they will...`

This should be reflected across the writing.

2022-02-01 23:18 UTC, I3uckwheat commented on foundations/tying_it_all_together/hire-beware.md
> +Many accounts stress the need to be ready to relocate in a moment’s notice and to have the financial means/savings to do so. While many people stay on at one location during their contract, many othe
> Plus plus, you have no choice as to where you will move.
May want to think of another way to write this, instead of "Plus plus"

2022-02-02 16:06 UTC, jernestmyers commented on foundations/tying_it_all_together/hire-beware.md
> +You finished Foundations, congratulations! You may be tempted- like many before you- to consider applying to jobs. But the reality is that you only know the basics of web development and are far from
I'm wondering if it is indeed easier for me to just throw this on dev.to to then be linked somewhere. I'm working on that approach as of now while also knocking out the appropriate edits.

2022-02-02 16:07 UTC, twalton83 commented
I’m of the opinion we put this in the blog repo.

2022-02-02 16:23 UTC, jernestmyers commented
@twalton83 To that end I'll continue down the path of throwing this up, with relevant edits, to DEV.to.

2022-02-02 19:36 UTC, jernestmyers commented
I've moved the markdown to the blog repo and [created a pull request there](https://github.com/TheOdinProject/blog/pull/1). I'm not sure if that was the intended workflow for this, so I apologize in advance if I broke convention.

2022-02-05 21:31 UTC, wise-king-sullyman commented
Based on my understanding of the current state of things it looks like this PR should be closed since the content has now been moved to the blog repo under a separate PR.

If this is incorrect please feel free to reopen.

2022-02-05 21:31 UTC, closed without merging