Add anti-deletion comment on empty Additional Resources markdown
TheOdinProject/curriculum pull request #23363
Opened 2022-01-24 03:35 UTC by zachmmeyer

- [X] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [X] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [X] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [ ] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [X] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Several people make a PRs to remove empty Additional Resource sections from lessons, which is something that is not wanted currently. Therefore, a cautionary comment should be added to notify contributors to not make this mistake.

#### 2. Related Issue

No related issue.

2022-01-24 04:09 UTC, thatblindgeye reviewed
So for Additional Resources, I do include in the updated lesson/project style guide some instructions about not deleting this section as well as changing the default verbiage when the section is empty (so instead of just an empty section, there'll be a default bullet asking users to improve the lesson essentially).

Do you think the anti-deletion comment would be good to have either in addition to that or until lessons are updated to follow the updated style guide? Disclosre: I have no strong opinion either way, mainly want to get your take. If you still want to move forward with this I'll approve it.

2022-01-24 04:15 UTC, zachmmeyer commented
> So for Additional Resources, I do include in the updated lesson/project style guide some instructions about not deleting this section as well as changing the default verbiage when the section is empty (so instead of just an empty section, there'll be a default bullet asking users to improve the lesson essentially).
> 
> Do you think the anti-deletion comment would be good to have either in addition to that or until lessons are updated to follow the updated style guide? Disclosre: I have no strong opinion either way, mainly want to get your take. If you still want to move forward with this I'll approve it.

If there will be a bullet that will be visible on the site that asks for contribution for an empty Additional Resources, this would not be necessary then. Do we want to add that verbiage now to this specific instance instead of an invisible comment? I'm down to repurpose this PR. It's still for alerting the user to not create PRs to remove Additional Resources, and also encourages them to add content.

2022-01-24 04:24 UTC, thatblindgeye commented
I'll say not *yet*, just because I'm still waiting on my PR for the updated style guide to get approved. But I'm going to leave this open and once that gets approved I'll make a change request on this.

2022-01-30 14:13 UTC, thatblindgeye requested changes

2022-01-30 16:56 UTC, thatblindgeye approved these changes

2022-01-31 12:48 UTC, merged