Fix grammar in Forms Basic lesson
TheOdinProject/curriculum pull request #23412
Opened 2022-01-26 19:11 UTC by eltonbautista

- [X ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [X ] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ X] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [X ] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [X ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Extra 'a' on line 417 causes a grammar issue. 

#### 2. Related Issue

Closes #XXXXX

2022-01-26 20:01 UTC, zachmmeyer commented
If you can resolve this conflict, it can be approved. I actually like this change. We did have a recent fix, but this one seems to be more correct.

2022-01-26 20:22 UTC, eltonbautista commented
I think I've resolved the conflict. I've never done it before so I'm not sure if I did it correctly though. I tried resolving it from my terminal, but it showed that there were no conflicts. I just resolved the conflict in the widget found on this PR.

2022-01-28 10:21 UTC, zachmmeyer requested changes
One minor change!

2022-01-28 10:21 UTC, zachmmeyer commented on html_css/intermediate_html/form-basics.md
> +
Looks like a line was accidentally added when you fixed the conflict. If you could take that out, we'll be done!

```suggestion
```

2022-01-28 18:14 UTC, eltonbautista reviewed
Oh sorry about that I didn't even notice. I think I've gone ahead and made the suggested change. Thanks!

2022-01-28 19:27 UTC, zachmmeyer approved these changes
Thank you!

2022-01-28 19:27 UTC, merged