Grammar fix on line 148
TheOdinProject/curriculum pull request #23431
Opened 2022-01-28 21:05 UTC by eltonbautista

- [X] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [X] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [X] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [X] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [X] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Just added "that of which" to make the grammar clearer and easier to understand! 

#### 2. Related Issue

Closes #XXXXX

2022-01-29 14:03 UTC, CouchofTomato commented on html_css/intermediate_html/form-validations.md
> +The pattern attribute can only be used on `<input>` elements. Some input elements already validate data that of which matches a certain pattern. For example the email input field which will make sure
Can't we just simplify this to "data that matches a certain pattern"?

2022-02-05 22:17 UTC, wise-king-sullyman requested changes
I agree with @CouchofTomato, I think the "of which" is unnecessary.

2022-02-05 22:26 UTC, wise-king-sullyman commented
Additionally just so that you know for the future, please reference the lesson being changed in the title of PRs you make.

I've already edited this PR title so there isn't anything you need to do at this time.

2022-02-08 17:47 UTC, eltonbautista commented
Okay I can do that. I hit the commit in wise-king-sullyman's suggestion, does that create the change or do I have to do it from the terminal on my computer? Sorry quite new at this.

2022-02-10 05:55 UTC, wise-king-sullyman commented
Hitting the "commit this suggestion" button automatically adds it to the branch PR. No need to be sorry for asking a question 🙂

2022-02-10 05:55 UTC, wise-king-sullyman reviewed
Good change, thanks!

2022-02-10 05:55 UTC, merged