fixed typo
TheOdinProject/curriculum pull request #23447
Opened 2022-01-31 01:04 UTC by chrisbarbas

- [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [ ] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) and reference it with the `#` sign and the issue number.
 - [ ] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [ ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

Removed 'can' from the sentence "Sometimes their examples could can be more useful."

2022-01-31 22:33 UTC, thatblindgeye requested changes

2022-01-31 22:33 UTC, thatblindgeye commented on html_css/intermediate_css/enhancing-design-with-css.md
> +* [CSS Tricks](https://css-tricks.com/almanac/properties) has some really great content. Some of it feels less formal and official than the MDN docs, but that means they can be easier to digest.  Som
I think `could` is the word that should be removed here as it sounds like the text is saynig the CSS Tricks article *can* be more useful than MDN sometimes.

```suggestion
* [CSS Tricks](https://css-tricks.com/almanac/properties) has some really great content. Some of it feels less formal and official than the MDN docs, but that means they can be easier to digest.  Sometimes their examples can be more useful. For example, check out their pages on the [background shorthand](https://css-tricks.com/almanac/properties/b/background/), or [overflow](https://css-tricks.com/almanac/properties/o/overflow).
```

2022-01-31 22:34 UTC, thatblindgeye commented
Additionally, @chrisbarbas, please re-read the PR template and ensure you've followed it correctly (specifically the title of the PR)

2022-01-31 22:53 UTC, thatblindgeye requested changes
Last thing it looks like. Thank you for making the update!

2022-01-31 22:53 UTC, thatblindgeye commented on html_css/intermediate_css/enhancing-design-with-css.md
> +* How would you use border-radius to make a circular element?
Should be the last thing. I believe we need a new line at the end of the lesson files.

2022-02-01 12:24 UTC, thatblindgeye commented
@chrisbarbas just wanted to let you know I updated the title of this PR

2022-03-10 11:52 UTC, 01zulfi commented
@chrisbarbas Are you still available to make the requested changes? Following inactivity over the next few days, this pull request will be closed and an issue will be put up for anyone to make these changes.

2022-03-27 13:38 UTC, zachmmeyer commented
Closed due to being stale.

2022-03-27 13:38 UTC, closed without merging