Missing a description for the :focus Psuedo-Class in CSS-Selectors lesson.
TheOdinProject/curriculum pull request #23463
Opened 2022-02-01 04:40 UTC by BrandonSigil

Reworded the definition that CSS-tricks give for the focus selector and applied it to the lesson.

 - [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).
 - [ ] The title summarizes the change and where it happened, for example: "Fixes punctuation in Clean Code lesson".
 - [ ] If the PR is related to an open issue, use a [relevant keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) and reference it with the `#` sign and the issue number.
 - [ ] You have previewed your markdown (if any) in the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview)
 - [ ] If changes are requested, please make the changes in a timely manner. After you submit the changes, request another review from the maintainer (top right).

#### 1. Describe the changes made and include why they are necessary or important:

...your text here

#### 2. Related Issue

Closes #XXXXX

2022-02-01 04:40 UTC, BrandonSigil commented
Added a definition to the :pseudo class-selector text in this lesson.

2022-02-01 12:30 UTC, thatblindgeye requested changes
Thank you for the (second) first time contribution! Agreed this should be updated, just have a very minor request below.

2022-02-01 12:30 UTC, thatblindgeye commented on html_css/intermediate_css/selectors.md
> +[:`focus`](https://css-tricks.com/almanac/selectors/f/focus/) applies to an element that is currently selected by the user either through selecting it with their cursor or using their keyboard.
We should put the colon inside the code backticks here. If you could also update line 101 (the `:active` selector) that would be perfect, too.

```suggestion
[`:focus`](https://css-tricks.com/almanac/selectors/f/focus/) applies to an element that is currently selected by the user either through selecting it with their cursor or using their keyboard. 
```

2022-02-01 17:33 UTC, BrandonSigil commented
I think I accepted your changes @thatblindgeye. I "committed" your suggestion, I believe. First time doing this! Thanks for the help :)

2022-02-01 22:50 UTC, thatblindgeye requested changes
I'm not able to select the line to suggest a chance, but could you also update line 101 to:

[`:active`]

And then just update the PR title to something along the lines of "Fixed selectors in CSS-Selectors lesson"?

2022-02-02 21:39 UTC, BrandonSigil commented
Sure thing! I believe I did that right.

2022-02-03 05:10 UTC, thatblindgeye approved these changes

2022-02-03 05:10 UTC, merged