Ruby debugging lesson: VSCode update
TheOdinProject/curriculum pull request #23647
Opened 2022-02-23 20:42 UTC by mgrigoriev8109

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

**1. Because:**
Closes #23633

**2. This PR:**
Is a work in progress for updating the current [Ruby Debugging lesson](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/debugging) to include the VSCode Debugging tool. Due to the importance of the concepts covered in the beginning of the lesson (stack trace, using `p`, using pry) I didn't touch any of that content.

The content I added is all in the Assignments, and focused on:
1) Guiding learners to install the VSCode debugger
2) Editing their launch.json Configuration 
3) Encouraging them to play with the VSCode Debugger and see the similarities to the Dev Tools debugger they already learned about
4) Pointing out the similar functionality of `binding.break` to `binding.pry`, and the importance of practicing using `pry` even though the VSCode Debugger exists

2022-02-23 20:45 UTC, zachmmeyer approved these changes
This is really great! Thank you for doing this!

2022-02-23 20:56 UTC, mgrigoriev8109 commented
I'm actually wondering if telling learners about `binding.break` is a bit much all at once, since the lesson literally just introduced `pry-byebug` and no one has really gotten a chance to practice that in their projects.

So I wonder if I should remove the mention of `binding.break`, and in the **Assignment** section stick to stating that while you *can* use the VSCode Debugger, you should still practice using `pry-byebug` on its own due to its current popularity as a Debugging tool.

2022-02-24 02:02 UTC, rlmoser99 commented
@mgrigoriev8109 Thank you for taking the initiative to work on this issue. I will take a closer look at this tomorrow, but in reading your note, I am reminded that we would like to create exercises that gives people examples to practice debugging. 

https://github.com/TheOdinProject/ruby-exercises/issues/15

These do not need to have tests, like the other ones in ruby-exercises, but basically some methods with built in bugs. I am wondering if we should consider exercises to go along with this lesson before we merge in these updates. 

Would you be interested in coming up with examples? The trickiest part would be coming up with examples without using enumerables, since those lessons are later. Maybe we could even use some of the examples from the array, hash, and method exercises.

2022-02-24 02:37 UTC, mgrigoriev8109 commented
@rlmoser99 I would definitely be interested in creating some exercises for this lesson to practice debugging. If it would be helpful I can also include tests - since learners will already be familiar with that format.

2022-02-26 17:23 UTC, mgrigoriev8109 commented
Just now updated the Assignment while checking all the instructions on a newly installed VM, everything worked for me getting the VSCode debugger running but I'd love input on how I can make things easier to understand. 

I'll now be working on the debugging exercises that I'll insert into the end of this lesson as practice, and should have a PR ready for https://github.com/TheOdinProject/ruby-exercises/issues/15 by the end of the week. I'm going to create a couple exercises instructing learners to rely on the stack trace, a couple instructing them to rely on `puts`, a couple instructing them to rely on `pry-byebug`, and a couple instructing them to use the VSCode debugger GUI.

2022-03-01 00:37 UTC, zachmmeyer requested changes
I found like one typo.
I followed the instructions and it works perfectly. Really awesome. Excited for the exercises!

2022-03-01 00:37 UTC, zachmmeyer commented on ruby_programming/basic_ruby/debugging.md
> +6. Now that everything is installed, configured, let's create a new file which you can call `script.rb`. Next copy and paste the very first example in the<a href='#debugging-with-pry-byebug'>Debuggin
```suggestion
6. Now that everything is installed, configured, let's create a new file which you can call `script.rb`. Next copy and paste the very first example in the <a href='#debugging-with-pry-byebug'>Debugging with pry-byebug</a> Section. So include everything from `require 'pry-byebug'` to `isogram?("Odin")` in our new file. Save the file. 
```

2022-03-02 18:40 UTC, zachmmeyer commented
@mgrigoriev8109 Let me know when we're good!

2022-03-03 21:11 UTC, mgrigoriev8109 commented
@zachmmeyer I created a pull request for the Ruby Debugging exercises: https://github.com/TheOdinProject/ruby-exercises/pull/69

, so once that pull request is reviewed and approved (Or any requested changes are made) this lesson should be all ready to go!

2022-03-03 21:21 UTC, zachmmeyer commented
@mgrigoriev8109 Understood!

2022-03-04 02:10 UTC, merged