Sign up project: Changed project steps to better reflect expected knowledge
TheOdinProject/curriculum pull request #23652
Opened 2022-02-24 19:23 UTC by NotAtec

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #23643

**2. This PR:**

- Changed usage of `focus` class to `:focus` pseudo-class since the student should have knowledge about pseudo-classes before they start this project.
- Broke up the step in 2, to make it easier to understand and match more with the shorter steps in other projects.

**3. Additional Information:**

2022-02-25 22:32 UTC, dm-murphy requested changes
Thanks for fixing these instructions! I like the breakdown of the steps here overall. But because this separates the two variations into two bullets, I think it needs a little rephrasing for this bullet to indicate this is the first step of two. I added in a suggestion if you'd like to use that or you could come up with another way of phrasing it.

2022-02-25 22:32 UTC, dm-murphy commented on html_css/project-sign-up-form/project-sign-up-form.md
> +4. The inputs, by default have a very light border (`#E5E7EB`), but we've included 2 variations. The password inputs should be given an `error` class.
```suggestion
4. The inputs, by default have a very light border (`#E5E7EB`), but we've included 2 variations. For starters, the password inputs should be given an `error` class.
```

2022-02-25 23:17 UTC, NotAtec commented
The suggestion looks good to me, so comitted it as you've phrased it

2022-02-26 02:30 UTC, dm-murphy approved these changes
Thanks!

2022-02-26 02:30 UTC, merged