Meta/63 real world git update
TheOdinProject/curriculum pull request #23663
Opened 2022-02-26 16:43 UTC by wise-king-sullyman

Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

TheOdinProject/top-meta/issues/63

**2. This PR:**

Updates the curriculum content as specified in that issue.

**3. Additional Information:**

2022-02-28 15:47 UTC, 01zulfi requested changes
The changes look great!

I've left a couple of comments below. Other than that, I have a question. Is there a reason we're using the `$` sign for every git command? I know it's used to identify that the command should be run in the terminal, but I believe this is something users reading this lesson should already be familiar with. Let me know if it's a non-issue and/or any other thoughts you have regarding it.

2022-02-28 15:47 UTC, 01zulfi commented on ruby_programming/git/lesson_using_git_in_the_real_world.md
> +Let's say you want to contribute to the web application that powers this website (it's a different repo than our curriculum content, you can check it out [here](https://github.com/TheOdinProject/theo
We could improve the link text here

2022-02-28 15:47 UTC, 01zulfi commented on ruby_programming/git/lesson_using_git_in_the_real_world.md
> +1. Note that a `$ git fetch upstream` followed by a `$ git merge upstream/some_branch` is the EXACT same thing as doing a `$ git pull upstream/some_branch`.  I prefer to split it up so I can explicit
```suggestion
1. Note that a `$ git fetch upstream` followed by a `$ git merge upstream/some_branch` is the EXACT same thing as doing a `$ git pull upstream/some_branch`.  We prefer to split it up so we can explicitly walk through the steps.
```

2022-03-01 04:11 UTC, wise-king-sullyman commented on ruby_programming/git/lesson_using_git_in_the_real_world.md
> +Let's say you want to contribute to the web application that powers this website (it's a different repo than our curriculum content, you can check it out [here](https://github.com/TheOdinProject/theo
Great catch!

2022-03-01 04:12 UTC, wise-king-sullyman commented
@01zulfi no reason I kept the `$` other than it was there and I didn't think to delete it. You're right, doesn't need to be there.

2022-03-01 13:30 UTC, 01zulfi approved these changes

2022-03-02 03:00 UTC, merged