Updated Intermediate HTML and CSS/Creating a Grid/Gap Section
TheOdinProject/curriculum pull request #23786
Opened 2022-03-14 02:49 UTC by iawong

Complete the following REQUIRED checkboxes:

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #23784

**2. This PR:**

- Replaced the last sentence in the first paragraph with "Furthermore, we can use a shorthand property called gap to set both row-gap and column-gap."
- Added a paragraph after the 3rd CodePen telling users that they can set the row-gap and column-gap using gap, gave an example explaining the syntax of using gap, and encouraged users to try it out.
- Changed the last paragraph to explain how gap can be used to set both the row-gap and column-gap to the same value. 

**3. Additional Information:**

2022-03-15 13:00 UTC, 01zulfi requested changes
The changes look great. Just one requested change below.

2022-03-15 13:00 UTC, 01zulfi commented on html_css/grid-lessons/creating-a-grid.md
> +Alternatively, we can set both the `row-gap` and `column-gap` by just using `gap`. For example: `gap: 10px 20px;` where the first value contains the `row-gap` and the second value contains the `colum
Wording suggestion:
```suggestion
Alternatively, we can set both the `row-gap` and `column-gap` by just using `gap`. For example: `gap: 10px 20px;` where the first value contains the `row-gap` and the second value contains the `column-gap`. Try using `gap` to change the `row-gap` and `column-gap` values in the above CodePen embed. 
```

2022-03-18 01:28 UTC, dm-murphy commented on html_css/grid-lessons/creating-a-grid.md
> +If we wanted the columns and rows to share the same gap value we can omit the `column-gap` property so it looks something like `gap: 25px;`. When a `column-gap` isn't specified, the value of the `col
```suggestion
If we wanted the columns and rows to share the same gap value we can omit the `column-gap` property so it looks something like `gap: 25px;`. When a `column-gap` isn't specified, the value of the `column-gap` is assumed to be the same value as the `row-gap`.
```

2022-03-18 01:53 UTC, dm-murphy requested changes
Although the changes here highlight some of the shorthand usage of the `gap` property, these were intentionally left out of the lesson when it was written. The point of the Creating a Grid lesson is to give a very simple walkthrough on the use of `grid` without overwhelming a beginner. Remember this is a lesson on creating a grid, not a lesson on `gap`.

While sometimes we touch upon shorthand properties, like this lesson's mention of `gap`, we also do our best not to overwhelm learners when learning a new concept with too much information or shorthand variations. It is easier for a beginner to visually separate `row-gap` and `column-gap` as two separate properties.

I do think the change on the first paragraph to this section is good (line 132) and further explains what the shorthand `gap` is doing : "Furthermore, we can use a shorthand..."

Perhaps the final paragraph could be reworded to imply that `gap` has other uses or learners could play around with it as a shorthand.

Regardless, the CSS Tricks article that is linked throughout the Assignments in this Grid curriculum series goes over all of the shorthand uses for `gap`.

2022-03-18 15:07 UTC, 01zulfi requested changes
Based on @dm-murphy's comment, we should update the final paragraphs.

@iawong Can you replace the final two paragraphs of the "Gap" section that you've added with:

"You can also try playing with the shorthand `gap` to set both the `row-gap` and `column-gap` in the above CodePen."

2022-03-21 15:16 UTC, iawong commented
Hey, I've removed the last 2 paragraphs and replaced them.

2022-03-21 15:27 UTC, 01zulfi approved these changes
Looks great! Thanks for doing this 🚀

2022-03-21 15:27 UTC, merged