CSS Units lesson: Improve punctuation
TheOdinProject/curriculum pull request #23891
Opened 2022-03-25 12:15 UTC by Overlandcoder

Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-03-26 04:39 UTC, 01zulfi requested changes

2022-03-26 04:39 UTC, 01zulfi commented on html_css/intermediate_css/css-units.md
> +Using a relative size like `rem` to define font sizes across your website _is_ recommended. Many browsers allow users to change the base font-size to increase readability. If at all possible, it is a
Wording suggestion:
```suggestion
Using a relative size like `rem` to define font sizes across your website _is_ recommended. Many browsers allow users to change the base font-size to increase readability. If at all possible, it is advisable to respect a user's wishes regarding font size. You'll learn more about this from the reading assignments.
```

2022-03-26 12:06 UTC, Overlandcoder commented on html_css/intermediate_css/css-units.md
> +Using a relative size like `rem` to define font sizes across your website _is_ recommended. Many browsers allow users to change the base font-size to increase readability. If at all possible, it is a
> Wording suggestion:

I agree with that.

2022-03-27 05:37 UTC, 01zulfi approved these changes

2022-03-27 05:37 UTC, merged