Asking for help lesson: Update verbiage
TheOdinProject/curriculum pull request #23946
Opened 2022-04-01 00:34 UTC by nguyens20

Updated the verbiage and formatting for the Asking for help lesson in the Foundations course.

Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #23928 

**2. This PR:**
Changed Learning Outcomes to Lesson Overview
 -->Update the format for some of the Knowledge Check items.

**3. Additional Information:**

2022-04-03 23:52 UTC, thatblindgeye requested changes

2022-04-03 23:52 UTC, thatblindgeye commented on foundations/introduction/asking_for_help.md
>  By the end of this lesson, you should be able to do the following:
The line below the heading should also be updated.

2022-04-04 16:24 UTC, nguyens20 commented on foundations/introduction/asking_for_help.md
>  By the end of this lesson, you should be able to do the following:
Gotcha !

2022-04-04 16:44 UTC, nguyens20 commented on foundations/introduction/asking_for_help.md
>  By the end of this lesson, you should be able to do the following:
I made a new PR #23968 to update the line below the heading as well. Its my first time contributing so if I'm doing anything wrong please let me know !

2022-04-04 21:34 UTC, thatblindgeye approved these changes
Ah disregard my original comment. Just saw your comments on the issue itself. Will reclose this and go to the most recent PRs.

2022-04-04 21:37 UTC, closed without merging