Update assignment-CSS: Remove note about outdated CSS Grid section.
TheOdinProject/curriculum pull request #23953
Opened 2022-04-01 14:42 UTC by swifteye1111

DevTools page has now separated "Inspect CSS Grid" from the linked CSS page.

Complete the following REQUIRED checkboxes:

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-04-03 23:51 UTC, thatblindgeye requested changes
Thank you for the changes. Can you please update your initial comment sot that tempalte is filled out correctly (checkboxes, the reason for the PR in the "Because" step, and what this PR does in the second step)

2022-04-06 12:18 UTC, swifteye1111 commented
> Thank you for the changes. Can you please update your initial comment sot that tempalte is filled out correctly (checkboxes, the reason for the PR in the "Because" step, and what this PR does in the second step)

I have updated it as you requested.

2022-04-06 12:24 UTC, thatblindgeye requested changes

2022-04-06 12:24 UTC, thatblindgeye commented on foundations/html_css/inspecting-html-and-css/inspecting-html-and-css.md
> +- [CSS](https://developer.chrome.com/docs/devtools/css): be sure to follow along with any interactive instructions!
One last change:

```suggestion
- [View and change CSS](https://developer.chrome.com/docs/devtools/css): be sure to follow along with any interactive instructions!
```

2022-04-06 12:36 UTC, thatblindgeye approved these changes

2022-04-06 12:36 UTC, merged