Ruby Path - Ruby on Rails -> Controlers: Swaps whitelist for allowlist
TheOdinProject/curriculum pull request #24008
Opened 2022-04-12 00:57 UTC by MLGabe

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**
Swapping the wording from whitelisting to allowlisting. Whitelisting implies blacklisting which can be viewed as a racist term.
https://www.vice.com/en/article/v7dd3d/we-need-to-stop-saying-blacklist-and-whitelist

**2. This PR:**
- Simple swap of words

**3. Additional Information:**

2022-04-16 22:56 UTC, KevinMulhern commented
Hey @MLGabe, thanks for contributing. I find `allowlisted_post_params` a little awkward to read, can it be changed to `allowed_post_params` instead please?

2022-04-18 02:03 UTC, MLGabe commented
I agree. Made the change :)

2022-04-18 02:03 UTC, MLGabe commented
@KevinMulhern 
I agree, change made :)

2022-04-18 22:06 UTC, KevinMulhern requested changes

2022-04-18 22:06 UTC, KevinMulhern commented on ruby_on_rails/rails_basics/controllers.md
> +*Note: This used to be done in Rails 3 by setting `attr_accessible` in the model to allowlist attributes, so you will probably see that in a lot of Stack Overflow posts and earlier applications.*
```suggestion
*Note: This used to be done in Rails 3 by setting `attr_accessible` in the model to allow attributes, so you will probably see that in a lot of Stack Overflow posts and earlier applications.*
```

2022-04-18 22:06 UTC, KevinMulhern commented on ruby_on_rails/rails_basics/controllers.md
> +To "allowlist", or explicitly allow, parameters, you use the methods `require` and `permit`.  Basically, you `require` the name of your array or hash to be in Params (otherwise it'll throw an error),
```suggestion
To explicitly allow parameters, you use the methods `require` and `permit`.  Basically, you `require` the name of your array or hash to be in Params (otherwise it'll throw an error), and then you `permit` the individual attributes inside that hash to be used.  For example:
```

2022-04-20 23:34 UTC, KevinMulhern commented on ruby_on_rails/rails_basics/controllers.md
> +This will allowlist and return the hash of only those params that you specified (e.g. `{:title => "your title", :body => "your body", :author_id => "1"}` ).  If you didn't do this, when you tried to
Apologies @MLGabe, just one more.
```suggestion
This will return the hash of only those params that you explicitly allow (e.g. `{:title => "your title", :body => "your body", :author_id => "1"}` ).  If you didn't do this, when you tried to access params[:post] nothing would show up! Also, if there were any additional fields submitted inside the hash, these will be stripped away and made inaccessible (to protect you).
```

2022-04-20 23:45 UTC, MLGabe commented on ruby_on_rails/rails_basics/controllers.md
> +This will allowlist and return the hash of only those params that you specified (e.g. `{:title => "your title", :body => "your body", :author_id => "1"}` ).  If you didn't do this, when you tried to
No problem, sorry for not picking it up!
Already changed :)

2022-04-21 18:39 UTC, KevinMulhern approved these changes
Thanks @MLGabe, this looks great 🥇

2022-04-21 18:39 UTC, merged