React Introduction lesson: Add a link to React Developer Tools Chrome Extension
TheOdinProject/curriculum pull request #24010
Opened 2022-04-12 14:17 UTC by DaeguDude

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #24003

**2. This PR:**

- Added a link to React Developer Tools Chrome Extension

**3. Additional Information:**

2022-04-12 15:19 UTC, 01zulfi requested changes

2022-04-13 00:56 UTC, DaeguDude commented on javascript/react-js/react-introduction.md
> +React Developer Tools is an extension to the browser developer tools which allows you to inspect React components that build the page. It helps you to check and edit the React component tree as well
I thought we needed to actually replace React Developer Tools by chrome extension not npm package which was introduced in the article. Should I leave that pluralsight article, and add chrome React Developer Tools chrome extension along with it?

2022-04-14 00:36 UTC, DaeguDude commented on javascript/react-js/react-introduction.md
> +React Developer Tools is an extension to the browser developer tools which allows you to inspect React components that build the page. It helps you to check and edit the React component tree as well
That makes sense. I've never used npm package for react developer tools, so I guess I was a bit mistaken. Will add the article back and add the chrome extension alongside.

2022-04-14 08:36 UTC, 01zulfi approved these changes
Looks good :rocket:

2022-04-14 08:36 UTC, merged