fundamentals-3.md: add additional resource
TheOdinProject/curriculum pull request #24090
Opened 2022-05-01 21:18 UTC by AshkanArabim

Added a link to a W3schools page about JavaScript function parameters that also explains how the 'arguments' object works.

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-05-04 02:05 UTC, wise-king-sullyman reviewed
I think that this is a good topic to add an additional resource about, but I wonder if this lesson is an ideal place to add it since we don't cover objects until fundamentals five. I'll think on it and circle back 🙂

2022-05-11 02:13 UTC, wise-king-sullyman requested changes
Per my previously discussed reasoning I think this would be a better additional resource in fundamentals 5, can you move it to that lesson?

2022-05-12 04:34 UTC, AshkanArabim commented
I removed the additional resource about arguments that I had added before. I will open another pull request to add it to the 'fundamentals 5' section.

2022-05-13 03:39 UTC, wise-king-sullyman commented
@AshkanArabim you can just add it to that lesson in this PR if you'd like, a new PR isn't needed.

2022-05-13 04:42 UTC, AshkanArabim commented
I made the requested changes.
I noticed that in fundamentals-5.md, unlike the others, the additional resources section was after the knowledge check section. I made the correction.

2022-05-13 12:47 UTC, wise-king-sullyman requested changes
Can you actually move the additional resources back to below the knowledge check section? That's the layout that we're going for in the future per [our lesson template](https://github.com/TheOdinProject/curriculum/blob/main/templates/lesson-template.md).

After that this should be good to go! 🙂

2022-05-19 02:53 UTC, wise-king-sullyman requested changes
Actually I have one final tweak I'd like to see, just a slight update of the link text used to keep things more accessible.

You can read about the reasoning behind this suggestion in this great [article about link text from Harvard](https://accessibility.huit.harvard.edu/technique-writing-link-text).

2022-05-19 02:53 UTC, wise-king-sullyman commented on foundations/javascript_basics/fundamentals-5.md
> +*   Learn about the 'arguments' object on [this page](https://www.w3schools.com/js/js_function_parameters.asp) about function parameters.
```suggestion
*   Learn about the 'arguments' object on this [page about function parameters](https://www.w3schools.com/js/js_function_parameters.asp).
```

2022-05-20 14:43 UTC, wise-king-sullyman approved these changes
Looks perfect, thanks!

2022-05-20 14:45 UTC, merged