Installing Ruby & various lessons: Update to use Ruby 3.1.2
TheOdinProject/curriculum pull request #24162
Opened 2022-05-26 19:07 UTC by scheals

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

 Ubuntu 22.04 comes with openSSL 3.0 installed and only Ruby 3.1+ started being compatible with it. Because of this, installing Ruby 3.0.3 is not possible on 22.04 without tinkering with openSSL installation which is not recommended. 20.04 installs are unaffected.
 
Part of #24112

**2. This PR:**

* Updates the installation instructions to use Ruby 3.1.2 
* Updates various links to the documentation to point to the 3.1.2 documentation
* Updates various links to the rubyapi version of documentation to point to the 3.1. documentation

**3. Additional Information:**

I also have to change various `.ruby-version` files to be 3.1.2, update the gems & the bundler in the repos and change description in ruby_testing, like this issue's PRs: #23434

2022-06-06 13:36 UTC, ChargrilledChook commented
Thank you for taking the time to work on this @scheals. I'd like to check with the team if there are any issues with switching over at the moment, assuming no issues there I aim to review all of your changes over the next couple of days.

2022-06-07 02:56 UTC, ChargrilledChook requested changes
Thanks very much for your work on this!

It's mostly fine, but there are some issues where you've updated links from version agnostic urls to versioned ones, which has broken them. 

There's also a handful of times where you've updated `core` in plain text to have a version next to it too.

If you can fix these up I think it should be ready to merge :+1:

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +[File](http://rubydoc.info/stdlib/core-3.1.2/File) is a core-3.1.2 ruby class that allows
@scheals I think your find and replace was a little over zealous here :wink: 

```suggestion
[File](http://rubydoc.info/stdlib/core-3.1.2/File) is a core ruby class that allows
```

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +* manipulate [file](http://rubydoc.info/stdlib/core-3.1.2/File) input and output
This link doesn't work for me, I think version agnostic links should generally be fine to leave

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +* manipulate [strings](http://rubydoc.info/stdlib/core-3.1.2/String)
This one too

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +There are numerous [String](http://rubydoc.info/stdlib/core-3.1.2/String) methods
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +[String#split](http://rubydoc.info/stdlib/core-3.1.2/String#split-instance_method)
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +[Array#each_with_index](http://rubydoc.info/stdlib/core-3.1.2/Enumerable#each_with_index-instance_method).
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +Ruby's core-3.1.2 language comes with a wealth of great classes. Not all of them are
Extra version here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +  * Use [String#rjust](http://rubydoc.info/stdlib/core-3.1.2/String#rjust-instance_method) to append zeros to the front of the string.
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +* [String#length](http://rubydoc.info/stdlib/core-3.1.2/String#length-instance_method) - returns the length of the string.
Broken links here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +[NilClass#to_s](http://rubydoc.info/stdlib/core-3.1.2/NilClass#to_s-instance_method).
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +[String#rjust](http://rubydoc.info/stdlib/core-3.1.2/String#rjust-instance_method) in
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +[String#slice](http://rubydoc.info/stdlib/core-3.1.2/String#slice-instance_method) in
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +/ruby-2.4.0/gems/google-api-client-0.15.0/lib/google/apis/core-3.1.2/http_command.rb:218:in 'check_status': parseError: Failed to parse address (Google::Apis::ClientError)
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +We need to explicitly convert our array of legislator names to a string. This way we are sure it will output correctly. This could be tedious work except Array again comes to the rescue with the [Arr
Broken link here

2022-06-07 02:56 UTC, ChargrilledChook commented on ruby/files_and_serialization/project_event_manager.md
> +[String#gsub](http://rubydoc.info/stdlib/core-3.1.2/String#gsub-instance_method) and
A few more in this file, I'll stop here pointing out each one individually :laughing:

2022-06-07 11:00 UTC, scheals commented
> Thanks very much for your work on this!
> 
> It's mostly fine, but there are some issues where you've updated links from version agnostic urls to versioned ones, which has broken them.
> 
> There's also a handful of times where you've updated `core` in plain text to have a version next to it too.
> 
> If you can fix these up I think it should be ready to merge +1

Ahhh! I didn't pick up on the fact that this lesson used `rubydoc.info` and not `ruby-doc.info`... I would prefer to change the links to the original `ruby-doc.info` here, then. I like `rubyapi.org` the most but I guess `ruby-doc.info` is fine too.

I made it version-specific so it is more in-line with the rest of curriculum which points to particular version.

And sorry for the overzealous core overwrites! There was some back-and-forth with my find-and-replace that probably resulted in this.

2022-06-07 12:23 UTC, ChargrilledChook commented
> Ahhh! I didn't pick up on the fact that this lesson used `rubydoc.info` and not `ruby-doc.info`... I would prefer to change the links to the original `ruby-doc.info` here, then. I like `rubyapi.org` the most but I guess `ruby-doc.info` is fine too.
No worries at all, it's a fairly subtle distinction.

IMO all 3 have a place; `ruby-doc` being the most 'official', `rubydoc` being the most extensive (it's auto-generated and also covers gems) and `rubyapi` being the best formatted (albeit more limited in content than the other two). 

I think `rubyapi` is my preference too, especially for core classes, but for the sake of this particular set of changes, I think it would be better to update the links 'as they are' for now. 

Certainly open to discussing switching over / being a bit more consistent in how we recommend docs, though

> I made it version-specific so it is more in-line with the rest of curriculum which points to particular version.
Yeah, the logic makes sense to me :+1: although having agnostic links is probably better to avoid having to do these rewrites every time we update

> And sorry for the overzealous core overwrites! There was some back-and-forth with my find-and-replace that probably resulted in this.
All good :smiley:

2022-06-07 15:39 UTC, scheals commented
> IMO all 3 have a place; `ruby-doc` being the most 'official', `rubydoc` being the most extensive (it's auto-generated and also covers gems) and `rubyapi` being the best formatted (albeit more limited in content than the other two).
> 
> I think `rubyapi` is my preference too, especially for core classes, but for the sake of this particular set of changes, I think it would be better to update the links 'as they are' for now.
> 

Alright, I'll revert the changes then! I do know how to convert rubydoc links to ruby-doc links now, though! :laughing: 

> Certainly open to discussing switching over / being a bit more consistent in how we recommend docs, though
> 

I believe that having a "more close encounter" with rubyapi might be beneficial. It's still the case that people in the ruby channels don't know about it and honestly it's a great resource. But that's for another issue.

> > I made it version-specific so it is more in-line with the rest of curriculum which points to particular version.
> 
> Yeah, the logic makes sense to me +1 although having agnostic links is probably better to avoid having to do these rewrites every time we update

I followed what's been done before in the curriculum at large, I think rubydoc currently links to 3.0.3 docs with its agnostic links also. Not sure whether converting everything to be agnostic makes sense because we don't know how up-to-date the curriculum is going to be in the future. The 3.0.3 -> 3.1.2 change has been pretty rapid.

Oh also rubydoc links to some [rdoc](https://rubydoc.info/stdlib/csv/file/README.rdoc) from possibly 2005 that I wasn't able to track down on ruby-doc anyway.

2022-06-07 16:06 UTC, scheals commented
@ChargrilledChook Turns out Event Manager lesson features rubydoc, ruby-doc and rubyapi links. Got my find-&-replace overzealous again. As such, I made two ruby-doc links version agnostic which seems more in line with rubydoc being agnostic too, but now rubyapi is the only version-specific one. Not sure whether rubyapi has an agnostic URL, it seems like you can chop the version off and it'll still navigate things but not sure how dependable that is.

2022-06-09 09:09 UTC, ChargrilledChook reviewed
LGTM :+1:

2022-06-09 09:10 UTC, ChargrilledChook approved these changes

2022-06-09 11:02 UTC, merged