Command Line Basics, Text Editors lessons: Moved Exercise section to Assignment section
TheOdinProject/curriculum pull request #24272
Opened 2022-06-19 09:28 UTC by muditchoudhary

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #24236

**2. This PR:**

- Removed Exercise Section from Command Line Basics Lesson.
- Add a new numbered list item to Assignment for Exercise.
- No Edit in Text Editors lesson.

**3. Additional Information:**

None.

2022-06-26 16:50 UTC, thatblindgeye requested changes
Thanks for making this update! I made a small change request below. Additionally, would you mind making an update to the "text editors" lesson and just updating the "Additional resources" heading to "Additional Resources"?

2022-06-26 16:50 UTC, thatblindgeye commented on foundations/installations/command_line_basics.md
> +3. In this exercise, you will practice creating files and directories and deleting them. You'll need to enter the commands for this exercise in your terminal. If you can't recall how to open a termin
For this line, I think we can reword it a little bit:

```suggestion
3. Let's practice creating files and directories and deleting them! You'll need to enter the commands for the steps below in your terminal. If you can't recall how to open a terminal, scroll up for a reminder.
```

Or something along those lines.

2022-07-01 04:26 UTC, muditchoudhary commented
Thank You for telling me the suggested changes. I worked on it as stated.
Other than that I reword the end message in practice. Please see if it's good.

2022-07-01 17:07 UTC, thatblindgeye reviewed
Looks great! There's just a merge conflict that needs to be resolved first. Do you want to try resolving it?

2022-07-02 03:19 UTC, muditchoudhary commented
Yes, sure!!

2022-07-02 13:04 UTC, thatblindgeye approved these changes
Thank you for working on this!

2022-07-02 13:04 UTC, merged