Ruby Nested Collections: Fix Additional Resources text
TheOdinProject/curriculum pull request #24368
Opened 2022-07-05 19:37 UTC by SpookyKasper

Additional Resources section is mentioning existence of helpful links to other content whereas there is none at the moment. 
I updated the text to make it clear and ask for suggestions :)

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-07-06 07:52 UTC, 01zulfi requested changes
Thanks for wanting to contribute! I've left a requested change below.

2022-07-06 07:52 UTC, 01zulfi commented on ruby/basic_ruby/nested_collections.md
> +Contribute on Github!
We use specific wording for cases like this. It is outlined in our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

The Additional Resources section should look like:

```suggestion

This section contains helpful links to related content. It isn’t required, so consider it supplemental.

*   It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
```

2022-09-26 22:36 UTC, wise-king-sullyman commented
@SpookyKasper are you planning to make the requested change?

2022-10-10 13:15 UTC, ChargrilledChook commented
Closing due to inactivity, happy to re-open if you would like to take this on in the future

2022-10-10 13:15 UTC, closed without merging