Added additional resources on introduction to flexbox curriculum in foundation course
TheOdinProject/curriculum pull request #24391
Opened 2022-07-08 08:18 UTC by Sajwan055

Here I have added ;
- I have added additional resource to the introduction to flexbox lesson in foundation course.
- It will help beginner to understand topic in better way.

2022-07-22 18:40 UTC, fortypercenttitanium requested changes
This looks like a fantastic resource. However, I noticed you linked only to one of the tutorials on flexbox.

In order to merge this, let's rename the link text to say "This flexbox tutorial..." as opposed to just giving the name of the site.

2022-08-04 02:48 UTC, zachmmeyer requested changes
Fix link text

2022-08-04 02:48 UTC, zachmmeyer commented on foundations/html_css/flexbox/flexbox-intro.md
> +* [interneting is hard](https://www.internetingishard.com/html-and-css/flexbox/) is a
```suggestion
* [This Flexbox tutorial](https://www.internetingishard.com/html-and-css/flexbox/) is a
```

2022-08-04 02:49 UTC, zachmmeyer approved these changes
Thanks for adding this additional resource

2022-08-04 02:49 UTC, merged

2022-08-04 05:12 UTC, Sajwan055 commented
Thank you so much for merging.

2023-08-05 07:34 UTC, sajwan05 commented
I am the ghost here sajwan055 -> sajwan05.