TheOdinProject/curriculum: Modify and add headings and section placement
TheOdinProject/curriculum pull request #24410
Opened 2022-07-11 18:58 UTC by c-yip

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #24342

**2. This PR:**

- Clean Code
    - Reorder headings
- Installing Node.js
    - Edit headings to conform with Wikipedia title case
    - Add Lesson Overview heading with content.
- DOM Manipulation and Events
    - Edit headings to conform with Wikipedia title case
- Fundamentals Part 5
    - Add Introduction heading
- Project: Calculator
    - Add pre-assignment and post-assignment headings

**3. Additional Information:**

I did not add content to many of the headings I added. All headings that were added were added to conform with the style guide.

2022-08-04 02:25 UTC, zachmmeyer requested changes
Everything looks pretty good. I had one direct change request, and you're missing the newlines at the end of the files.

2022-08-04 02:25 UTC, zachmmeyer commented on foundations/javascript_basics/project_calculator.md
> +### POST-ASSIGNMENT SECTION HEADING
```suggestion

```
I don't believe this is necessary. It also would just say `POST-ASSIGNMENT SECTION HEADING` which wouldn't look very good. You're supposed to write something else, but I don't think anything would go here.

2022-08-05 19:52 UTC, zachmmeyer commented
@c-yip Are you able to resolve the merge conflicts?

2022-08-05 19:56 UTC, c-yip commented
@zachmmeyer I will resolve the merge conflicts right now. 

Regarding the newlines at the end of the files, my local repo shows newlines at all the files I made commits to. I am not sure why the newlines do not show up on GitHub. Perhaps GitHub does not show the newlines at the end of files in its code preview?

2022-08-05 19:58 UTC, zachmmeyer commented
> @zachmmeyer I will resolve the merge conflicts right now. 
> 
> Regarding the newlines at the end of the files, my local repo shows newlines at all the files I made commits to. I am not sure why the newlines do not show up on GitHub. Perhaps GitHub does not show the newlines at the end of files in its code preview?

That's OK, do not worry about the newlines then.

2022-08-05 20:26 UTC, c-yip commented
@zachmmeyer I resolved the merge conflicts. Please let me know if there are any other issues.

2022-08-05 20:34 UTC, zachmmeyer approved these changes
Looks good to me! Thank you!

2022-08-05 20:34 UTC, merged