Fix some minor grammatical errors
TheOdinProject/curriculum pull request #24413
Opened 2022-07-12 18:50 UTC by imReset

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-07-17 20:17 UTC, fortypercenttitanium requested changes
Just a few changes and we'll get it merged! Thanks!

2022-07-17 20:17 UTC, fortypercenttitanium commented on html_css/intermediate_html/Introduction.md
> +Our foundations lessons, by design, only scratched the surface of what's possible. We wanted to give you all of the bare necessities for getting started, so you could move on and be somewhat producti
This comma is unnecessary

2022-07-17 20:17 UTC, fortypercenttitanium commented on html_css/intermediate_html/Introduction.md
> +You have probably realized by now that we mentioned many more HTML elements in our foundation's content. Throughout this course, we’ll hit the rest of the important elements, such as forms and tables
This changes the meaning of the sentence. We're saying there are more elements that we *haven't* covered yet. Your sentence implies that we covered more elements in the foundations lesson, which is not the case.

2022-08-03 00:41 UTC, chayboats commented on html_css/intermediate_html/Introduction.md
> +You have probably realized by now that we mentioned many more HTML elements in our foundation's content. Throughout this course, we’ll hit the rest of the important elements, such as forms and tables
```suggestion
You have probably realized by now that we mentioned many more HTML elements in our foundation's content. Throughout this course, we’ll cover the rest of the important elements, such as forms and tables.
```

2022-08-03 04:53 UTC, closed without merging