React Router Lesson: Add small blurp/section on why use router #24210
TheOdinProject/curriculum pull request #24424
Opened 2022-07-16 18:58 UTC by Lakshmikant-2001

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #24210 

**2. This PR:**
Satisfies the Acceptance Criteria, 
- [x] Add a section called "Client-side Routing" right after Learning Outcomes
- [x] In the new section, discuss client-side routing and why it's useful. Then, briefly touch upon how React Router is handy for routing in React applications.
- [x] Rename the "React Router" section to "How To Use React Router"

2022-07-24 06:54 UTC, 01zulfi requested changes
Great work, especially with including learning outcomes and knowledge checks :fire: 

I've made some minor requested changes below.

2022-07-24 06:54 UTC, 01zulfi commented on javascript/react_js/router.md
> +### Client-side Routing
As per our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md) we want our headings to be [Wikipedia Style Title Case](https://titlecaseconverter.com/rules/#WP):
```suggestion
### Client-Side Routing
```

2022-07-24 06:54 UTC, 01zulfi commented on javascript/react_js/router.md
> +React router is the standard routing library for React Applications. By using React routers, we can specify which component can be rendered based on the route. From version 4, react router uses dynam
I think we could add a reference link for dynamic routes:
```suggestion
React router is the standard routing library for React Applications. By using React routers, we can specify which component can be rendered based on the route. From version 4, react router uses [dynamic routes](https://v5.reactrouter.com/web/guides/philosophy/dynamic-routing) (routing that takes place as your app is rendering).
```

2022-07-24 06:54 UTC, 01zulfi commented on javascript/react_js/router.md
> +### How to use React Router
See suggestion about lesson titles above.

```suggestion
### How To Use React Router
```

2022-07-24 15:13 UTC, Lakshmikant-2001 commented
@01zulfi Resolved all the comments.

2022-07-25 03:53 UTC, 01zulfi approved these changes

2022-07-25 03:53 UTC, merged