Classes lesson : Add one knowledge check
TheOdinProject/curriculum pull request #24445
Opened 2022-07-23 15:24 UTC by Tribhuwan-Joshi

Knowledge check about static variables and properties  in class

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-07-24 06:05 UTC, 01zulfi commented
- Putting this on hold until https://github.com/TheOdinProject/curriculum/pull/24432 is reviewed.

2022-08-24 10:53 UTC, Tribhuwan-Joshi commented
@01zulfi  can u review this pr now

2022-09-03 08:43 UTC, 01zulfi requested changes
The change looks good, but unfortunately there's a merge conflict that needs to be fixed.

2022-09-07 07:51 UTC, 01zulfi requested changes

2022-09-07 07:51 UTC, 01zulfi commented on javascript/organizing_your_javascript_code/classes.md
> +* <a class="knowledge-check-link" href="https://rajaraodv.medium.com/is-class-in-es6-the-new-bad-part-6c4e6fe1ee65">Briefly talk about the conflict in JS with functional programming and classes.</a>
These two knowledge checks were removed in another PR https://github.com/TheOdinProject/curriculum/pull/24432/files. I don't think we need to add them back.

2022-09-07 09:27 UTC, 01zulfi approved these changes
Thanks for making this change and resolving the merge conflicts!

2022-09-07 09:27 UTC, merged