Convert CS lessons to be Javascript specific
TheOdinProject/curriculum pull request #24466
Opened 2022-07-27 14:22 UTC by CouchofTomato

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**
Javascript does not currently have a CS course

**2. This PR:**

* Copies the Ruby CS course files into the Javascript directory and then edits references to anything Ruby specific to be Javascript specific.

**3. Additional Information:**

2022-07-27 16:09 UTC, 01zulfi requested changes
This is great 🔥 

I've left a review below, mostly it's just convention shift from Ruby to JS 😆 

Additionally, where do you envision this section going in the JavaScript course?

2022-07-27 16:09 UTC, 01zulfi commented on javascript/computer_science/project_binary_search_trees.md
> +1. Write a `level_order` function which accepts another function as a parameter. `level_order` should traverse the tree in breadth-first level order and yield each node to the provided function. This
Yield each node to the provided function sounds weird for JS. Wording suggestion:
```suggestion
1. Write a `levelOrder` function which accepts another function as a parameter. `levelOrder` should traverse the tree in breadth-first level order and provide each node as the argument to the provided function. This function can be implemented using either iteration or recursion (try implementing both!). The method should return an array of values if no function is given. **Tip:** You will want to use an array acting as a queue to keep track of all the child nodes that you have yet to traverse and to add new ones to the list (as you saw in the [video](https://www.youtube.com/watch?v=86g8jAQug04)).
```

2022-07-27 16:09 UTC, 01zulfi commented on javascript/computer_science/project_knights_travails.md
> +  > knight_moves([3,3],[4,3])
```suggestion
  > knightMoves([3,3],[4,3])
```

2022-08-01 13:50 UTC, CouchofTomato commented on javascript/computer_science/recursive_methods.md
> +  1. Solve each of the questions from this [Code Quiz](http://www.codequizzes.com/computer-science/beginner/recursion) on Recursion. You are not expected to answer them from memory at this point.
What do you think about https://www.codingame.com/playgrounds/5422/js-interview-prep-recursion as an alternative

2022-08-03 11:45 UTC, KevinMulhern approved these changes
Looks great to me mate @CouchofTomato 👑

2022-08-03 14:57 UTC, 01zulfi commented on javascript/computer_science/recursive_methods.md
> +  1. Solve each of the questions from this [Code Quiz](http://www.codequizzes.com/computer-science/beginner/recursion) on Recursion. You are not expected to answer them from memory at this point.
Some of the problems seem to be a little on the tough side, but I like it. 🚀

2022-08-03 15:01 UTC, 01zulfi approved these changes
Approved, although minor nitpicks 🚀

2022-08-03 19:10 UTC, merged