JavaScript: Binary Search Tree Project: add `prettyPrint()` function translated from Ruby's BST project
TheOdinProject/curriculum pull request #24540
Opened 2022-08-12 22:58 UTC by JoshDevHub

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

 This section was recently translated from the computer science section in the ruby path. For the binary search tree project, an important component to the assignment was lost in the translation: the `#pretty_print` method. You can see it at the bottom of the [assignment in the ruby section here](https://www.theodinproject.com/lessons/ruby-binary-search-trees). This method allows learners to print their tree in a human reader friendly way, which is especially valuable given how this section comes prior to testing -- when learners will only be able to test by looking at console output. Here are two terminal screenshot comparisons to show how much more readable this output is with `prettyPrint()`:
 
 **Using `console.dir` to print a nested object. The entire tree given at the end of the assignment doesn't even fit in my full terminal window ->**
 ![Screenshot from 2022-08-12 16-38-23](https://user-images.githubusercontent.com/88392688/184453335-49158762-3ef7-4aa1-ae48-ebf1599c925d.png)
 
 **Using this `prettyPrint()` function on a tree of equal size ->**
![Screenshot from 2022-08-12 16-39-52](https://user-images.githubusercontent.com/88392688/184453451-ddc430c1-d48c-4c14-954c-d2a09ce3c80e.png)

**2. This PR:**

 * Translates the `prettyPrint()` function present in the ruby course over to JavaScript. I've verified it works in my [own binary search tree project in JS](https://github.com/JoshDevHub/JavaScript-Binary-Search-Tree/blob/main/binary-tree.js#L129-L137).

**3. Additional Information:**

I've positioned this at the very end of the exercise, just like it is in the Ruby course. Glad to make a further commit if it's considered better elsewhere on the page.

2022-08-15 07:41 UTC, 01zulfi requested changes
This is an amazing and a valuable addition :fire: 

As for the placement, I personally feel the pretty print function should be placed further up in the lesson for more visibility (even in the Ruby version of the lesson). What do you think?

2022-08-15 07:41 UTC, 01zulfi commented on javascript/computer_science/project_binary_search_trees.md
> +**Tip:** If you would like to visualize your binary search tree, here is a `prettyPrint()` function that will `console.log` your tree in a structured format. This function will expect to receive the
Wording suggestion: Just being extra specific on how to pass in the root.

```suggestion
**Tip:** If you would like to visualize your binary search tree, here is a `prettyPrint()` function that will `console.log` your tree in a structured format. This function will expect to receive the root of your tree as the value for the `node` parameter.
```

2022-08-17 20:58 UTC, JoshDevHub commented
@01zulfi I've committed that change of phrase for the parameter. I also think it's probably a good idea to move it higher on the page. I seem to remember at least one time where a learner in the ruby path made it through most of the project before even noticing it existed haha.

Could it maybe fit in after the `buildTree()` function? Learners are guaranteed to see it, and they'll be able to use it straight away. Let me know what you think or if you have some other idea for where it could go. I'll gladly commit those changes for both courses :+1:

2022-08-18 07:08 UTC, 01zulfi commented
> I seem to remember at least one time where a learner in the ruby path made it through most of the project before even noticing it existed haha.

Oh wow, I can definitely see that happening :laughing: 


Yes, right after `buildTree` sounds good.

2022-08-19 16:14 UTC, JoshDevHub commented
@01zulfi Alright I moved the function up after `buildTree` for both paths. Sorry about the messy diff, I had to change the spacing after the numbers in the list to make sure the codeblock doesn't interrupt the ordering of the list. The [style guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#nested-list-spacing) seems to recommend two spaces after numbers in an ordered list anyway.

2022-08-22 05:03 UTC, 01zulfi approved these changes
This looks great :fire: Thanks for your work on this! :rocket:

2022-08-22 05:03 UTC, merged