Update fundamentals-3.md
TheOdinProject/curriculum pull request #24568
Opened 2022-08-22 13:50 UTC by shreedhar37

Added one more video reference for call stack.

Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-09-26 15:16 UTC, linkonsat commented
Thanks for doing this @shreedhar37. I think the video can be useful but would prefer to see it in the additional resources section as reading articles is preferred as the initial resources. If you could move it to the additional resources I would be more than happy to merge it.

2022-10-18 14:15 UTC, zachmmeyer requested changes

2022-10-18 14:15 UTC, zachmmeyer commented on foundations/javascript_basics/fundamentals-3.md
> +- [Video on How JavaScript Code is executed?](https://youtu.be/iLWTnMzWtj4)
```suggestion
- [How JavaScript Code is executed?](https://youtu.be/iLWTnMzWtj4)
```

2022-10-18 14:16 UTC, zachmmeyer approved these changes

2022-10-18 14:16 UTC, merged