Ruby on Rails: Stimulus: Fix a faulty example
TheOdinProject/curriculum pull request #24620
Opened 2022-09-05 21:33 UTC by RolandStuder

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

The example code for targets has several errors, switching target, having invalid closing input tags, it just plain won't work, when people try to copy it.

**2. This PR:**

Puts correct code, that can be put into your application and will work.

**3. Additional Information:**

example of a confused person: https://discord.com/channels/505093832157691914/514204607770001411/1015910188190011402 they were not the first person to be confused by this.

2022-09-07 07:10 UTC, KevinMulhern requested changes

2022-09-07 07:10 UTC, KevinMulhern commented on ruby_on_rails/rails_sprinkles/stimulus_js.md
> +        this.outputTarget.innerHTML = "Hello " + this.nameTarget.value + "!"
Can we use interpolation here instead please?
```suggestion
        this.outputTarget.innerHTML = `Hello ${this.nameTarget.value}!`
```

2022-09-28 20:52 UTC, RolandStuder commented
@KevinMulhern committed your suggestion, thx!

2022-09-30 11:38 UTC, KevinMulhern approved these changes
Nice one, thanks for taking the time to do this @RolandStuder 💪

2022-09-30 11:39 UTC, merged