Introduction to Grid lesson: Fix grammer mistake in subheading
TheOdinProject/curriculum pull request #24715
Opened 2022-10-01 10:45 UTC by arpit-srivastava-one

Fixed a small grammer mistake in one of the subheadings -

### Earlier
```
What the Grid?
```

### Updated
```
What is Grid?
```

2022-10-01 11:34 UTC, DanatGutema reviewed
Although Grid is a newer module to CSS, this layout tool has been long in development

2022-10-02 06:00 UTC, arpit-srivastava-one commented
> Although Grid is a newer module to CSS, this layout tool has been long in development

Thanks for pointing this out. I've did the change and made the commit.

2022-10-03 14:48 UTC, zachmmeyer requested changes
Hello! Thanks for offering to contribute to the curriculum! I've got some changes I'd like to request to your PR before we merge it.

2022-10-03 14:48 UTC, zachmmeyer commented on intermediate_html_css/grid/introduction_to_grid.md
> +Although Grid is a newer module to CSS, this layout tool has been long in development. Fun fact, CSS co-creator Dr. Bert Bos (no relation to Wes Bos) started working on this layout model in 1996. The
```suggestion
Although Grid is a newer module to CSS, this layout tool has long been in development. Fun fact, CSS co-creator Dr. Bert Bos (no relation to Wes Bos) started working on this layout model in 1996. The idea was inspired by the use of grid-like layouts in other forms of media like newspapers and magazines. After years of thought demonstrations and development, CSS Grid was finally introduced to all major browsers in 2017.
```

2022-10-03 14:48 UTC, zachmmeyer commented on intermediate_html_css/grid/introduction_to_grid.md
> +### What is Grid?
```suggestion
### What's the Grid?
```

2022-10-05 10:40 UTC, DanatGutema reviewed
Which CSS layout module would you use to easily make equal sized items in a container
should replaced by
Which CSS layout module used to easily make equal sized items in a container

2022-10-05 12:19 UTC, arpit-srivastava-one commented on intermediate_html_css/grid/introduction_to_grid.md
> +### What is Grid?
Isn't ```What's the Grid?``` grammatically incorrect?

2022-10-06 04:26 UTC, zachmmeyer commented on intermediate_html_css/grid/introduction_to_grid.md
> +### What is Grid?
Oh yeah you're right, my bad.

2022-10-06 04:27 UTC, zachmmeyer approved these changes
There we go. Thanks for contributing, your patience and dealing with me!

2022-10-06 04:27 UTC, merged