JavaScript course conclusion: Clarify conclusion text, add context about other lessons closes #24031
TheOdinProject/curriculum pull request #24790
Opened 2022-10-11 01:40 UTC by Pete-Fowler

Make clear the context of the overall paths and that this is not the final module

Complete the following REQUIRED checkboxes:

-   [ X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ X] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ X] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #24031

**2. This PR:**

**3. Additional Information:**

2022-10-16 19:24 UTC, wise-king-sullyman reviewed
Thanks for putting this change together!

I know it wasn't in the original issue description, but after reviewing this I feel like this whole lesson could use some significant editing since (for example) people reading this content haven't reached the Node course yet and it's mentioned in the second paragraph, and the whole tone of it feels like it's closing out the path IMO, which as you know isn't true on either path.

Would you be willing to take on a more significant rework? If not that's totally fine.

2022-10-16 20:16 UTC, Pete-Fowler commented
Sure, I'll take another look at the whole thing and add a commit by the end of the day.

2022-10-16 21:37 UTC, Pete-Fowler commented
Changes added. Let me know if you have any edits or suggestions. Thanks.

2022-10-17 22:05 UTC, wise-king-sullyman requested changes
Thanks for doing this so quickly, mostly looks great! Two small notes:

2022-10-17 22:05 UTC, wise-king-sullyman commented on javascript/finishing_up_with_javascript/conclusion.md
> +Whichever path you're on, BUILD! Build and build and build and build (see a theme in this curriculum yet?). Use what you've learned to create great projects. Focusing on creating interesting software
I think we could maybe cut all of this, and add some encouragement for people to explore and learn more "on their own" to the part above that's speaking directly towards Ruby path people, since people on the full stack JS path still have quite a few TOP projects to do before we really cut them loose so to speak. What do you think?

2022-10-17 22:05 UTC, wise-king-sullyman commented on javascript/finishing_up_with_javascript/conclusion.md
> +1. Before you move on to the next section, we would like your feedback [here](https://docs.google.com/forms/d/e/1FAIpQLSeHcp46iWF5D7V7wPPHDeIHK0q5Nu0zXHZi46pP7ExVjULvZA/viewform?usp=sf_link). Getting
I know the link text here was already bad but if you'd be willing to fix it while we're doing this major rework of the content anyways I would appreciate that. Check out [this page from WebAim](https://webaim.org/techniques/hypertext/#screen_readers) for some more information about what I mean fi you're not familiar.

2022-10-17 22:08 UTC, wise-king-sullyman commented
Also your point about the different order of the paths is noted and something we will discuss on the maintainer team, though I believe that it's intentional. For people doing the full stack JS path they (of course) need that fuller understanding of JS before trying to add in the complexity of backend development, vs people doing the Rails path first learn Ruby and then learn backend development in a similar manner.

2022-10-18 01:30 UTC, Pete-Fowler commented
Some more changes are added. Is this helpful? To me, it would make sense to have both paths do the JavaScript module first, since it is in both, and then move on to back end. This of course could be debated and is subject to opinion.

2022-10-28 00:11 UTC, wise-king-sullyman approved these changes
Looks great, thanks!

2022-10-28 00:11 UTC, merged