React section: Adds Class-based components lesson
TheOdinProject/curriculum pull request #24805
Opened 2022-10-14 07:12 UTC by Lofty-Brambles

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [x] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Adds the lesson based on [top-meta #230](https://github.com/TheOdinProject/top-meta/issues/230)

**2. This PR:**

- Adds a class-based components lesson.

**3. Additional Information:**

N/A. Waiting on feedback.

2022-10-30 07:56 UTC, 01zulfi requested changes
Amazing work you've put in here 🔥 🔥 🔥 

Left some comments below.

2022-10-30 07:56 UTC, 01zulfi commented on react/class_components/class_based_components.md
> +~~~
We should remove comments in this code example. By this point, learners should be well versed in functional components and how state works.

2022-10-30 07:56 UTC, 01zulfi commented on react/class_components/class_based_components.md
> +That was a solid chunk of code. Take a while, sip some water and read it a couple of times.
<details>
<summary></summary>

![image](https://media4.giphy.com/media/sIDxMqTWbVxOM6gRPQ/giphy.gif?cid=ecf05e47u05ku7ojdqsilc04d7zsi957lv5kikj598sxswbh&rid=giphy.gif&ct=g)

2022-10-30 07:56 UTC, 01zulfi commented on react/class_components/class_based_components.md
> +In your previous lessons, you have already been introduced to functional components, and the basic patterns in which components get written now a days. However, React components did not look this way
```suggestion
In your previous lessons, you have already been introduced to functional components, and the basic patterns in which components get written now a days. However, React components did not look this way when React was introduced.
```

2022-10-30 07:56 UTC, 01zulfi commented on react/class_components/class_based_components.md
> +In your career, chances are, you will be dealing with legacy code, so there will be days where you would be dealing with class components. To meet this issue, we take a peek into the works and intric
Wording suggestion:

```suggestion
In your career, chances are, you will be dealing with legacy code, so there will be days where you would be dealing with class components. Let's peek into the intricacies of a class-based component, and how they work.
```

2022-10-30 07:56 UTC, 01zulfi commented on react/class_components/class_based_components.md
> +- Highlights the uses of `this` in class components.
We can simplify the Lesson Overview:

```suggestion

- Learn the structure of a class component and how they're written.
- How to use props and state in class components.
- Highlight the uses of `this` in class components.
```

2022-10-30 07:56 UTC, 01zulfi commented on react/class_components/class_based_components.md
> +3.  Implement an edit button for each task. It should replace the todo with an input field, and change the button itself to 'Resubmit', so the edits can be saved. This is a comparatively harder task,
I like the assignment section. Hands on practice is invaluable!

2022-11-04 17:05 UTC, 01zulfi requested changes
I'll take a look at the code examples in a bit more detail once I get a chance to review the codesandbox PR (promise I'll get to it soon 😄). Left a couple of comments below, the lesson is looking solid otherwise.

2022-11-08 07:37 UTC, Lofty-Brambles commented on react/class_components/class_based_components.md
> +### The What's And Why's
Grammar gosh.. [Here's what I found](https://english.stackexchange.com/questions/146348/the-whys-and-the-hows), so I'm simply dropping them. Thanks for that, learnt something today-

2022-11-08 07:41 UTC, Lofty-Brambles commented
Addressed the two issues @01zulfi

2022-11-14 12:50 UTC, 01zulfi requested changes

2022-11-14 12:50 UTC, 01zulfi commented on react/class_components/class_based_components.md
> +></iframe>
I've created a sandbox on TOP's account, we should change to that link instead: 
```
<iframe src="https://codesandbox.io/embed/github/TheOdinProject/react-examples/tree/main/class-component-example?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="react-example"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```

2022-12-04 17:56 UTC, Lofty-Brambles commented
@01zulfi - It should be added! Could you please ping me when you add another comment next time?

2022-12-05 12:14 UTC, 01zulfi approved these changes

2022-12-05 12:15 UTC, merged