Foundations, Fundamentals II: Improve grammar
TheOdinProject/curriculum pull request #24810
Opened 2022-10-15 14:05 UTC by MRZHD1

Made it clearer that Regular Expressions = regex, as it wasn't explicitly stated and might not be immediately obvious + fixed the sentence structure a bit. The content is still identical and portraying the same meaning.

Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [ ] I have previewed all lesson files included in this PR with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure the Markdown content is formatted correctly
-   [ ] I have ensured all lesson files included in this PR follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-10-15 22:10 UTC, xandora requested changes
I'm not really a fan of either sentence to be honest... Do you think instead of modifying the current wording, you could reword the whole thing to make it clearer?

2022-10-16 06:29 UTC, MRZHD1 commented
I reworded it and added a stack overflow post. I'm not sure if I formatted it correctly 😓

2022-10-18 23:23 UTC, xandora requested changes
Just a couple changes to make, then I think we're good to go.

2022-11-01 11:54 UTC, MRZHD1 reviewed
I think I forgot to finish the review 🤔 but I implemented the changes.

2022-11-01 20:41 UTC, merged