Objects and Object Constructors: Update lesson on Prototype and Prototypal Inheritance
TheOdinProject/curriculum pull request #24941
Opened 2022-12-02 21:35 UTC by anupamvamsi

## Because
The primary aim of this PR was to update the lesson's Recommended Method for Prototypal Inheritance content from using `Object.create()` to the `Object.setPrototypeOf()` method.

However I realized that the lesson also could better explain the `prototype` function property vs. the `__proto__` / `[[Prototype]]` property and prototypal inheritance through TOP's curriculum directly. Personally to me as a learner, the lesson was confusing and I had to refer to quite a few resources to understand it.

It is a complete update to #24560 and its corresponding PRs.

## This PR
1. Explains the concept of the `prototype` and Prototypal Inheritance.
2. Updates the recommended way of performing prototypal inheritance to using `Object.setPrototypeOf()` rather than using `Object.create()`.

## Issue
Closes #24560, #24563, #24782.

## Additional Information
* This PR has been made as per suggestions on the conversation on #24560.
* Suggestions-Bugs Forum discussion on [Discord](https://discord.com/channels/505093832157691914/1010249197544538112)
* Discussion on mdn/content: https://github.com/mdn/content/pull/18880
* PR closing the above discussion on mdn/content: https://github.com/mdn/content/pull/20693

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2022-12-02 21:38 UTC, anupamvamsi commented
Hi, @wise-king-sullyman! I've made a PR for the complete set of changes as you suggested. Please take a look, thanks! 

I'll be closing the other PRs I've created before.

2023-03-27 01:33 UTC, fortypercenttitanium requested changes
Thank you for your patience on this one. We had a lot of internal discussion about this and have decided that this material is a good addition to the curriculum, however, we'd like to graciously ask for a few modifications:

- Prefer using `Object.getPrototypeOf` in lieu of __proto__ as the primary method for getting an object's prototype. Since [__proto__ is deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto), we don't want to be using it as a tool for learning modern Javascript.
- A couple of style guide conformity changes notated on the appropriate lines
- Please use the aside section on current lines 212-223 to make mention of the deprecated methods of viewing prototype info.
- Please make mention of the `Object.hasOwnProperty` method and how it relates to the prototype chain details you are explaining at that point.

2023-03-27 01:33 UTC, fortypercenttitanium commented on javascript/organizing_your_javascript_code/objects_and_object_constructors.md
> +3. Well, then, is it part of `Player.prototype.__proto__` (=== `Object.prototype`)? Yes, `.valueOf` is defined on `Object.prototype`!
Can we use this aside to also cover how `hasOwnProperty` works as well? It's in a very similar vein and is a method that is likely to be used or encountered.

2023-03-27 01:33 UTC, fortypercenttitanium commented on javascript/organizing_your_javascript_code/objects_and_object_constructors.md
> +Now, how do you utilise Prototypal Inheritance? What do you need to do to use it? Just as we use `Object.getPrototypeOf()` to 'get' or view the `prototype` of an object, we can use `Object.setPrototy
```suggestion
Now, how do you utilize Prototypal Inheritance? What do you need to do to use it? Just as we use `Object.getPrototypeOf()` to 'get' or view the `prototype` of an object, we can use `Object.setPrototypeOf()` to 'set' or mutate it. Let's see how it works by adding a `Person` Object Constructor to the `Player` example, and making `Player` inherit from `Person`!
```

2023-03-27 01:33 UTC, fortypercenttitanium commented on javascript/organizing_your_javascript_code/objects_and_object_constructors.md
> +   3b. So, any properties or methods defined on `Player.prototype` will be available to the created `Player` objects!
Please refer to the style guide on how we number our markdown [ordered lists (lazy numbering) ](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lazy-numbering)

2023-03-27 01:33 UTC, fortypercenttitanium commented on javascript/organizing_your_javascript_code/objects_and_object_constructors.md
> +This explanation about the `prototype` might have been a lot, so remember to take a breather before moving on!
Use this section to make a note about `__proto__` and `[[Prototype]]`, mention how you might see them in legacy code, etc... See the bigger comment on the review to understand why we prefer not teaching to use `__proto__` in lieu of `Object.getPrototypeOf()`

2023-04-16 15:35 UTC, anupamvamsi commented
Hi @fortypercenttitanium, thanks for your inputs! I understand that this is a topic of debate and it required some time from your side to be spent on it to decide if it is good for the lesson. I've made the changes you've suggested. Apologies that it took me some time to act on these suggestions. Hopefully the changes should be good to go!

2023-04-19 16:26 UTC, fortypercenttitanium approved these changes
Excellent work @anupamvamsi .

2023-04-19 16:28 UTC, merged