Update git_basics.md
TheOdinProject/curriculum pull request #25061
Opened 2023-01-29 17:19 UTC by stirfry93

In line 33, I changed "green" to "blue" because I noticed the "Create repository" button on GitHub is now blue. I suppose this change would require the following screenshot to also be updated, however.

## Because

## This PR

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-02-05 13:37 UTC, thatblindgeye requested changes
The button is still green to me (using dark mode on GitHub, in case that might be a factor). The RGB of the background of that button is `35, 134, 54`.

The color of the button really isn't important here, though. We shouldn't be instructing what to click based on color, especially since we already state the button content ("Create repository"). So let's just remove the color from the lesson like below.

2023-02-05 13:37 UTC, thatblindgeye commented on git/foundations_git/git_basics.md
> +3.  Give your repository the name "git_test" in the repository name input field. Check "Add a README file". And then create the repository by clicking the blue "Create repository" button at the botto
```suggestion
3.  Give your repository the name "git_test" in the repository name input field. Check "Add a README file". And then create the repository by clicking the "Create repository" button at the bottom of the page.
```

2023-02-11 05:19 UTC, xandora commented
@stirfry93 There are some requested changes you can review and commit that are still waiting. Do you want to handle them? If not, we'll push it through quickly and get this PR closed out. :)

2023-04-08 20:12 UTC, thatblindgeye approved these changes

2023-04-08 20:12 UTC, merged