Webpack: additional resources
TheOdinProject/curriculum pull request #25103
Opened 2023-02-14 21:31 UTC by Amer-tech

## Because
This PR suggests adding an additional resource to this lesson.

## This PR
- The suggested additional resource: https://www.youtube.com/watch?v=5IG4UmULyoA

## Pull Request Requirements
[x] I have thoroughly read and understand The Odin Project Contributing Guide
[x] The title of this PR follows the location of change: brief description of change format, e.g. Intro to HTML and CSS lesson: Fix link text
[x] The Because section summarizes the reason for this PR
[x]  The This PR section has a bullet point list describing the changes in this PR
[] If this PR addresses an open issue, it is linked in the Issue section
[] If any lesson files are included in this PR, they have been previewed with the Markdown preview tool to ensure it is formatted correctly
[] If any lesson files are included in this PR, they follow the Layout Style Guide

2023-02-18 07:30 UTC, KevinMulhern commented
Can you explain the value in adding this new resource please @Amer-Alic? 5 assignments is leaning on the too many side of things.

2023-02-19 08:25 UTC, Amer-Alic commented
> Can you explain the value in adding this new resource please @Amer-Alic? 5 assignments is leaning on the too many side of things.

If you watch the video, you will realise that with this video you go through almost everything in those 4 large blog posts (I was considering even to propose removing one of them, but tought it was too much). So yea, in nutshell I think this video is great foundation for this topic and other posts would be to go more in depths.

2023-02-20 17:47 UTC, KevinMulhern requested changes
Thanks for the explanation @tansaku. Please fill in the PR because prompt with that kind of thing in the future, letting us know the intention and why behind a PR helps us, help you with reviewing.

The video looks good for an overview and think it would be helpful too. I just have a some suggestions for wording in the assignment.

2023-02-20 17:47 UTC, KevinMulhern commented on javascript/organizing_your_javascript_code/webpack.md
> +1. Go through [this tutorial](https://www.youtube.com/watch?v=5IG4UmULyoA). An excellent, concise tutorial that explains the most important things. Follow with an example in the video!
```suggestion
1. Watch and follow along with [Fireship's Module Bundlers Explained video](https://www.youtube.com/watch?v=5IG4UmULyoA) to get a great overview and some hands on experience with webpack.
```

2023-02-22 13:41 UTC, KevinMulhern approved these changes
Thanks @Amer-Alic

2023-02-22 13:41 UTC, merged