add : computer basics aditonal video added
TheOdinProject/curriculum pull request #25156
Opened 2023-02-28 18:03 UTC by sumitshinde-84

## Because

i have added nice animated  computer basics video of freecodecamp (duration 55 min)
check it https://youtu.be/y2kg3MOk1sY  

## This PR

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-03-05 00:45 UTC, MIfoodie commented
This PR does not follow the second point of *Pull Request Requirements*. Please format your title correctly.

2023-03-05 14:01 UTC, sumitshinde-84 commented
@CouchofTomato request for review .

2023-03-06 14:33 UTC, 01zulfi requested changes

2023-03-06 14:41 UTC, sumitshinde-84 commented
sir i have made changes as you suggest me 
thank you so much for your precious suggestion

2023-03-06 14:49 UTC, 01zulfi approved these changes

2023-03-06 14:49 UTC, merged