added aditional content to foundation/Choose Your Path Forward
TheOdinProject/curriculum pull request #25178
Opened 2023-03-07 07:46 UTC by sumitshinde-84

## Because

i have added additional content to foundation/Choose Your Path Forward,
article which i have added  (https://cloudinfrastructureservices.co.uk/ruby-on-rails-vs-javascript-whats-the-difference/)

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-03-07 07:47 UTC, sumitshinde-84 commented
request for review @01zulfi

2023-03-07 14:08 UTC, CouchofTomato requested changes

2023-03-07 14:08 UTC, CouchofTomato commented on foundations/tying_it_all_together/conclusion.md
> +* If you are still confuse, Checkout this article to get more facts, prons and cons about both languages [Cloud-Infrastucter- service article](https://cloudinfrastructureservices.co.uk/ruby-on-rails-
Can we correct the typos here please.

 If you are still confused, Checkout this article to get more facts, pros and cons about both languages [Ruby on Rails vs Javascript](https://cloudinfrastructureservices.co.uk/ruby-on-rails-vs-javascript-whats-the-difference/).

2023-03-07 15:04 UTC, CouchofTomato reviewed
Thanks @sumitshinde-84 

A couple of changes weren't actioned and I noticed a couple more. Hopefully it's clearer now what needs to change.

2023-03-07 15:04 UTC, CouchofTomato commented on foundations/tying_it_all_together/conclusion.md
> +* If you are still confuse, Checkout this article to get more facts, prons and cons about both languages [Ruby on Rails vs Javasctipt.](https://cloudinfrastructureservices.co.uk/ruby-on-rails-vs-java
```suggestion
* If you are still confused, Check out this article to get more facts, pros and cons about both languages [Ruby on Rails vs Javasctipt.](https://cloudinfrastructureservices.co.uk/ruby-on-rails-vs-javascript-whats-the-difference/).
```

2023-03-07 15:42 UTC, sumitshinde-84 commented
@CouchofTomato  yes sir i have made changes , as you suggest me .

2023-03-07 15:44 UTC, CouchofTomato requested changes
Hey @sumitshinde-84 

I'm really sorry to keep throwing this back at you. These are the last changes 🙏

2023-03-07 15:44 UTC, CouchofTomato commented on foundations/installations/computer_basics.md
> +
We don't need this extra space here.

2023-03-07 15:44 UTC, CouchofTomato commented on foundations/installations/computer_basics.md
>  * Checkout [GCF's page on "What are accessibility features"](https://edu.gcfglobal.org/en/computerbasics/using-accessibility-features/1/) to learn how you can leverage these features to use your comp
```suggestion
- Checkout [GCF's page on "What are accessibility features"](https://edu.gcfglobal.org/en/computerbasics/using-accessibility-features/1/) to learn how you can leverage these features to use your computer efficiently.
```

2023-03-07 15:44 UTC, CouchofTomato commented on foundations/installations/computer_basics.md
> +* If you feel like spending more time learning about this topic, check out [FreeCodeCamp's excellent course on computer basics](https://youtu.be/y2kg3MOk1sY)
```suggestion
- If you feel like spending more time learning about this topic, check out [FreeCodeCamp's excellent course on computer basics](https://youtu.be/y2kg3MOk1sY)
```

2023-03-07 15:55 UTC, CouchofTomato requested changes
Hey @sumitshinde-84 

I noticed a typo which was my fault.

However I need that extra space on line 43 of computer_basics to be removed please as well.

2023-03-07 15:55 UTC, CouchofTomato commented on foundations/tying_it_all_together/conclusion.md
> +- If you are still confused, Check out this article to get more facts, pros and cons about both languages [Ruby on Rails vs Javasctipt.](https://cloudinfrastructureservices.co.uk/ruby-on-rails-vs-jav
```suggestion
- If you are still confused, Check out this article to get more facts, pros and cons about both languages [Ruby on Rails vs Javascript.](https://cloudinfrastructureservices.co.uk/ruby-on-rails-vs-javascript-whats-the-difference/).
```

2023-03-07 15:55 UTC, CouchofTomato commented on foundations/installations/computer_basics.md
> +
We still need to remove this extra space.

2023-03-07 17:02 UTC, sumitshinde-84 commented
Hello  sir ,
I have made changes as you suggest me  if everything is ok then please merge it

2023-03-08 10:26 UTC, CouchofTomato approved these changes

2023-03-08 10:28 UTC, merged

2023-03-08 13:43 UTC, sumitshinde-84 commented
@CouchofTomato  , 
Hii Austin sir,
I am sumit from India and I have learned frontend development from odin,
It was amazing experience learning through Odin but now I wanna be member of odin organisations , being part of odin project I will learn lot of precious thing and also I will get opportunity to contribute in my School of programming .