Flexbox Alignment: Update resources
TheOdinProject/curriculum pull request #25494
Opened 2023-05-19 03:03 UTC by i4pg

## Because

This comprehensive MDN article provides a solid foundation for understanding the basics of CSS Flex-box. It extensively covers the concept of axes while also briefly introducing alignment. To optimize the learning flow, I have moved this section to the previous lesson on flex-box axes, where students will receive a brief introduction to alignment. Additionally, in order to avoid duplication, I have removed the Kevin Powell video from this lesson since it is already mentioned in the Growing and Shrinking lesson. Instead, I have included the cheat sheet from the previous lesson in this current lesson.

## This PR

- Move MDN resource to the previous lesson.
- Remove one duplicate resource
- Move Flex-box cheat sheet from the previous lesson to this lesson

## Issue

## Additional Information

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-05-20 00:38 UTC, rlmoser99 commented
Closing this one as well, since these associated changes are not being merged.

2023-05-20 01:09 UTC, i4pg commented
> Closing this one as well, since these associated changes are not being merged.

This PR accomplishes three tasks, two of which are related to another PR.

2023-05-20 03:14 UTC, rlmoser99 requested changes
I apologize for closing this PR, since you also wanted to remove duplicate additional resource.

2023-05-21 21:38 UTC, rlmoser99 approved these changes

2023-05-21 21:39 UTC, merged