[react/states_and_effects] React revamp - Project Shopping Cart
TheOdinProject/curriculum pull request #25506
Opened 2023-05-21 10:06 UTC by Lofty-Brambles

## Because

This adds a lesson for the react section, updating the old one, according to necessary specs.

## This PR

N/A

## Issue

Closes https://github.com/TheOdinProject/top-meta/issues/266

## Additional Information

N/A

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] ~~The `Because` section summarizes the reason for this PR~~
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-05-26 13:43 UTC, 01zulfi requested changes
The PR title made me do a double take, fixed that.

Just a couple of tiny comments below ⬇️

2023-05-26 13:43 UTC, 01zulfi commented on react/states_and_effects/project_memory_card.md
> +1.  Create a new React project with `vite`.
I'm not sure if we need to add this assignment item. "Create a new React project with XYZ tool" isn't future proof.

2023-06-20 14:59 UTC, Lofty-Brambles commented
@01zulfi - 👍 I was terribly busy

2023-06-24 13:28 UTC, 01zulfi approved these changes
Looks good 🚀

2023-06-24 13:28 UTC, merged