Update hooks.md
TheOdinProject/curriculum pull request #25708
Opened 2023-06-30 10:48 UTC by AtomicSage22

Hooks lesson: Fix useState paragraph text

## Because
It fixes a typo and makes it easier to read and understand.

## This PR

- Added punctuation
- Added grammatically correct words.

## Issue
Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-07-02 08:31 UTC, 01zulfi requested changes

2023-07-02 08:31 UTC, 01zulfi commented on javascript/react_js/hooks.md
>  ### useEffect
We need a newline before the heading for it to render correctly on the website:

```suggestion
Afterwards, we are declaring a function, which right now just sets a new count. In this case, we are incrementing the current count by one. This function will be called anytime we click the button. In the div above the button, we are just displaying the current state. One thing to mention and keep in mind here is that setting the state is an asynchronous task. Additionally, setting the state is called a re-render. That’s the reason we see the new count when clicking the button. If it wouldn’t trigger a re-render, then we would still see the old count. Our component will update after setting the state. As mentioned in our last lecture, we might want to use this opportunity for updating to do some tasks. Unfortunately, we don’t have any lifecycle methods for functional components, right?

### useEffect
```

2023-07-03 18:11 UTC, CouchofTomato approved these changes

2023-07-04 04:39 UTC, 01zulfi approved these changes

2023-07-04 04:39 UTC, merged