react/states_and_effects: add cv application project lesson
TheOdinProject/curriculum pull request #25728
Opened 2023-07-02 16:40 UTC by Lofty-Brambles

## Because

It'd revamp the existing CV application project.

## This PR

- Adds a new lesson under react/states_and_effects

## Issue

Closes https://github.com/TheOdinProject/top-meta/issues/265

## Additional Information

N/A

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-07-03 01:22 UTC, fcasibu reviewed
Great job with the lesson, love the options as well 🚀 Just added a few comments

2023-07-03 01:22 UTC, fcasibu commented on react/states_and_effects/project_cv_application.md
> +### Deploying A React App
```suggestion
### Deploying a React application
```

2023-07-03 01:22 UTC, fcasibu commented on react/states_and_effects/project_cv_application.md
> +Not only do some of these get rid of additional steps after pushing our code to GitHub as these services have tools that automatically _deploy on push_, but you also will not need to worry about othe
```suggestion
Not only do some of these get rid of additional steps after pushing our code to GitHub as these services have tools that automatically _deploy on push_, but you also don't have to worry about other issues further down the curriculum, like routers and build steps. We shall use a few selected options for now. Once you are done with the assignment, choose one of the following options, and deploy!
```

2023-07-03 01:22 UTC, fcasibu commented on react/states_and_effects/project_cv_application.md
> +1.  Push your React app to GitHub.
```suggestion
1.  Push your React application to GitHub.
```

2023-07-03 01:22 UTC, fcasibu commented on react/states_and_effects/project_cv_application.md
> +1.  Again, push your React app to GitHub.
```suggestion
1.  Again, push your React application to GitHub.
```

2023-07-03 01:22 UTC, fcasibu commented on react/states_and_effects/project_cv_application.md
> +1.  Yes, push your React app to GitHub.
```suggestion
1.  Yes, push your React application to GitHub.
```

2023-07-03 01:22 UTC, fcasibu commented on react/states_and_effects/project_cv_application.md
> +1.  Create a new React Project.
```suggestion
1.  Create a new React project.
```

2023-07-03 01:22 UTC, fcasibu commented on react/states_and_effects/project_cv_application.md
> +    3.  A section to add practical experience (company name, position title, main tasks of your jobs, date from and until when you worked for that company)
```suggestion
    3.  A section to add practical experience (company name, position title, main responsibilities of your jobs, date from and until when you worked for that company)
```

2023-07-04 04:48 UTC, 01zulfi requested changes
Can we put the `Deploying a react app` section after the `Assignment` section please? Also there would be minor changes needed accordingly. The reasoning is that I wouldn't want learners to worry about deploying until they've actually completed the project, hope it makes sense

2023-07-06 16:23 UTC, Lofty-Brambles commented
@01zulfi - made the changes

2023-07-07 04:03 UTC, 01zulfi approved these changes
Looks good to me 🚀

2023-07-07 04:03 UTC, merged