Change Headers to use spell-case for React Testing and React Ecosystem Sections
TheOdinProject/curriculum pull request #25896
Opened 2023-07-20 21:32 UTC by Babb2000

## Because
Changed Headers to use spell-case

## This PR
- Apply's spell-case to headers

## Issue
Related to #25861

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-07-20 21:47 UTC, ManonLef commented
Hi there! I noticed that at least these lessons are not included in these PR, but they still have a few headings that need to be sentence-cased. Would you mind PR'ing those so I can review them all at once?

- Type Checking With PropTypes
- Styling React Applications (Only the Component Libraries header I believe)

2023-07-20 23:56 UTC, ManonLef commented
@Babb2000 just give me an @ ping once all the lessons I mentioned are ready for review okay?

2023-07-21 16:18 UTC, ManonLef commented
Hi @Babb2000 ! I'd love to review this but would you mind changing this header still 
- Styling React Applications (Only the Component Libraries header)

2023-07-21 21:04 UTC, Babb2000 commented
@ManonLef Done

2023-07-21 21:13 UTC, ManonLef requested changes
Thanks for doing this. 
I edited a few as suggestions. 

Instead of locally editing these, you can also click `commit suggestion` on each of them to automatically commit the suggestions here.

2023-07-21 21:13 UTC, ManonLef commented on react/the_react_ecosystem/react_router.md
> +### Client-Side routing
```suggestion
### Client-side routing
```

2023-07-21 21:13 UTC, ManonLef commented on react/the_react_ecosystem/react_router.md
> +### Nested routes, outlets And dynamic segments
```suggestion
### Nested routes, outlets and dynamic segments
```

2023-07-21 21:13 UTC, ManonLef commented on react/the_react_ecosystem/type_checking_with_proptypes.md
> +### What about typeScript?
```suggestion
### What about TypeScript?
```

2023-07-22 14:22 UTC, ManonLef commented on react/the_react_ecosystem/react_router.md
> +### Client-Side routing
this one is not changed yet @Babb2000 :)

2023-07-23 19:19 UTC, ManonLef approved these changes

2023-07-23 19:20 UTC, ManonLef commented on react/the_react_ecosystem/react_router.md
> +### Client-Side routing
I committed this one myself to start wrapping up the issue

2023-07-23 19:20 UTC, merged

2023-07-23 19:20 UTC, ManonLef commented
Thanks again!