Added explanation of blocks/yields to enumerable project.
TheOdinProject/curriculum pull request #25981
Opened 2023-07-27 17:36 UTC by linkonsat

## Because

## This PR

Adds an example to the custom enumerable project to explain and refresh learners' memories on this topic before the custom enumerable projects. As folks in the project seemed to have a bit of hard time understanding how to use yields and blocks.

## Issue

Closes #23481
## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-08-03 14:04 UTC, zachmmeyer commented
Reviewing this now, I missed this notification and it got cleared out.

2023-08-03 14:16 UTC, zachmmeyer requested changes

2023-08-03 14:16 UTC, zachmmeyer commented on ruby/advanced_ruby/project_custom_enumerables.md
> +We will explain an example of how an enumerable works to give you an idea of how to start tackling these methods. Specifically were going to breakdown the `sort` enumerable method. The sort method so
GitHub found a typo here.
```suggestion
We will explain an example of how an enumerable works to give you an idea of how to start tackling these methods. Specifically were going to breakdown the `sort` enumerable method. The sort method sorts the elements by comparing their values based on whether one element is bigger, equal or smaller than the next element as shown below. 
```

2023-08-03 14:16 UTC, zachmmeyer commented on ruby/advanced_ruby/project_custom_enumerables.md
> +ary in this case would be the array that we use to put in our results from building our map method. Self in this case is _calling the method on itself_ which is how were able to do `.my_map` without
It's difficult to see what I modified here.
- our to have
- modified punctuation
- yield to yielded

I'd throw it in a real diff checker, it should show the changes to see if you agree with them.
```suggestion
ary in this case would be the array that we use to put in our results from building our map method. Self in this case is _calling the method on itself_ which is how were able to do `.my_map` without having to pass the array directly through the method parameters. Now that we that self refers to the array we can use the `each` method to pass each element. Now this is where yield becomes extremely useful. In our very first example of using `a.map` we used a special tool called a block. The block in this case is the `a.my_map {}` and this is where the values have changed. `yield` in this case specifies _what_ is passed, in this case the elem. Now that elem has been yielded it's accessible through the `{}` brackets and we can perform an operation on it. In this case: adding two. Therefore, we use the shovel method to add that element to the array that has been yielded to the block/`{}`. To recap briefly, the element is given to the `yield` through the elem or can be done by just putting something in the `{}` such as `puts 5` and the `{}` brackets is where the operation is performed. In essence the block/`{}` is where the `yield` operation is performed.
```

2023-09-03 19:01 UTC, JoshDevHub commented
I think this is an incredible idea, and I've been giving an example for a while now when talking to learners in the discord who are struggling with this exercise.

I will say that I think `sort` isn't ideal for demonstrating because it has a complicated implementation. The logic underpinning the method is the [quicksort algorithm](https://en.wikipedia.org/wiki/Quicksort). `map` also isn't great in my opinion because it's a part of the project itself. It'd be giving learners the answer to one of the problems.

I like using `#find`. It's pretty simple, and it's not part of the custom enumerables project
```rb
def my_find
  self.each do |elem|
    # if the element meets the block's conditions, return it
    return elem if yield(elem)
  end
  # if we're here, we looped the items without finding an element that meets the condition
  # return `nil`
  nil
end
```

2023-12-09 00:35 UTC, zachmmeyer commented
@JoshDevHub Is there anything you could add to this PR to improve upon it? Or would you be open to submitting something of your own?

2023-12-10 18:43 UTC, JoshDevHub commented
Hey @zachmmeyer 

Thank you for reminding me about this. I had forgotten about it completely.

My personal preference is to use something that isn't `#map` for demonstration. This is because `#map` is a part of the project, so it's essentially showing the learner how to solve one of the problems. But maybe that isn't such a huge deal.

In discord when helping people with this, I've often used `#find`, which is pretty straightforward and not part of the project. If you want, I could show an example of what that would look like.

2023-12-10 19:22 UTC, zachmmeyer commented
@JoshDevHub I think your reasoning is sound. Would you be up for opening a PR that uses `#find` instead? Then we could close this one down.

2023-12-11 04:24 UTC, JoshDevHub commented
@zachmmeyer Yeah, I'll whip something up :thumbsup:

2023-12-11 18:37 UTC, JoshDevHub commented
@zachmmeyer @linkonsat Okay I put in a PR for what I was thinking: #26915 

Let me know if y'all have any thoughts.

2023-12-11 19:13 UTC, closed without merging