Update motivation_and_mindset.md
TheOdinProject/curriculum pull request #26015
Opened 2023-08-01 09:29 UTC by CrypterSr

## Because

## This PR

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-08-01 13:35 UTC, zachmmeyer requested changes
I absolutely love TypingClub. I didn't know it existed when I suggested KeyBr honestly, and I would much prefer we shilled them haha.
I have one recommendation, I'm interested to know what you think.

2023-08-01 13:35 UTC, zachmmeyer commented on foundations/introduction/motivation_and_mindset.md
> +*   [Improve your typing skills with Keybr.com](https://www.keybr.com/). One excellent alternative is [typing.com](https://www.typing.com/). Another great option is [TypingClub.com](https://www.typin
What do you think of this? It gets the main point of the bullet across and keeps all the suggestions in their own sub-bullets.
```suggestion
*   If you find your typing speed is holding you back, you can improve your typing skills by utilizing these keyboard trainers for at least 5 minutes every day:
  * [Keybr.com](https://www.keybr.com/)
  * [typing.com](https://www.typing.com/)
  * [TypingClub.com](https://www.typingclub.com)
```

2023-08-01 13:43 UTC, zachmmeyer commented on foundations/introduction/motivation_and_mindset.md
> +*   [Improve your typing skills with Keybr.com](https://www.keybr.com/). One excellent alternative is [typing.com](https://www.typing.com/). Another great option is [TypingClub.com](https://www.typin
Good call, I'll update my comment. I didn't notice.

2023-08-02 15:24 UTC, zachmmeyer requested changes

2023-08-09 08:11 UTC, ManonLef commented
@CrypterSr I noticed you closing and reopening this PR. Let us know if you need any help on how to proceed with the reviews/suggestions.

2023-10-03 09:41 UTC, ManonLef commented on foundations/introduction/motivation_and_mindset.md
> +  * [Monkeytype](https://monkeytype.com/)
```suggestion
-   If you find your typing speed is holding you back, you can improve your typing skills by utilizing these keyboard trainers for at least 5 minutes every day:
   - [Keybr.com](https://www.keybr.com/)
    - [typing.com](https://www.typing.com/)
    - [TypingClub.com](https://www.typingclub.com)
    - [Monkeytype](https://monkeytype.com/)
```

2023-10-03 09:48 UTC, ManonLef commented
Since there was no response from the issue opener, I have made the suggested changes and also updated the entire list to the correct syntax for you to review @zachmmeyer

2023-10-03 10:52 UTC, zachmmeyer approved these changes
Looks like the merge conflict needs to be resolved and this will be good.
Thanks for finishing this.

2023-10-03 11:26 UTC, ManonLef commented
@zachmmeyer thanks, I missed the check :)

2023-10-03 11:26 UTC, merged