The Box Model, Block and Inline, Alignment Lessons: Move scrims to Additional Resources
TheOdinProject/curriculum pull request #26062
Opened 2023-08-06 10:46 UTC by aniket-agra

## Because

This PR moves Scrimba embeds from their current position to the Additional Resources section as link text as part of [this issue](https://github.com/TheOdinProject/curriculum/issues/26057).

## This PR

- Move one existing Scrim to Additional Resources for [The Box Model](https://www.theodinproject.com/lessons/foundations-the-box-model) lesson.
- Move one existing Scrim to Additional Resources for [Block and Inline](https://www.theodinproject.com/lessons/foundations-block-and-inline) lesson.
- Move two existing Scrims to Additional Resources for [Alignment](https://www.theodinproject.com/lessons/foundations-alignment) lesson.

## Issue

Related to #26057 

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-08-07 21:53 UTC, thatblindgeye requested changes
Thanks for updating these! Had some requests below. When it comes to link text, we need to avoid being vague with it ("This article", "click here", etc), as it makes it difficult for users navigating with assistive tech (like screen readers) to understand the link purpose without any surrounding context.

2023-08-07 21:53 UTC, thatblindgeye commented on foundations/html_css/css-foundations/block-and-inline.md
> +*  Try [this Scrim](https://scrimba.com/scrim/co5024997a7e46c232d9abe55) for a more interactive explanation and example of different options for block and inline display.
```suggestion
*  For a more interactive explanation and example, try this [Scrim on block and inline display](https://scrimba.com/scrim/co5024997a7e46c232d9abe55).
```

2023-08-07 21:53 UTC, thatblindgeye commented on foundations/html_css/css-foundations/the-box-model.md
> +*  Try [this Scrim](https://scrimba.com/scrim/cof3d488184abe24ec6258ab4) for a more interactive explanation and example of the box model.
```suggestion
*  For a more interactive explanation and example, try this [Scrim on the box model](https://scrimba.com/scrim/cof3d488184abe24ec6258ab4).
```

2023-08-07 21:53 UTC, thatblindgeye commented on foundations/html_css/flexbox/flexbox-alignment.md
> +* [This next Scrim](https://scrimba.com/learn/flexbox/align-items-flexbox-tutorial-cJqymH9) covers the behavior of `align-items`, how to perfectly center an element on a page using flexbox and much m
```suggestion
* For more interactive demos, try the [Scrim on the justify-content property](https://scrimba.com/learn/flexbox/justify-content-flexbox-tutorial-cVWPacR) and the [Scrim on the align-items property](https://scrimba.com/learn/flexbox/align-items-flexbox-tutorial-cJqymH9). Note that these Scrims require logging into Scrimba in order to view.
```

2023-08-08 19:05 UTC, thatblindgeye approved these changes

2023-08-08 19:05 UTC, aniket-agra commented
Thanks for the suggestions! I have updated the repo with the appropriate changes.

2023-08-08 19:05 UTC, merged