Factory functions and the module patterns, objects and object constructors: Move scrims to Additional Resources
TheOdinProject/curriculum pull request #26072
Opened 2023-08-07 09:24 UTC by ToobaJamal

## Because
This PR moves Scrimba interactive scrim embeds from their current position to the Additional Resources section as a link text as part of [this](https://github.com/TheOdinProject/curriculum/issues/26057) issue.

## This PR
- Moves existing Scrimba embed in [Factory Functions and the Module Pattern](https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern) to the Additional Resources section.
- Moves existing Scrimba embed in [Objects and Object Constructors](https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors) to the Additional Resources section.

## Issue
Related to #26057 

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-08-07 21:33 UTC, thatblindgeye requested changes
Thanks for the updates! Had some *slight* verbiage tweaks below, additionally there's a merge conflict that will need to be resolved as well.

2023-08-07 21:33 UTC, thatblindgeye commented on javascript/organizing_your_javascript_code/factory_functions_and_module_pattern.md
> +- [Interactive explanation of Factory Functions in JavaScript](https://scrimba.com/scrim/c2aaKzcV)
```suggestion
- [Interactive Scrim on factory functions](https://scrimba.com/scrim/c2aaKzcV)
```

2023-08-07 21:33 UTC, thatblindgeye commented on javascript/organizing_your_javascript_code/objects_and_object_constructors.md
> +- [Interactive tutorial on Objects and Object Constructors.](https://scrimba.com/scrim/co2624f87981575448091d5a2)
```suggestion
- [Interactive Scrim on objects and object constructors.](https://scrimba.com/scrim/co2624f87981575448091d5a2)
```

2023-08-08 06:24 UTC, ToobaJamal commented
@thatblindgeye I have made the requested changes and resolved the conflict as well. Thank you :)

2023-08-08 11:36 UTC, thatblindgeye approved these changes

2023-08-08 11:38 UTC, merged