Ruby/Rails Path: Introduction && Basic Ruby sections: Rewrite headings following the Style Guide
TheOdinProject/curriculum pull request #26170
Opened 2023-08-21 19:43 UTC by headlessNode

## Because

- Change the headings according to Style Guide requirement.

## This PR

- Change the headings of the Ruby introduction section to sentence case.
- Change the headings of the Ruby basic ruby section to sentence case.

## Issue

- Related to #25861

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

2023-08-21 19:45 UTC, ManonLef commented
That's quick! I'll review it right away. I'll also change the "related to" into the correct one for I've missed that in updating the text :)

2023-08-21 20:01 UTC, ManonLef requested changes
Thanks so much for doing this! The `Loops` lesson is the only one I have left a comment on since it seems to have a few more headers that need updating.

2023-08-22 03:18 UTC, headlessNode commented on ruby/basic_ruby/loops.md
Hi, I just updated the loops.md please check.

2023-08-22 07:18 UTC, ManonLef approved these changes

2023-08-22 07:18 UTC, ManonLef commented
Thank you again! Much appreciated

2023-08-22 07:18 UTC, merged