React: Merge using node lesson with conclusion
TheOdinProject/curriculum pull request #26278
Opened 2023-09-04 08:41 UTC by OmarNaguib

## Because

The "Using NodeJS For Your Backend" provided instructions that seemed out of place

## This PR

-edits the "Using NodeJS For Your Backend" in place (for ease of comparison)
-merges it with the conclusion lesson
-makes a react directory in the archive directory and moves the old lesson into it

## Issue

Closes #25998

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-09-08 11:54 UTC, 01zulfi requested changes
Left couple of comments below to make the changes concise.

Additionally, please make a copy of the current conclusion lesson into a separate file called `conclusion_ruby_on_rails.md`. Then, the changes you suggested in this PR should be reflected in a new file called `conclusion_full_stack_javascript.md`. This is because these changes should be shown in the Node path, not the Ruby on Rails path. The only way I can think of right now is to have separate files. in the curriculum repository.

Also putting this here: once this PR is merged, we'll need to update the website repository as well to reflect the changes.

2023-09-08 11:54 UTC, 01zulfi commented on react/conclusion/conclusion.md
> +While Local Storage is great, it's not ideal: it only stores data on the computer from which the user is accessing the page. This approach does not allow for the app to 'remember' anything when the s
I feel this paragraph is redundant. Thoughts on removing it?

2023-09-08 11:54 UTC, 01zulfi commented on react/conclusion/conclusion.md
> +### NodeJS to the rescue!
Not sure we need to keep this heading as well.. What do you think?

2023-09-08 16:26 UTC, OmarNaguib commented
> Additionally, please make a copy of the current conclusion lesson into a separate file called `conclusion_ruby_on_rails.md`. Then, the changes you suggested in this PR should be reflected in a new file called `conclusion_full_stack_javascript.md`. This is because these changes should be shown in the Node path, not the Ruby on Rails path. The only way I can think of right now is to have separate files. in the curriculum repository.
> 
done

2023-09-09 10:45 UTC, thatblindgeye requested changes

2023-09-09 10:45 UTC, thatblindgeye commented on react/conclusion/conclusion_full_stack_javascript.md.md
> +NodeJS is a JavaScript runtime environment which will let you build an entire backend with JavaScript. We'll learn all about it next in our [NodeJS](https://www.theodinproject.com/paths/full-stack-ja
I feel like these two sections can be combined into one + some other tweaks:

```suggestion
### Using a backend

As you've seen, you can get your apps to do a lot of pretty cool things already, just using client-side JavaScript. You may have noticed, though, that there is still an important piece of the puzzle missing: unless you use [Local Storage](http://coding.smashingmagazine.com/2010/10/11/local-storage-and-how-to-use-it/), your app 'forgets' the user's preferences, as well as any other changes made, as soon as the page gets reloaded.

While Local Storage is great, it's not ideal: it only stores data on the computer from which the user is accessing the page. This approach does not allow for the app to 'remember' anything when the same user tries to access it again from a different device. For that, you're going to need a real backend, which you'll learn all about next in our [NodeJS](https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs) course. With Node, we'll be able to add a bunch of cool features to your apps like user authentication, data persistence, and more.
```

2023-09-19 15:40 UTC, 01zulfi approved these changes
This looks good. Before we merge, we need to make relevant changes to the website repository as well. @OmarNaguib, are you willing to work on that? If not, that's okay as well.

2023-09-19 18:13 UTC, OmarNaguib commented
> This looks good. Before we merge, we need to make relevant changes to the website repository as well. @OmarNaguib, are you willing to work on that? If not, that's okay as well.

Yeah I would like to @01zulfi

2023-09-20 06:57 UTC, 01zulfi commented
@OmarNaguib Great, tag me when the website PR is ready for review. Do let me know if you need any help

2023-09-23 08:01 UTC, merged