JS Tic-Tac-Toe: Improve instructions order
TheOdinProject/curriculum pull request #26286
Opened 2023-09-05 16:04 UTC by MaoShizhong

## Because
As per #26280, this is a proposal for revamped JS TTT instructions to address the following:
- Bringing the "Building a house" resource to an earlier step as it can provide great insight to both the overall approach as well as overall structure - more useful earlier on in the process than previously, where people may well have written plenty of code and already settled on a perhaps less ideal structure.
- Rewriting instructions for what things to write/focus on to be more consistent with the "building a house" resource approach (don't touch display stuff until game logic works in console first). This is to reinforce the idea that logic such as the display/DOM is not part of the game flow logic and how decoupling it (both in a module and also in development flow) can aid with more modular code and workflow.
- Reworded the suggestions about using an IIFE for singletons. I felt the original wording could be interpreted as "IIFEs are used in order to instantiate singletons" (I remember having this confusion at first) as opposed to dealing utilising how it alters scope. I remember not understanding how ES6 modules "meant IIFEs weren't as useful anymore" because my understanding was ES6 modules were to do with scope and IIFEs were used to make singletons.

## This PR
- Rewrote instructions to address the above issues

## Issue
Closes #26280

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-10-30 14:58 UTC, MaoShizhong commented
*Gentle bump if that's alright* ^^'

2023-10-30 15:34 UTC, CouchofTomato commented
@01zulfi 

Are you still handling this one mate?

2023-11-04 08:23 UTC, 01zulfi requested changes

2023-11-04 10:59 UTC, 01zulfi commented on javascript/organizing_your_javascript_code/project_tic_tac_toe.md
> -   3. If you get this running _definitely_ come show it off in the chatroom.  It's quite an accomplishment!
Let's keep this change as per https://github.com/TheOdinProject/curriculum/issues/26172#issuecomment-1793410258

2023-11-04 18:13 UTC, 01zulfi approved these changes
lgtm :rocket:

2023-11-04 18:14 UTC, merged