Update deployment.md
TheOdinProject/curriculum pull request #26296
Opened 2023-09-07 08:22 UTC by saurabhje

Deployment - Our recommended PaaS services:  Added one more PaaS ( Glitch )  section that can be used to deploy the previously created project (Mini Message Board)

## Because
It makes deploying of the Node Js project Mini Message board in the express section fairly easier, by using Glitch PaaS.
User simply has to import the code from the project's github repo and share.

## This PR
Added another section of a PaaS in the "Our  recommended PaaS services" in the lesson "Deployment" of the Node section

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-09-07 08:23 UTC, saurabhje commented
Added one more PaaS

2023-09-07 11:47 UTC, rlmoser99 commented
I've assigned someone to review this PR, but in the meantime could you please fill out the PR template, paying special attention to the Pull Request Requirements.

2023-09-09 11:06 UTC, thatblindgeye requested changes
Some changes below, but I would like someone more savvy with these courses to also take a look.

2023-09-09 11:06 UTC, thatblindgeye commented on nodeJS/express_and_mongoose/deployment.md
> +- The best part of this, you don't have to add your credit card *wink wink* info to deploy your apps freely here.
```suggestion
### Glitch

- Glitch enables you to effortlessly deploy simple and small Express apps in just a few easy steps.
- Github import and export support.
- No credit card needed
```

2023-09-09 11:06 UTC, thatblindgeye commented on nodeJS/express_and_mongoose/deployment.md
> +- Full stack apps that will sleep after 5 mins of inactivity but gets back on if a user wants to access it.
```suggestion
**Free Plan**

- 1000 hours usage per month for each app.
- Unlimited static websites that are always on.
- Full stack apps will be put to sleep after 5 minutes of inactivity.
```

2023-09-09 11:06 UTC, thatblindgeye commented on nodeJS/express_and_mongoose/deployment.md
> +- [Homepage](https://glitch.com/)
```suggestion
- [Glitch](https://glitch.com/)
```

2023-09-09 16:22 UTC, saurabhje reviewed
more concise , better.

2023-11-04 12:15 UTC, thatblindgeye commented
@TheOdinProject/javascript any thoughts on this addition?

2023-12-05 10:03 UTC, closed without merging