Text Editors lesson: Update lists per layout style guide
TheOdinProject/curriculum pull request #26453
Opened 2023-10-09 04:28 UTC by ScaxCodes

## Because

Update the lists syntax of the lessons to align with the TOP style guide.

## This PR

- Add punctuation at the end of unordered lists, following the google style guide.
- Change `*` to `-` syntax in unordered lists.

## Issue

Closes #26437

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-10-09 07:19 UTC, ManonLef commented
FYI it should be **Related to** #26437 and not **Closes** since there are multiple people working on the issue. Could you edit that in your description?

2023-10-09 08:08 UTC, ScaxCodes commented
Thank you @ManonLef, I didn't notice that.

2023-10-09 21:25 UTC, thatblindgeye requested changes
Some spacing changes noted below. Additionally can we remove the spacing from the Assignment numbered item?

2023-10-09 21:25 UTC, thatblindgeye commented on foundations/installations/text_editors.md
> +   - Run the following command to download the latest **VSCode** `.deb` package.
```suggestion
- Open your **Terminal**.
- Run the following command to download the latest **VSCode** `.deb` package.
```

2023-10-09 21:25 UTC, thatblindgeye commented on foundations/installations/text_editors.md
> +   - Enter the following command in your terminal to install the **VSCode** `.deb` package.
```suggestion
- Enter the following command in your terminal to install the **VSCode** `.deb` package.
```

2023-10-09 21:25 UTC, thatblindgeye commented on foundations/installations/text_editors.md
> +   - If prompted, enter your password.
```suggestion
- If prompted, enter your password.
```

2023-10-09 21:25 UTC, thatblindgeye commented on foundations/installations/text_editors.md
> +   - **Or**, use the `code` command from the terminal.
```suggestion
- Click **Visual Studio Code** from the Applications menu.
- **Or**, use the `code` command from the terminal.
```

2023-10-09 21:25 UTC, thatblindgeye commented on foundations/installations/text_editors.md
> +   - Drag the **Visual Studio Code.app** icon to the **Applications** folder icon.
```suggestion
- Open the **Downloads** folder.
- Double click the file **VSCode-darwin-universal.zip**.
- Drag the **Visual Studio Code.app** icon to the **Applications** folder icon.
```

2023-10-09 21:25 UTC, thatblindgeye commented on foundations/installations/text_editors.md
> +   - Drag **VSCode-darwin-universal.zip** to the trash.
```suggestion
- Open **Finder**.
- Go to the **Downloads** folder.
- Drag **VSCode-darwin-universal.zip** to the trash.
```

2023-10-09 21:25 UTC, thatblindgeye commented on foundations/installations/text_editors.md
> +   - Double click **Visual Studio Code**.
```suggestion
- Go to your **Applications** folder.
- Double click **Visual Studio Code**.
```

2023-10-10 17:11 UTC, ScaxCodes commented
So I did apply the suggestions from @thatblindgeye, now I want to add another commit as requested (remove spacing from the Assignment numbered item).

In this PR, there is this message:
> Add more commits by pushing to the [update_lists_layout](https://github.com/ScaxCodes/curriculum/tree/update_lists_layout) branch on [ScaxCodes/curriculum](https://github.com/ScaxCodes/curriculum).

But when I open my branch in VS Code, the suggestions mentioned above are not live in my local repo.
Is there a way to sync my local repo with the current state of the PR, or do I have to fix the spacing again manually in my code editor?

Whats the best practise?
@ManonLef can you help out?

2023-10-10 18:43 UTC, ScaxCodes commented
Okay so I just played a bit around in the PR, and realized I can either edit the file right at Github in this PR and commit the change, or I can display and copy the code from the current state from this PR and paste it into my editor.

The consequences will vary a bit, I guess there will be a conflict when I commit the next change via my local repo, as this commit would try to change the suggestions from @thatblindgeye again, even its already changed in the PR.

I hope you can understand my logic, PR is just a new territory for me, and I would be happy if you can clarify this a bit.

I will commit via Github without my editor, I think its the best solution here.

2023-10-10 19:37 UTC, ManonLef commented
@ScaxCodes you'd have to `pull` the branch to get the GH changes you've committed to your local branch as well :) But editing it on GH works fine too

2023-10-10 19:41 UTC, ScaxCodes commented
@ManonLef I see, my branch gets updated during the PR, I just have to pull the current state via the CLI to update my local repo. I think I did not realize that my branch got updated, I thought the changes are isolated in this PR. Thank you!

2023-10-12 20:07 UTC, thatblindgeye approved these changes
Thanks for the updates! And glad you got things figured out, ➕➕  to @ManonLef for helping you out

2023-10-12 20:07 UTC, merged