Removed the section where there is a broken link as mentioned in the …
TheOdinProject/curriculum pull request #26595
Opened 2023-10-28 13:42 UTC by Learningcomputers777

Because:
Removed the section of the broken link.

This PR:
The link in the 4th point of the assignment section is broken so I have removed it as per the issue #26581. The link of the file (https://github.com/TheOdinProject/curriculum/blob/main/nodeJS/introduction_to_nodeJS/introduction_what_is_nodeJS.md).

Issue:
Closes #26581 

Additional Information

Pull Request Requirements

 I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
 The title of this PR follows the location of change: brief description of change format, e.g. Intro to HTML and CSS lesson: Fix link text
 The Because section summarizes the reason for this PR
 The This PR section has a bullet point list describing the changes in this PR
 If this PR addresses an open issue, it is linked in the Issue section

2023-10-28 13:44 UTC, Learningcomputers777 commented
Excuse me for the template thing. I didn't know how to make a PR with that template so I thought rather focusing on the template I thought it would be good to do the changes and make the PR. So i submitted the  PR of the required changes.

2023-10-30 13:18 UTC, CouchofTomato requested changes
It seems the link has just updated to 

https://nodejs.org/en/docs/guides/getting-started-guide

We can just update the link.

2023-10-30 13:56 UTC, Learningcomputers777 commented
Resolved the conflict as per the changes you have mentioned.

2023-10-30 14:04 UTC, CouchofTomato approved these changes

2023-10-30 14:05 UTC, merged