Changed Twitter to X in personal portfolio
TheOdinProject/curriculum pull request #26603
Opened 2023-10-29 03:19 UTC by AlzyWelzy

2023-10-30 13:36 UTC, CouchofTomato commented
There are merge conflicts with this PR.

2023-11-27 00:41 UTC, wise-king-sullyman commented
@AlzyWelzy are you planning to resolve the merge conflicts in this PR?

2023-11-27 00:42 UTC, wise-king-sullyman requested changes

2023-11-27 00:42 UTC, wise-king-sullyman commented on advanced_html_css/responsive_design/project_personal_portfolio.md
> +3. In the design we have icon-links for GitHub, LinkedIn and X. Obviously feel free to add whatever links you want to your own site. We got those icons from [https://devicon.dev/](https://devicon.dev
There are merge conflicts which need to be resolved.

2023-12-10 02:25 UTC, wise-king-sullyman commented
I'm a bit confused, it looks like the merge conflict still needs to be resolved and you've added conduct code and contributing files?

2024-01-14 23:07 UTC, wise-king-sullyman commented
Closing due to inactivity.

2024-01-14 23:07 UTC, closed without merging