Updated the name of Twitter to X in all docs
TheOdinProject/curriculum pull request #26627
Opened 2023-10-30 17:54 UTC by Arcturus22

This repository has so many stars and forks. Wouldn't it be the best to be updated with the latest?

I have changed the name of Twitter to X in all the documentation of this repo.
Everyone must be well aware by now that the legal name of Twitter has been formally changed to X. Therefore, I have updated the README files and other files and corrected the name to X.

2023-10-30 17:55 UTC, Arcturus22 commented
@CouchofTomato 
Kindly review this PR and merge it. Suggest changes (if any)

2023-10-31 12:30 UTC, CouchofTomato commented
Why are some X and some X(twitter). How have you decided which ones to change to what?

2023-10-31 21:43 UTC, rlmoser99 commented
@CouchofTomato Not to disagree with you, but I know we've made the decision to stick with the twitter logo in our footer. Which makes me question changing our lesson content to use X.
https://github.com/TheOdinProject/theodinproject/issues/4161

2023-10-31 21:48 UTC, rlmoser99 commented
@Arcturus22 In the future, I kindly suggest you to not ping maintainers to review and merge your PR. We are a volunteer team that has to balance our full-time jobs, families, and other obligations. Plus, we have a system in place to review PRs in a timely manner.

2023-11-02 14:14 UTC, CouchofTomato commented
@rlmoser99 I think either way it doesn't matter to be honest. X is the proper name now and over time the name Twitter will be used less and less. For now it doesn't matter though.

2023-11-04 13:21 UTC, rlmoser99 requested changes
Thanks for taking the time to make these changes and for being patient while we figure out how to move forward with this PR.

We discussed it with the maintainer team, and decided that we are okay with using "Twitter" to "X (formerly Twitter)" in our curriculum. In addition, use of the word "tweet" should be changed to "post"

Finally, I would like the lessons in the `archive` folder to not be changed. They are only there for historical purposes, so I do not believe they should get this updated.

2023-11-04 13:21 UTC, rlmoser99 commented on ruby_on_rails/rails_basics/deployment.md
> +Dynamic websites, on the other hand, are websites that can change content based on the user who is visiting them. X(Twitter) is a good example; every X(Twitter) user sees different content on their h
I think in this example, the second use of X could be left out.

> X (formerly Twitter) is a good example; every user...

2023-11-04 13:21 UTC, rlmoser99 commented on ruby_on_rails/forms_and_authentication/project_members_only.md
> +and [A X(Twitter) Clone Lets Build with Ruby on Rails Part 2](https://www.youtube.com/watch?v=fyj70TbS75c&t=474s). If you still need more inspiration for this project or want more insight then the re
In this example, the video title uses Twitter, so I think we should leave these as is.

2023-11-04 13:21 UTC, rlmoser99 commented on ruby_on_rails/apis/working_with_external_apis.md
> +  1. Watch [this Railscast on using Omniauth to allow X (Twitter) Signin](http://railscasts.com/episodes/241-simple-omniauth-revised).
I think this could be more generic, so something like this:

> on using Omniauth to allow third party sign in

2023-11-04 13:21 UTC, rlmoser99 commented on nodeJS/express_and_mongoose/deployment.md
> +Dynamic websites, on the other hand, are websites that can change content based on the user who is visiting them. X (Twitter) is a good example; every X (Twitter) user sees different content on their
I think in this example, the second use of X could be left out.

> X (formerly Twitter) is a good example; every user...

2023-12-05 10:05 UTC, KevinMulhern commented
@Arcturus22 just checking in, do you still want to finish this PR?

2024-01-18 07:08 UTC, kamranzafar4343 reviewed
Just reviewing the code

2024-02-09 18:39 UTC, thatblindgeye commented
@Arcturus22 checking in again on the status of this PR. If there is no further activity this may be closed and an issue created instead.

2024-02-27 18:52 UTC, closed without merging