TODO List Project conclusion: Removes algorithm practice site mention
TheOdinProject/curriculum pull request #26681
Opened 2023-11-06 02:58 UTC by bycdiaz

## Because

Many learners are detouring the curriculum to engage with sites like codewars when it is presently mentioned.

The challenge is that many will arrive to these sites and struggle when they encounter problems that require awareness of some algorithm. And those situations aren't productive.
## This PR

This PR:

- will remove the mention of these algorithm practice sites from the TODO List Project
- adds context about how to engage with them productively in the Preparing to Interview lesson.

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-11-11 04:12 UTC, kashura requested changes

2023-11-11 04:12 UTC, kashura commented on getting_hired/applying_and_interviewing/preparing_to_interview_and_interviewing.md
> +This would be like being tasked with getting the length of a Hypotenuse in a triangle but having no awareness of the Pythagorean theorem. Without awareness of that theorom, that calculation can feel
typo "theorom"

2023-11-12 05:46 UTC, bycdiaz commented on getting_hired/applying_and_interviewing/preparing_to_interview_and_interviewing.md
> +This would be like being tasked with getting the length of a Hypotenuse in a triangle but having no awareness of the Pythagorean theorem. Without awareness of that theorom, that calculation can feel
Ah. Thanks for catching that. 🙏

2023-11-12 16:05 UTC, kashura approved these changes

2023-11-12 16:06 UTC, merged