too specific instructions for Knights Travails
TheOdinProject/curriculum pull request #26710
Opened 2023-11-09 19:47 UTC by OmarNaguib

## Because

-Wasn't clear that there is no need for GUI
-instructions suggested users have to make Board and Knight objects
-instructions suggested users have to represent the problem as a tree

## This PR

-Clarified there is no need for GUI
-used more generalized instructions

## Issue

Closes #26301

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-11-09 21:30 UTC, JoshDevHub requested changes
Great stuff. Just a couple small fixes

Also, would you be comfortable making these same changes for the ruby path's version of this project? The projects have the exact same instructions, and the only differences are things like using `snake_case` with Ruby and `camelCase` with JavaScript. That's not relevant for the changes you're making here though. You should be able to just make these same changes over in the ruby course's `project_knight_travails.md` file.

2023-11-09 21:30 UTC, JoshDevHub commented on javascript/computer_science/project_knights_travails.md
> +1. Think about the rules of the board and knight, make sure to follow them.
```suggestion
1. Think about the rules of the board and knight, and make sure to follow them.
```

2023-11-09 21:30 UTC, JoshDevHub commented on javascript/computer_science/project_knights_travails.md
> +2. For every square there is a number of possible moves, choose a data structure that will allow you to work with them .  Don't allow any moves to go off the board.
```suggestion
2. For every square there is a number of possible moves, choose a data structure that will allow you to work with them. Don't allow any moves to go off the board.
```

2023-11-14 06:19 UTC, JoshDevHub commented
Do you want to make the same changes in the ruby course @OmarNaguib ?

If not that's fine, I just wanted to give you the opportunity to add that in before merging this.

2023-11-16 00:02 UTC, OmarNaguib commented
@JoshDevHub, Thank you for the opportunity, I think i added the required changes

2023-11-16 01:11 UTC, JoshDevHub approved these changes
Looks great. Thank you for contributing @OmarNaguib :raised_hands:

2023-11-16 01:11 UTC, merged