React: add note in keys section
TheOdinProject/curriculum pull request #26751
Opened 2023-11-16 18:24 UTC by Baguirre03

## Because

- SO people remember not to worry about `props` while learning about keys

## This PR

- Adds a note

## Issue

Closes #26722 

## Additional Information

I <3 open source

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-11-17 06:40 UTC, 01zulfi requested changes

2023-11-17 06:40 UTC, 01zulfi commented on react/getting_started_with_react/keys_in_react.md
> +Reminder: We will be using `props` here, and you will learn more about them in the next lesson. For now, you just need to know that `props` are arguments that are passed into components.
Small suggestion: the lesson note styling already highlights the text, not sure if we need the "Reminder" phrase
```suggestion
We will be using `props` here, and you will learn more about them in the next lesson. For now, you just need to know that `props` are arguments that are passed into components. 
```

2023-11-18 20:28 UTC, Baguirre03 commented
updated

2023-11-19 08:20 UTC, 01zulfi approved these changes
lgtm 🚀

2023-11-19 08:20 UTC, merged