Node pathway/Linting: Add section on template repos
TheOdinProject/curriculum pull request #26829
Opened 2023-11-27 20:03 UTC by MaoShizhong

## Because
Template repos are simple and very handy, and are commonly suggested when learners ask about easier ways to manage things like reusing Webpack config for new projects.
A brief mention of what they are and how to set/use one has been added to the end of the Linting lesson, as part of the lesson's "productivity" theme, whilst also giving the learner an opportunity to get a better feel for Webpack across Restaurant Page/To-do list first.

## This PR
- Adds content on template repos
- Rephrase intro text to account for new content
- Add knowledge check and doc link for template repos

## Issue
Closes #26515

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-11-28 03:55 UTC, wise-king-sullyman requested changes
I dig it 🚀 

One small nit:

2023-11-28 03:55 UTC, wise-king-sullyman commented on javascript/javascript_in_the_real_world/linting.md
> +With the last few projects, you have felt that setting up Webpack involved a fair few files and configuration, and that you may have had to look at what you configured before to copy and paste the co
```suggestion
With the last few projects, you might have felt that setting up Webpack involved a fair few files and configuration, and that you may have had to look at what you configured before to copy and paste the configuration you want to reuse. You may also have noticed that whenever you create a new repository on Github, there is an option near the top for a `Repository template`.
```

2023-11-28 11:46 UTC, MaoShizhong commented
Good catch, it must have gotten chopped off in a reword and I missed it...thank you!
I also just noticed the branch spelling...

2023-11-29 02:17 UTC, wise-king-sullyman commented
😂 I hadn't noticed the branch name until you mentioned it!

2023-11-29 02:17 UTC, wise-king-sullyman approved these changes
🔥 🔥 🔥

2023-11-29 02:17 UTC, merged