Node messaging app: Mention expectations regarding real time functionality
TheOdinProject/curriculum pull request #26830
Opened 2023-11-27 20:27 UTC by MaoShizhong

## Because
Methods for implementing real time functionality (e.g. polling/SSE/websockets etc.) have not been taught yet in the Node course. Unless these are later added to the curriculum, the Node messaging app ought to clarify that the user is not expected to implement any real time functionality in this project.

## This PR
- Adds mention of real time functionality expectations and explanation
- Fixes nested numbered list indentation to follow style guide
- Replaces `*` for `-` for extra credit unordered list to follow style guide

## Issue
Closes #26525

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2023-11-27 20:29 UTC, MaoShizhong commented
Side note - I noticed that the messaging app and Where's Waldo project `.md` files are currently in `react/react_and_the_backend` and not in the `nodeJS` directory.
How straightforward would this be to restructure?  If this will not cause any significant conflicts then after this has been approved and merged, I can open a new PR to move them into the appropriate `nodeJS` directory.

2023-11-28 02:23 UTC, JoshDevHub commented
> Side note - I noticed that the messaging app and Where's Waldo project .md files are currently in react/react_and_the_backend and not in the nodeJS directory.
How straightforward would this be to restructure? If this will not cause any significant conflicts then after this has been approved and merged, I can open a new PR to move them into the appropriate nodeJS directory.

You'll notice if you closely read the project prompts that there's nothing specific to NodeJS about them. This is partially because people who are this far can be given very high level instructions, but it's also because these same projects exist in the Ruby/Rails path. But in that path, they are placed in the React content rather than the "backend" -- owing to the way things are ordered there (backend comes before React).

Anyways, I probably don't think it makes sense to move them inside the `nodeJS/` directory when the Rails path is using them, although I get that it's probably a bit of a confusing navigational experience from a node learner's perspective.

As another aside: rails learners doing this project actually *have* been exposed to websockets :laughing: 
I think it's still fine though because although they've been shown how to use them in a Rails monolith, they haven't been shown how to interact with websockets on the React end of a split FE/BE app.

2023-11-28 02:29 UTC, JoshDevHub requested changes
Couple incredibly small nits but otherwise this looks good.

2023-11-28 02:29 UTC, JoshDevHub commented on react/react_and_the_backend/project_messaging_app.md
> +   1. You may have realised that a REST API backend cannot handle real time updates. It is "request-response", so the server can only respond to a request. If a user sends a message to another user,
```suggestion
   1. You may have realized that a REST API backend cannot handle real time updates. It is "request-response", so the server can only respond to a request. If a user sends a message to another user, a REST API cannot automatically notify the recipient as the recipient will not have requested that data. Whilst there are ways to implement real time functionality (e.g. polling, server-sent events, websockets etc.), these methods have not been taught, so you are not expected to implement any in this app.
```
"realize" for "realise" is an American English vs UK English thing. The style guide indicates a preference for American English.

2023-11-28 11:44 UTC, MaoShizhong commented
Good catch, I need to remember to switch to AE mode when working on these repos.
I have reworded the last bit of the additions to be a bit more pathway-agnostic whilst hopefully still retaining the same message.

2023-11-28 16:40 UTC, JoshDevHub approved these changes
Awesome work @MaoShizhong :raised_hands:

2023-11-28 16:40 UTC, merged