JavaScript Basics - Fundamentals Part 1: Added JavaScript description and MDN article link
TheOdinProject/curriculum pull request #27063
Opened 2024-01-06 12:20 UTC by Churtified

… link explaining javascript

## Because
The first JavaScript lesson in fundamentals was missing a description of what JavaScript does, in the introduction. By adding this description, it is a helpful reminder before starting exercises, especially after finishing HTML and CSS. The resourse section could also do with the MDN article as that goes a bit more in depth.

## This PR
- Added description of JavaScript in Introduction header.
- Added MDN article link of JavaScript in additional resources.

## Issue
Closes #27059

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-01-07 11:12 UTC, 01zulfi requested changes

2024-01-07 11:12 UTC, 01zulfi commented on foundations/javascript_basics/fundamentals-1.md
> +- [This MDN article](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript) explains a bit more about JavaScript on a high-level.
We should have a descriptive link text
```suggestion
- This [MDN article on what is JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript) explains a bit more about it on a high-level.
```

2024-01-08 09:41 UTC, Churtified reviewed
Thanks for the suggestion. Commited the change

2024-01-09 13:24 UTC, 01zulfi approved these changes
lgtm :rocket:

2024-01-09 13:24 UTC, merged