React/Setting Up A React Environment: Add additional resources
TheOdinProject/curriculum pull request #27235
Opened 2024-01-30 09:28 UTC by scottwright-dev

## Because

This PR adds additional optional resources. The additional video resources offer clear, step-by-step instructions on setting up a Vite React App with ESLint and Prettier in VSCode, and an introduction to React Dev Tools in Chrome. 

## This PR

Adds the following to the additional resources section:
1. A video resource outlining how to correctly set up a Vite React App with EsLint & Prettier in VSCode.
2. A video resource providing a brief overview of React Dev Tools in Chrome and how to get started with it.

## Issue

Closes: N/A

## Additional Information

N/A

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-01-30 09:42 UTC, scottwright-dev commented
Looks like this PR has highlighted some additional formatting issues in the MD file. I am happy to work through these but will take me a bit of time.

2024-02-23 16:26 UTC, thatblindgeye requested changes
Couple comments below, one being a change request for link text

2024-02-24 17:01 UTC, scottwright-dev commented on react/introduction/setting_up_a_react_environment.md
> +- [This video](https://www.youtube.com/watch?v=SMbqi1HPprc) is a helpful guide on how to set up Prettier inside your Vite-React projects.
Hi @thatblindgeye, it essentially covers setting up Prettier with a React project properly, so probably more of a "nice to have" more than anything. I just felt it helped contextualise the set up process abit. 

It seems however the PR #27423 could well render that addition less relevant.

2024-02-28 12:51 UTC, thatblindgeye commented on react/introduction/setting_up_a_react_environment.md
> +- [This video](https://www.youtube.com/watch?v=SMbqi1HPprc) is a helpful guide on how to set up Prettier inside your Vite-React projects.
@scottwright-dev If you find it helpful to have an optional visual reference for how to set them up together I won't block it, so I'll leave it up to you on its relevancy/usefulness. If you would like to keep it, let's just update the it to:

```suggestion
- [Vite React App with EsLint & Prettier in VSCode (2023)](https://www.youtube.com/watch?v=SMbqi1HPprc) is a helpful video guide on how to set up Prettier inside your Vite-React projects.
```

2024-03-20 22:30 UTC, zachmmeyer commented
@scottwright-dev are you able to resolve your merge conflict?

2024-03-25 15:16 UTC, scottwright-dev commented
> @scottwright-dev are you able to resolve your merge conflict?

Hey @zachmmeyer, all done. Appreciate your patience! Best, Scott

2024-03-26 22:36 UTC, thatblindgeye approved these changes

2024-03-26 22:37 UTC, merged