DOM Manipulation and Events: Update lists per layout style guide
TheOdinProject/curriculum pull request #27269
Opened 2024-02-03 15:46 UTC by adityax4

## Because

The Markdown files should be updated as per layout style guide for better readability.

## This PR

- Updated lists per layout style guide.
- Added lazy numbering in lists.
- Removed extra unnecessary spaces.

## Issue

Related to #27119

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-02-05 22:11 UTC, thatblindgeye requested changes

2024-02-05 22:11 UTC, thatblindgeye commented on foundations/javascript_basics/DOM_manipulation_and_events.md
> +### DOM Document Object Model
Let's just update this to remove DOM:

```suggestion
### Document Object Model
```

2024-02-06 02:39 UTC, adityax4 commented
hey @thatblindgeye, there's a link error that asks that Link fragments should be valid.
[Context: "[What is the DOM?](#dom-document-object-model)"]
then, this also needs to be updated to:
[What is the DOM?](#document-object-model)
but in html file the <a href attribute is #dom-document-object-model

that's why i removed the hyphen initially from the heading to resolve this lint error.
what to do next? guide please.

2024-02-08 12:50 UTC, thatblindgeye commented
@adityax4 you can update that knowledge check url to `#document-object-model`

2024-02-08 13:03 UTC, adityax4 commented
> @adityax4 you can update that knowledge check url to `#document-object-model`

@thatblindgeye done, everything's good now :)

2024-02-09 13:39 UTC, thatblindgeye approved these changes
💯 Thank you!

2024-02-09 13:39 UTC, merged