Advanced HTML and CSS - Animation: Update codeblock delimiters
TheOdinProject/curriculum pull request #27391
Opened 2024-02-18 01:55 UTC by Churtified

## Because
The code blocks in this section need to be updated to align with the new layout style guide.

## This PR
- Update all tilde to backticks to align with style guide

## Issue

Related to #27303

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-02-18 02:39 UTC, Churtified commented
Okay, I'm gonna need some help/suggestion here!

I've updated all the backticks, and most of the other lint issues.

These other issues I am unsure of.
**Links must have a descriptive text label**
I have read the style guide and it makes sense, however I can't seem to find what makes a link qualify as "descriptive". Also, should I reword the sentence and context to what I would find reasonable? Or is there a specific rule to this?

**Multiple headings with the same content**
There are 2x H3's, Two-dimensional transforms and Three-dimensional transforms. Within each of them there are 3x H4's that a repeated, within their own context it makes sense. However the linter does not like this. I am unsure of how to resolve this?

**Required heading structure**
The Assignment H3 seems to be required on all lessons, however the transforms lesson does not have it. I have read the style guide and it says "If the lesson does not have an assignment, remove this entire section from the lesson."
What do we normally do in this case?

**Sections have default content**
The other ones I corrected make sense. However this one threw me off, not really sure what this means at all -
_advanced_html_css/animation/transitions.md:1 TOP003/default-section-content Sections have default content [This rule threw an exception: Value of 'lineNumber' passed to onError by 'TOP003' is incorrect for '/home/runner/work/curriculum/curriculum/advanced_html_css/animation/transitions.md'.]_

If someone could give me some guidance, I can go back and complete. Thanks!

2024-02-22 16:39 UTC, JoshDevHub requested changes
> Links must have descriptive label

This emerges from having things like "click here" or "this link". These should change to directly reference where you are taken when the link is clicked.

So for example, taking this link in the content:
```md
See MDN's 3D cube in action with `scaleZ` [here](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scaleZ())
```
This could change to:
```md
See MDN's 3d cube in action by viewing the [`scaleZ` documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scaleZ())
```

> Multiple headings with the same content
> Required heading structure

Let's ignore these in this PR for the time being. I'll create a separate issue after this PR is merged for addressing this problem.

> Sections have default content

Let's also ignore this one. Seems like it might be a bug with our markdownlint setup.

So just fix the links and we'll be good to merge. If you have questions about any specific link, I'll gladly answer.

>

2024-02-25 00:29 UTC, Churtified commented
@JoshDevHub Thank you, have updated links. Only markdownlint left is the default content bug.

2024-02-25 03:08 UTC, JoshDevHub approved these changes

2024-02-25 03:09 UTC, merged