Intermediate HTML & CSS Fonts: Remove mention of Google Fonts and Add warning
TheOdinProject/curriculum pull request #27413
Opened 2024-02-21 02:52 UTC by nikitarevenco

## Because

Google fonts [violate the GDPR](https://www.cookieyes.com/documentation/features/integrations/google-fonts-and-gdpr/) and as such, should not be used.

## This PR

- Remove mention of google fonts and add warning against using them

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-02-22 21:02 UTC, thatblindgeye requested changes

2024-02-23 16:32 UTC, nikitarevenco commented on intermediate_html_css/intermediate_css_concepts/more_text_styles.md
> +</div>
I think its better to leave the article in, it serves as 'proof' to the reader that google fonts violates GDPR. I tried finding an article that doesn't mention how to use google fonts and still stay compliant, but I couldn't - so I've added a change to tell the reader not to follow the instructions on that article as you've mentioned.

2024-02-23 17:05 UTC, thatblindgeye approved these changes
Looks good! Had a nit below, more personal preference than anything, but let me know what you think makes the most sense to you and I'd be good either way to merge this in.

2024-02-23 17:05 UTC, thatblindgeye commented on intermediate_html_css/intermediate_css_concepts/more_text_styles.md
> +As you look into online font libraries to use you may come across [Google Fonts](https://fonts.google.com/). We strongly advise against using them, as websites that use Google Fonts [violate the GDPR
```suggestion
As you look into online font libraries to use you may come across [Google Fonts](https://fonts.google.com/). We strongly advise against using them, as websites that use Google Fonts [violate the GDPR](https://www.cookieyes.com/documentation/features/integrations/google-fonts-and-gdpr/). Do not follow the instructions in that article on how to make Google fonts compliant, as we will be going over downloading fonts in this lesson.
```

2024-02-23 18:18 UTC, nikitarevenco commented
> Looks good! Had a nit below, more personal preference than anything, but let me know what you think makes the most sense to you and I'd be good either way to merge this in.

Great, I think your suggestion improves the clarity & wording. I added it.

2024-02-23 18:43 UTC, merged