Foundations/ Revisiting RPS: Add lesson overview and knowledge check
TheOdinProject/curriculum pull request #27461
Opened 2024-02-26 23:49 UTC by maahsnd

## Because

The "Revisiting RPS" lesson lacks both a "lesson overview" and a "knowledge check." Add both to align with standard lesson format. This will ensure consistency across the curriculum. Standardized structure improves clarity and user experience.

## This PR

- Add a lesson overview section. The lesson covers how to use git branches (create, merge, delete, best practices, use cases).
- Add a knowledge check section. Reference the general concept of branches, branch creation, branch merging, and one use case.

## Issue

Closes #27332

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-03-02 15:12 UTC, KevinMulhern requested changes

2024-03-02 15:12 UTC, KevinMulhern commented on foundations/javascript_basics/revisiting_rock_paper_scissors.md
> +## <pre class="mermaid">
Nit: This is used to display a diagram, and needs to be in a very specific format to display correctly.
Can everything between this line and line 46 be reverted back to what it was before please?

2024-03-02 22:47 UTC, maahsnd commented
Should I make those changes/ revert the requested section? I did not intend to alter anything there, must have been in the linting process and I missed it. Sorry for the confusion and any hassle.

2024-03-04 08:01 UTC, KevinMulhern commented
> Should I make those changes/ revert the requested section?

Yes please @maahsnd, we'll need those changes reverted to merge this PR.

2024-03-06 07:04 UTC, maahsnd commented
Hey @KevinMulhern I attempted to make the change. In my local environment, the diagram code matches its earlier state. I've committed and pushed that to the branch. I'm not confident I did that correctly. I'm inexperienced with updating PRs and am concerned I made a mistake.

2024-03-06 11:31 UTC, KevinMulhern commented
It looks like an empty merge commit was added, are you sure the revert changes were committed?

You can view the changes for this PR in the "Files changed" tab near the top of this page to verify whats in this PR.

2024-03-06 16:24 UTC, maahsnd commented
Revert changes were not committed. I've made a mess of my branch/ local git, and am not sure how to clean that up. My thought is to start from scratch, opening a new PR.

2024-04-11 15:49 UTC, MaoShizhong commented
@maahsnd If you've ended up in a bit of a tangle and you feel the easiest way for you to resolve this would be a fresh PR, feel free to close this one then open a new PR once you've done what you need to do.

2024-04-15 15:45 UTC, maahsnd commented
@MaoShizhong Got it, I'll do that. Thank you.

2024-04-17 22:07 UTC, maahsnd commented
@MaoShizhong @KevinMulhern I opened a new PR, #27810

2024-04-18 00:19 UTC, closed without merging