Fix wording
TheOdinProject/curriculum pull request #27494
Opened 2024-02-28 17:45 UTC by elayachihamrit1

## Because

Improving the wording in a sentence to provide a more positive and encouraging tone.

## This PR

Adjusting the sentence "Remember how much fun you had solving the card layout in this exercise? We know that was a frustrating one, but it’s part of the point." to "Remember the card layout exercise? It challenged your understanding of Flexbox, but that's how you learn and grow as a developer."

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-02-28 18:24 UTC, KevinMulhern requested changes
Thanks @elayachihamrit1, I like the sentiment of this change. Just a minor suggestion

2024-02-28 18:25 UTC, KevinMulhern commented on intermediate_html_css/grid/introduction_to_grid.md
> +It challenged your understanding of Flexbox, but that's how you learn and grow as a developer."
Nit: This reads a little better to me: 

```suggestion
That was a challenging one! but that's how you learn and grow as a developer."
```

2024-02-28 20:15 UTC, elayachihamrit1 commented
Thanks ❤️

2024-02-29 00:09 UTC, elayachihamrit1 commented on intermediate_html_css/grid/introduction_to_grid.md
> +It challenged your understanding of Flexbox, but that's how you learn and grow as a developer."
solved

2024-02-29 00:10 UTC, elayachihamrit1 reviewed
solved

2024-03-01 00:45 UTC, closed without merging