Motivation and Mindset: Add image for /stuck diagram
TheOdinProject/curriculum pull request #27556
Opened 2024-03-05 21:01 UTC by nikitarevenco

## Because

useful diagram for when stuck

## This PR

Adds the image for /stuck diagram

## Issue

Closes #27523

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-03-06 17:33 UTC, JoshDevHub reviewed
Looks good @nikitarevenco 

Would you be okay fixing the lint errors in this lesson while you're here? You can ignore the heading structure one because that'll be a bigger change, but the ones around blank lines and list styles could be easy to clean up if you want.

2024-03-07 20:22 UTC, nikitarevenco commented
> Looks good @nikitarevenco
> 
> Would you be okay fixing the lint errors in this lesson while you're here? You can ignore the heading structure one because that'll be a bigger change, but the ones around blank lines and list styles could be easy to clean up if you want.

Alright, I've fixed the issues mostly but I have a few questions

This lint issue says I should remove the whitespace to the left of the unordered list dashes `-`, however if I do that, then the list structure will change, I am pretty sure the lists need to be nested? I checked with the markdown preview tool and that does appear to be the case.
<img src="https://github.com/TheOdinProject/curriculum/assets/154856872/141092fd-8302-4644-8e2e-b7cfd65b0a77" width="30%" height="auto">

Also, since the additional resources shouldn't have nested lists, I've removed the 3 extra typing tool options and left a single one only. I personally don't think it makes a difference if we recommend 1 tool vs 4 tools, since all of them are pretty much the same. What do you think about this? Thinking about other ways this problem could be solved without removing the mention of those 3 extra typing speed tools

2024-03-08 01:29 UTC, nikitarevenco commented on foundations/introduction/motivation_and_mindset.md
> +- If you find your typing speed is holding you back, you can improve your typing skills by utilizing the [Monkeytype](https://monkeytype.com/) keyword trainer for at least 5 minutes every day.
> ```suggestion
> - If you find your typing speed is holding you back, you can improve your typing skills by utilizing keyword trainers for at least 5 minutes every day. Some excellent options include [Monkeytype](https://monkeytype.com/), [typing.com](https://www.typing.com/), [TypingClub.com](https://www.typingclub.com) and [Monkeytype](https://monkeytype.com/).
> ```
> 
> What about adding all of them inline?

This is a possibility, but one might have to ask why even mention 4 sites for typing speed? The main goal is to represent the idea. Use a typing speed site to improve your typing speed. Here is an example. The learner can research another one if they don't like the current one, but really they're all the same

2024-03-08 16:05 UTC, cakegod commented on foundations/introduction/motivation_and_mindset.md
> +- If you find your typing speed is holding you back, you can improve your typing skills by utilizing the [Monkeytype](https://monkeytype.com/) keyword trainer for at least 5 minutes every day.
It provides additional base options. Although I am indifferent towards either solution.

2024-03-11 17:34 UTC, JoshDevHub commented on foundations/introduction/motivation_and_mindset.md
> +- If you find your typing speed is holding you back, you can improve your typing skills by utilizing the [Monkeytype](https://monkeytype.com/) keyword trainer for at least 5 minutes every day.
I like adding the different options inline, so +1 for cake's idea here.

I like MonkeyType, but some of the other given options are a bit more formal, which might suit certain users' needs better. Like if you don't know touch typing at all, you may want something that's more of a "course" that walks through hand positioning and what fingers to use with each key, etc., and those other sites have that kind of thing going on.

2024-03-11 17:44 UTC, JoshDevHub commented
> This lint issue says I should remove the whitespace to the left of the unordered list dashes -, however if I do that, then the list structure will change, I am pretty sure the lists need to be nested? I checked with the markdown preview tool and that does appear to be the case.

Try formatting these the same way they're done in the [LAYOUT_STYLE_GUIDE](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#nested-lists)
```md
<!-- bad -->
1. List item

  - unordered item 1
  - unordered item 2
  
<!-- good -->
1. List item
   - unordered item 1
   - unordered item 2
```
Notice the absence of a blank line between the OL item and the UL items, as well as the three space indentation for the nested unordered items.

2024-03-11 17:48 UTC, nikitarevenco commented on foundations/introduction/motivation_and_mindset.md
> +- If you find your typing speed is holding you back, you can improve your typing skills by utilizing the [Monkeytype](https://monkeytype.com/) keyword trainer for at least 5 minutes every day.
> I like adding the different options inline, so +1 for cake's idea here.
> 
> I like MonkeyType, but some of the other given options are a bit more formal, which might suit certain users' needs better. Like if you don't know touch typing at all, you may want something that's more of a "course" that walks through hand positioning and what fingers to use with each key, etc., and those other sites have that kind of thing going on.

Oh yeah, in that case I definitely agree!

2024-03-12 21:25 UTC, JoshDevHub requested changes
Just one little change with the bullets and this should be good to merge.

2024-03-12 21:25 UTC, JoshDevHub commented on foundations/introduction/motivation_and_mindset.md
>    - [Believe you can get better](https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve)
The linter error here is confusing, but it should be fixed if you indent these bullets one more step to the right.

2024-03-13 02:48 UTC, JoshDevHub approved these changes
Looks great :rocket:

2024-03-13 02:48 UTC, merged