Update/css positioning lesson
TheOdinProject/curriculum pull request #27868
Opened 2024-04-26 19:58 UTC by Finn245

Updated CSS positioning lesson with additional insights and resources from the 'Slay the Dragon' video tutorial.

Changes:
- Incorporated video tutorial on CSS positioning from 'Slay the Dragon'
- Enhanced lesson content with visual demonstrations for improved clarity

This update enriches the learning experience by providing supplemental material that reinforces key concepts covered in the CSS positioning lesson.

2024-05-30 13:05 UTC, MaoShizhong requested changes
Thanks @Finn245 

Could you resolve the merge conflict please? While doing this, could you also extend the link text for your added video to include"CSS positioning from"? So the link text should read "CSS positioning from Slaying the Dragon". That would make it sufficiently descriptive and accessible.

2024-05-30 13:05 UTC, MaoShizhong commented on README.md
Could you also undo the changes to the README to remove it from this PR? It's unrelated and would be best done in a separate PR. Many thanks

2024-05-31 12:58 UTC, Finn245 commented on README.md
Hello, it is done.

2024-05-31 13:02 UTC, MaoShizhong commented
Looks like there's still the merge conflict to resolve.
I see you tried to resolve it by fetching and merging `origin/main`, your remote fork, except your remote fork is out of sync with upstream main (TOP's repo).

You can either sync your remote fork with upstream on GH, then redo the fetch and merge resolution to origin main, or you can skip the first step by just fetching from `upstream main` and merging `upstream/main` instead (i.e. syncing your local fork directly with TOP's repo).

2024-05-31 13:48 UTC, MaoShizhong requested changes
Almost there! Just need the below quick change as well as removing the trailing space on line 72, and the extra blank lines at the end of the file.
Our lesson files need to end with only a single blank line, but it looks like there are 3 blank lines instead.

2024-05-31 13:48 UTC, MaoShizhong commented on intermediate_html_css/intermediate_css_concepts/positioning.md
> +- You can check out this helpful video resource on CSS positioning from [CSS positioning from Slaying the Dragon](https://www.youtube.com/watch?v=MxEtxo_AaZ4&t=2s) for clear explanations and practica
Just meant to move the opening `[` forward to extend the link text, no need to double up on the words here
```suggestion
- You can check out this helpful video resource on [CSS positioning from Slaying the Dragon](https://www.youtube.com/watch?v=MxEtxo_AaZ4&t=2s) for clear explanations and practical examples.
```

2024-05-31 14:04 UTC, Finn245 commented
Oh okay so i have to remove line 72 and remove the last line which is the 75 so we keep only 1 blank line(74 one)?

2024-05-31 14:06 UTC, MaoShizhong commented
> Oh okay so i have to remove line 72 and remove the last line which is the 75 so we keep only 1 blank line(74 one)?

Yep. Either remove the space on line 72 (it's not blank, it's a line with just a space in it), or remove that line altogether (we don't need it anyway). Then files must end with only a single blank line, so delete any extra blank lines at the end of the file.

2024-05-31 14:41 UTC, MaoShizhong approved these changes
Many thanks for the new resource, it's a nice video on the topic for sure :+1:

2024-05-31 14:41 UTC, merged

2024-05-31 15:11 UTC, Finn245 commented
Thank you for your kind words! I'm thrilled that you found the new resource helpful. I'm looking forward to contributing more and continuing to enhance this project . Your encouragement means a lot, and I'm excited to collaborate further 😊👍.