Git Basics: Added a beginner-friendly git handbook to additional resources
TheOdinProject/curriculum pull request #27886
Opened 2024-04-29 13:11 UTC by theSamyak

Added beginner-friendly Git fundamentals handbook to additional resources.

## Because
This PR introduces a beginner-friendly Git fundamentals handbook into The Odin Project's additional resources. The handbook is easy for beginners to understand, with clear explanations and step-by-step instructions on Git basics. Its inclusion aims to significantly benefit students by providing them with a comprehensive and accessible resource to learn Git fundamentals effectively. Furthermore, the handbook has gained recognition within the community, having been featured in multiple newsletters and promoted by an official Microsoft page on Twitter, further validating its quality and usefulness.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-04-30 02:34 UTC, wise-king-sullyman requested changes
Thank you for taking the time to make this PR, but we are very intentional about when and where we introduce different Git concepts so this wouldn't really fit with our approach to the subject.

Honestly, we should probably look at removing all additional resources there for that same reason. I would wager most of them predate our shift in how we cover Git.

Is that something you would be interested in doing?

2024-04-30 07:14 UTC, theSamyak commented
> Thank you for taking the time to make this PR, but we are very intentional about when and where we introduce different Git concepts so this wouldn't really fit with our approach to the subject.
> 
> Honestly, we should probably look at removing all additional resources there for that same reason. I would wager most of them predate our shift in how we cover Git.
> 
> Is that something you would be interested in doing?



Thank you very much for taking the time to review my pull request and for providing feedback. I truly appreciate the effort you and the team put into maintaining the Odin Project.

I completely understand and respect your decision regarding the inclusion of additional resources in the Git section. Consistency in teaching approach is indeed crucial, and I appreciate your commitment to maintaining it.

If there are any further adjustments you'd like to make, such as removing additional resources or any other contributions you'd like assistance with, please don't hesitate to let me know. I'm more than willing to collaborate further in any capacity that aligns with the project's goals and in whatever capacity I can.

2024-05-01 19:27 UTC, wise-king-sullyman requested changes
Thank you for making these changes! This isn't _quite_ the approach we would want to take though.

2024-05-01 19:27 UTC, wise-king-sullyman commented on markdownlint/docs/TOP004.md
> -### Additional Resources
We want to keep the additional resources section as required.

2024-05-01 19:27 UTC, wise-king-sullyman commented on git/foundations_git/git_basics.md
> -This section contains helpful links to related content. It isn't required, so consider it supplemental.
We'll want to keep this section with the bullet below added as we outline in our [lesson layout guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#lesson-layout)

```
- It looks like this lesson doesn't have any additional resources yet. Help us expand this section by contributing to our curriculum.
```

2024-05-02 08:59 UTC, theSamyak commented
The changes have been made as suggested. Is there anything else I can assist with or any further adjustments required? Please let me know. Thank you.

2024-05-30 11:31 UTC, xandora approved these changes
Just a small issue with a close quote instead of an apostrophe. If there's nothing else to change, I think we can probably merge this one.

2024-06-08 13:51 UTC, wise-king-sullyman approved these changes
Looks perfect :fire: 

Thanks!

2024-06-08 13:52 UTC, merged