Async Await: Add blog post to Additional Resources
TheOdinProject/curriculum pull request #28111
Opened 2024-06-03 17:31 UTC by Asartea

## Because
- Josh W Comeau published a [new blogpost](https://www.joshwcomeau.com/javascript/promises/#why-would-they-design-it-this-way-1) about Promises today, and I think it would make a good additional resource to this lesson.

## This PR
- Adds it to the Additional Resources section

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-06-03 19:28 UTC, MaoShizhong requested changes
I like this article a lot. Josh Comeau always writes some good stuff :ok_hand: 
One nit below

2024-06-03 19:28 UTC, MaoShizhong commented on javascript/asynchronous_javascript_and_apis/async_and_await.md
> +- This [blog post about Promises From The Ground Up](https://www.joshwcomeau.com/javascript/promises/#why-would-they-design-it-this-way-1) delves into how Promises work
```suggestion
- For a more interactive explanation and example, try a [Scrim on async and await](https://scrimba.com/scrim/crd4eMc6?embed=odin,mini-header,no-next-up).
- This [blog post about Promises From The Ground Up](https://www.joshwcomeau.com/javascript/promises/#why-would-they-design-it-this-way-1) delves into how Promises work.
```

2024-06-04 07:50 UTC, Asartea commented
Fixed

2024-06-04 11:19 UTC, MaoShizhong approved these changes
:rocket:

2024-06-04 11:19 UTC, merged