Maintain react syntax
TheOdinProject/curriculum pull request #28123
Opened 2024-06-05 23:20 UTC by asdacosta

## Because

Use right language, React, for fenced code blocks

## This PR

Changes from Javascript to React syntax

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-06-05 23:56 UTC, MaoShizhong requested changes
Two of the code blocks do not need changing to `jsx` - reasoning outlined in #28122

The other two code blocks do, since they actually contain JSX that needs to be properly highlighted when rendered.

2024-06-05 23:56 UTC, MaoShizhong commented on react/the_react_ecosystem/type_checking_with_proptypes.md
> +```jsx
This block doesn't need to be changed as it does not contain any JSX syntax that needs different highlighting.

2024-06-05 23:56 UTC, MaoShizhong commented on react/the_react_ecosystem/type_checking_with_proptypes.md
> +```jsx
This one doesn't need changing either

2024-06-06 00:06 UTC, asdacosta commented
> Two of the code blocks do not need changing to `jsx` - reasoning outlined in #28122
> 
> The other two code blocks do, since they actually contain JSX that needs to be properly highlighted when rendered.

Ok @MaoShizhong . Since jsx and javascript render the code the same way when no jsx is returned, should I maintain the first two I changed to jsx or I need to change it?

2024-06-06 00:09 UTC, MaoShizhong commented
> > Two of the code blocks do not need changing to `jsx` - reasoning outlined in #28122
> > The other two code blocks do, since they actually contain JSX that needs to be properly highlighted when rendered.
> 
> Ok @MaoShizhong . Since jsx and javascript render the code the same way when no jsx is returned, should I maintain the first two I changed to jsx or I need to reverse the change?

If you could revert those two I pointed out, that would be great. We only need to set a code block's language to `jsx` if it actually contains JSX that needs JSX-specific syntax highlighting (because `javascript` won't properly do it), not just because it's a code block containing JS used in a React context (JSX isn't exclusive to React - it's just an extension of the language).

2024-06-06 00:15 UTC, MaoShizhong approved these changes
Many thanks, also for fixing up the knowledge check link syntax :rocket:

2024-06-06 00:16 UTC, merged