Set default content
TheOdinProject/curriculum pull request #28211
Opened 2024-06-12 22:42 UTC by asdacosta

## Because

Set default content

## This PR

* Set default content

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-06-15 02:38 UTC, JoshDevHub requested changes
Nice work.

Before merging, I think we should go ahead and completely resolve the lint errors in this lesson. It's still complaining about nesting the list in the Additional Resources section. I think we can make a few quick alterations to this section to clean that up ->
```md
### Additional resources

This section contains helpful links to related content. It isn't required, so consider it supplemental.

- Read the full [Variables chapter from *The Bastards Book of Ruby*](http://ruby.bastardsbook.com/chapters/variables) if you can't get enough about variables.
- [Variables as Pointers](https://launchschool.com/books/ruby/read/more_stuff#variables_as_pointers), from LaunchSchool's *Introduction to Programming With Ruby*.
- If you want to know more about Ruby's naming conventions, check out the [Ruby Style Guide](https://github.com/rubocop-hq/ruby-style-guide). Don't get too deep into it; just know that it's there.
```
Feel free to paste this over the current "Additional resources" section. This does a few things:
- removes the nesting
- removes one of the links, which was redundant with the first link
- gives one of the links more accessible wording

Let me know if you have any questions.

2024-06-17 07:24 UTC, asdacosta commented
> Nice work.
> 
> Before merging, I think we should go ahead and completely resolve the lint errors in this lesson. It's still complaining about nesting the list in the Additional Resources section. I think we can make a few quick alterations to this section to clean that up ->
> 
> ```
> ### Additional resources
> 
> This section contains helpful links to related content. It isn't required, so consider it supplemental.
> 
> - Read the full [Variables chapter from *The Bastards Book of Ruby*](http://ruby.bastardsbook.com/chapters/variables) if you can't get enough about variables.
> - [Variables as Pointers](https://launchschool.com/books/ruby/read/more_stuff#variables_as_pointers), from LaunchSchool's *Introduction to Programming With Ruby*.
> - If you want to know more about Ruby's naming conventions, check out the [Ruby Style Guide](https://github.com/rubocop-hq/ruby-style-guide). Don't get too deep into it; just know that it's there.
> ```
> 
> Feel free to paste this over the current "Additional resources" section. This does a few things:
> 
> * removes the nesting
> * removes one of the links, which was redundant with the first link
> * gives one of the links more accessible wording
> 
> Let me know if you have any questions.

The section has 5 links. It’s supposed to be 4 if you removed one of the links, but it’s 3. Please review and this time you could edit it yourself I reckon.

2024-06-17 16:57 UTC, JoshDevHub commented
> The section has 5 links. It’s supposed to be 4 if you removed one of the links, but it’s 3. Please review and this time you could edit it yourself I reckon.
I actually can't edit it easily in this PR because those lines are not currently part of the diff. You haven't changed anything with them, so GitHub won't allow me to make suggestions for those lines.

Anyways I meant to say I removed one of the Additional Resources list items outright. It happens to be one that had 2 links in it, so that's why it's down to 3 links.

2024-06-21 06:16 UTC, JoshDevHub approved these changes

2024-06-21 06:16 UTC, merged