Update setting_up_git.md
TheOdinProject/curriculum pull request #28251
Opened 2024-06-20 21:34 UTC by theSamyak

issue #28215
In the "Setting Up Git" lesson (setting_up_git.md), added a note section to clearly differentiate macOS-specific commands from general setup instructions.

## Because

Added a note section in the "Setting Up Git" lesson to clearly differentiate macOS-specific commands from general setup instructions.

## This PR

Added a note section in setting_up_git.md to highlight macOS-specific commands and also changed the title "macOS Users" to "For macOS Users" improving clarity for users.

## Issue

Closes #28215

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [X] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-06-20 22:03 UTC, xandora requested changes
We have specific styling code for these types of note blocks. Just using `>` is not the right way to do it in this situation.

Please review the style guide and update this PR accordingly before we can consider merging it. 

https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#note-boxes

2024-06-22 11:16 UTC, xandora requested changes
@theSamyak Thanks for working on the previous suggestions, just a couple of minor touches needed to get this ready to go.

2024-06-22 11:16 UTC, xandora commented on foundations/installations/setting_up_git.md
> +
Needs to be a blank line, currently there is one space.
```suggestion
 
```

2024-06-22 11:16 UTC, xandora commented on foundations/installations/setting_up_git.md
> +</div>
There needs to be a blank line between the end of the code fence and the next element.
```suggestion

</div>
```

2024-06-22 12:10 UTC, theSamyak commented
> @theSamyak Thanks for working on the previous suggestions, just a couple of minor touches needed to get this ready to go.

Hi, I messed up my commit history and there is still some linting issue and I apologize for it.  I have cloned the project into VS Code and from now on, will make the changes and contributions from there to maintain a cleaner commit history and preserve my sanity. Thanks.

2024-06-22 19:17 UTC, xandora approved these changes
Looks good to me!

2024-06-22 19:17 UTC, merged