Added hash map tests for Ruby
TheOdinProject/curriculum pull request #28263
Opened 2024-06-22 23:05 UTC by elishamutang

## Because

Allows users to populate their hash maps where it will exceed their load factor and ensuring that their hash map methods will still work as expected after growing their buckets ([similar to this PR for JavaScript course](https://github.com/TheOdinProject/curriculum/pull/28245)).

## This PR

Added a new section to test out user hash map implementation after `Assignment` section.
Added dummy nodes to populate user hash map in the new section.

## Issue

Closes [#28257](https://github.com/TheOdinProject/curriculum/issues/28257)

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-06-23 14:36 UTC, SumonGFC commented
Hello :p Small gripe: In ruby style conventions, the names of "predicate methods" (methods that return a boolean) should end with a question mark to indicate that they return booleans. So on lines 52 and 109 in your proposed changes, `#has(key)` should be named `#has?(key)`. just wanted to let you know.

2024-06-23 14:44 UTC, elishamutang commented
@SumonGFC Ah i see, didn't know that. Thanks for letting me know, I'll undo that change! What about the the set method in lines 44 & 48?

2024-06-23 15:01 UTC, SumonGFC commented
@elishamutang those lines are perfect. This set method is not supposed to return a boolean in the interface described by this project (think it is supposed to return the value that is associated with the key)

2024-06-24 16:27 UTC, JoshDevHub requested changes
Awesome work :raised_hands:

Like @SumonGFC said, the only suggestion I have is to append a `?` to the `#has` method name (I forgot to mention this as something to keep in mind).

After that's fixed, we should be good to merge.

2024-06-24 16:27 UTC, JoshDevHub commented on ruby/computer_science/project_hash_map.md
> +1. Test the other methods of your hash maps such as `#get(key)`, `#has(key)`, `#remove(key)`, `#length`, `#clear`, `#keys`, `#values`, and `#entries` to check if they are still working as expected af
```suggestion
1. Test the other methods of your hash maps such as `#get(key)`, `#has?(key)`, `#remove(key)`, `#length`, `#clear`, `#keys`, `#values`, and `#entries` to check if they are still working as expected after expanding your hash map.
```

2024-06-25 01:09 UTC, elishamutang commented
@JoshDevHub totally missed that last `#has` method haha. No worries and thanks for the help! You too @SumonGFC :)

2024-06-25 16:09 UTC, JoshDevHub approved these changes
Thanks for doing this!

2024-06-25 16:09 UTC, merged