Provide descriptive link text to methods lesson of 'basic ruby' section
TheOdinProject/curriculum pull request #28310
Opened 2024-06-29 15:37 UTC by CJKbarts

## Because some links in the lesson were either to verbose or too concise. These changes make the lesson easier to follow

## This PR

## Issue

Related to #28290

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-06-29 22:48 UTC, MaoShizhong requested changes
Thanks for doing these and also fixing up the lint errors. Just a couple of small changes below then we should be good to merge!

2024-06-29 22:48 UTC, MaoShizhong commented on ruby/basic_ruby/methods.md
> +One of Ruby's great advantages for new programmers is its large number of built-in methods. You've been using many of them already, probably without even realizing it. Over the course of your learnin
Missed this one
```suggestion
One of Ruby's great advantages for new programmers is its large number of built-in methods. You've been using many of them already, probably without even realizing it. Over the course of your learning so far, you have modified strings and other objects in various ways. For example, the [#times loop](https://docs.ruby-lang.org/en/3.3/Integer.html#method-i-times) and [#upto loop](https://docs.ruby-lang.org/en/3.3/Integer.html#method-i-upto) that you learned about in the Loops lesson are both methods that are included as part of Ruby's [Integer class](https://docs.ruby-lang.org/en/3.3/Integer.html).
```

2024-06-29 22:48 UTC, MaoShizhong commented on ruby/basic_ruby/methods.md
> +- <span id="reserved-words">You cannot name your method one of [Ruby’s approximately 40 reserved words](https://stackoverflow.com/questions/10542354/what-are-the-restrictions-for-method-names-in-ruby
The href for this link was changed in a previous PR that I missed, so the spreadsheet wasn't updated - oops! However, checking the new link, it seems broken and doesn't lead to the right list. Therefore, the below now contains the doc page with the keywords which I think makes more sense than an SO post or other page anyway.
```suggestion
- <span id="reserved-words">You cannot name your method one of [Ruby’s approximately 40 reserved words](https://docs.ruby-lang.org/en/3.3/keywords_rdoc.html), such as `end`, `while`, or `for`.</span>
```

2024-06-29 22:48 UTC, MaoShizhong commented on ruby/basic_ruby/methods.md
> +1. Complete the Complete the method exercises from the [ruby-exercises repo](https://github.com/TheOdinProject/ruby-exercises) that you previously cloned.
```suggestion
1. Complete the method exercises from the [ruby-exercises repo](https://github.com/TheOdinProject/ruby-exercises) that you previously cloned.
```

2024-06-30 00:49 UTC, CJKbarts commented
I think I got everything. I had some problems trying to squash the new commit into the old one but I think I got it.
Thank you for your feedback

2024-06-30 10:13 UTC, MaoShizhong approved these changes
:rocket: Congrats on your first PR here

2024-06-30 10:13 UTC, merged

2024-06-30 10:52 UTC, CJKbarts commented
Thank you

2024-06-30 10:53 UTC, CJKbarts commented
Do I delete the branch then?

2024-06-30 11:41 UTC, MaoShizhong commented
> Do I delete the branch then?

You can safely delete the branch now that it's been merged.