Advanced HTML and CSS Course: Adds A11y Project as Additional Resource
TheOdinProject/curriculum pull request #28340
Opened 2024-07-04 19:37 UTC by kellyky

## Because

Resolve issue - to add an additional resource to this lesson. 

## This PR

Adds to Additional Resources:

[The A11Y Project:](https://www.a11yproject.com/) An open-source resource that provides information on how to make your web content more accessible. The A11Y Project includes checklists, guidelines, and tools that can help you implement WCAG standards effectively.

## Issue

Closes #27971 

## Additional Information

n/a

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-07-04 21:00 UTC, MaoShizhong requested changes
Thanks @kellyky 
On top of the nit below, there are also a few simple lint errors - would you be happy to fix these as well? They should fixable with a single pass of our `fix:lesson` script as per our [local linting and fixing instructions](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md).

2024-07-12 03:46 UTC, kellyky commented on advanced_html_css/accessibility/the_web_content_accessibility_guidelines_wcag.md
> +- [The A11Y Project]((https://www.a11yproject.com/)): An open-source resource that provides information on how to make your web content more accessible. The A11Y Project includes checklists, guidelin
Good catch, thanks!

2024-07-12 10:38 UTC, MaoShizhong approved these changes
Are you happy to fix the few remaining lint errors? The error messages should be self explanatory, but we also have lint and fix instructions that I've linked in the message above.

If so, I'll wait for the lint errors to be fixed before merging.

2024-07-15 19:19 UTC, kellyky commented
> Are you happy to fix the few remaining lint errors? The error messages should be self explanatory, but we also have lint and fix instructions that I've linked in the message above.
> 
> If so, I'll wait for the lint errors to be fixed before merging.

Sure - I should be able to later today or tomorrow morning!

2024-07-15 21:30 UTC, kellyky commented
All set! (And all in all a good reminder for me to mind the linting check).

2024-07-15 21:45 UTC, MaoShizhong approved these changes
:rocket:

For future PRs, you if you're not sure then you don't need to handle lint errors if you haven't been asked to. You can always comment asking if a maintainer would like you to fix them, especially since some lint errors can only be fixed manually and are based on context.

2024-07-15 21:46 UTC, merged