JS Recursive Methods: Change incorrect to incomplete
TheOdinProject/curriculum pull request #28345
Opened 2024-07-05 21:00 UTC by stephspace

## Because
This PR changes the current wording from "incorrect" to "incomplete" because it can be confusing to people when they run the code and it gives them the same outcome as the one in the corrected solution using the exercise's test case.

## This PR

- Clarify the reason why the solution from the code quiz “Question 6: Search JS object” is less incorrect and more incomplete.

## Issue

Closes #28341

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-07-05 21:54 UTC, MaoShizhong requested changes

2024-07-05 21:54 UTC, MaoShizhong commented on javascript/computer_science/recursive_methods.md
> +The solution for "Question 6: Search JS object" is incomplete. See the [corrected solution](https://gist.github.com/JoshDevHub/b00125f483d4a1ecc257eaa030916973) after you solve it.
No issue with your change, just thought while we're at it, the current link text "corrected solution" isn't descriptive enough on its own for what it actually refers to, so would ideally be made more accessible with something like the following:

```suggestion
The solution for "Question 6: Search JS object" is incomplete. See [a more accurate solution for `contains()`](https://gist.github.com/JoshDevHub/b00125f483d4a1ecc257eaa030916973) after you solve it.
```

2024-07-06 15:58 UTC, MaoShizhong requested changes
Sorry to be a pain as I missed this earlier.
Line 35 `### Test yourself` is flagging a lint error. In this scenario, that's simply fixable by changing it to `#### Test yourself` (4 `#` instead of 3) to put it on the appropriate heading level (not all cases like this should be fixed this way, but this one can).

We can merge after you change that, if you don't mind :rocket:

2024-07-06 16:35 UTC, MaoShizhong approved these changes
Thanks for contributing and congrats on your first PR here :rocket:

2024-07-06 16:35 UTC, stephspace commented
No problem at all! This is my first time contributing and I appreciate the learning opportunity to make these changes 👍

2024-07-06 16:35 UTC, merged