Ruby course: Add example results for two projects
TheOdinProject/curriculum pull request #28380
Opened 2024-07-10 18:35 UTC by Grayvox

## Because

Recursion and Linked Lists both lack any examples of inputs and expected outputs to test the student's solutions for the projects, so this PR aims to fix that. Originally, as discussed in the issue linked below, this was going to add it to Knight Travails as well. However, I felt with what method examples are already present in the project that it was probably unnecessary.

## This PR

- Adds a "Test it out" section to Recursion and Linked Lists
- Adds inputs and expected outputs into the new section

## Issue

Closes #28318

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-07-10 19:01 UTC, MaoShizhong requested changes
Many thanks! Some initial comments/changes needed.

Once these are done and a maintainer more familiar with Ruby is happy with this PR's additions and has approved and merged, I'll do a translation for the JS/Node side.

2024-07-10 19:18 UTC, Grayvox commented
@MaoShizhong Done! Thanks for that - only linting issues left are what should be resolved in the accessible link text issue

2024-07-15 19:51 UTC, JoshDevHub requested changes
Just have one small suggestion but otherwise this looks great.

Another small sidebar: I can see that you made this PR from the `main` branch of your fork. This is *very* dangerous. If someone else works on this file and has their PR merged to the curriculum while this is still in review, a "merge conflict" may happen, and you might not have an easy way to resolve it from this PR. So just a reminder that when you're working on something, be sure to create a *new* branch to do the PR with. You'll be guaranteed to avoid a situation where you throw away a bunch of work and have to redo the whole PR (I've seen this happen to people multiple time!). Just a warning for the future.

2024-07-15 19:51 UTC, JoshDevHub commented on ruby/computer_science/project_linked_lists.md
> +1. Create a `main.rb` file and make sure it inherits the file containing `LinkedList`. This is where we'll test the list.
```suggestion
1. Create a `main.rb` file and make sure it requires the file containing `LinkedList`. This is where we'll test the list.
```
Recommend changing this from "inherits" (which generally refers to subclassing) to "requires" (which is the Ruby terminology for loading different files)

2024-07-15 22:00 UTC, Grayvox commented
Thanks @JoshDevHub ! So sorry about that, and thank you for pointing it out to me - I'll be sure to do that in the future to prevent any issues that might come up. I committed the change you suggested and it should be all ready to go.

2024-07-15 23:11 UTC, JoshDevHub approved these changes
Looks great! Thank you for making this change @Grayvox :rocket:

And thank you for the previous review @MaoShizhong :raised_hands:

2024-07-15 23:11 UTC, merged

2024-07-15 23:36 UTC, MaoShizhong commented
I'll get a JS translation up in a bit