chore: update mini-message and inventory projects
TheOdinProject/curriculum pull request #28420
Opened 2024-07-16 12:13 UTC by 01zulfi

## Because

https://github.com/TheOdinProject/curriculum/issues/27927

## This PR

https://github.com/TheOdinProject/curriculum/issues/27927

## Issue

Closes #27927 

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-07-16 12:24 UTC, MaoShizhong reviewed
How will URLs be handled for links to other lessons in the course, specifically the ones that are brand new files in the `express/` directory (and not the ones that are updating existing lesson files), e.g. the new deployment lesson? Will they retain the same URL as the lessons they're replacing?

2024-07-16 12:46 UTC, MaoShizhong requested changes
:fire:

2024-07-16 12:46 UTC, MaoShizhong commented on nodeJS/express/project_inventory_application.md
> +1. Figure out the delete functionality. What happens if you delete a category with items in it? Should it delete all the items as well? Or should it just remove the category from the items? This spec
Possibly makes it more "you decide with what makes sense to you" than "these are your only two options - pick one" to me

```suggestion
1. Figure out the delete functionality. What happens if you try to delete a category with items in it? Should it delete all the items as well? Should it just remove the category from the items? Or something else? This specific behavior will depend on your app's requirements.
```

2024-07-16 12:46 UTC, MaoShizhong commented on nodeJS/express/project_inventory_application.md
> +1. Create all of the 'READ' views (i.e. view category, and view item)
```suggestion
1. Create all of the 'READ' views (i.e. view category, and view item).
```

2024-07-16 12:46 UTC, MaoShizhong commented on nodeJS/express/project_mini_message_board.md
> +1. Set up a basic Express app by installing Express and EJS. Set up a basic index route and run your server. Create required folders and files as discussed in the previeous lessons.
```suggestion
1. Set up a basic Express app by installing Express and EJS. Set up a basic index route and run your server. Create the required folders and files as discussed in the previous lessons.
```

2024-07-16 12:46 UTC, MaoShizhong commented on nodeJS/express/project_mini_message_board.md
> +1. We are going to have 2 routes, the index (`"/"`) and a new-message form (`"/new"`).
Nit
```suggestion
1. We are going to have 2 routes, the index (`"/"`) and a "new message" form (`"/new"`).
```

2024-07-16 12:46 UTC, MaoShizhong commented on nodeJS/express/project_mini_message_board.md
> +1. Next, in your index template (in the `"views"` folder) loop through the messages array using whichever templating language you selected and for each one, display the user, text and the date the me
```suggestion
1. Next, in your index template (in the `"views"` folder) loop through the messages array and for each one, display the user, text and the date the message was added. Don't forget to make your messages available to your template by including it in the `res.render` 'locals' object (e.g. `res.render("index", { title: "Mini Messageboard", messages: messages })`).
```

2024-07-16 12:46 UTC, MaoShizhong commented on nodeJS/express/project_mini_message_board.md
> +1. At the end of the `router.post()` function use `res.redirect('/')` to send users back to the index page after submitting a new message.
```suggestion
1. At the end of the `router.post()` function use `res.redirect("/")` to send users back to the index page after submitting a new message.
```

2024-07-16 12:46 UTC, MaoShizhong commented on nodeJS/express/project_mini_message_board.md
> +1. Add a "open" button against every message to open a new page with the message details.
```suggestion
1. Add an "open" button next to every message to open a new page with the message details.
```

2024-07-16 12:46 UTC, MaoShizhong commented on nodeJS/final_project/project_odin_book.md
While we're at it, there are two mentions of `passportJS` on line 7 here where the first mention should be changed to `passport.js, and the second mention either the same or changed to simply `Passport`.

2024-07-17 06:26 UTC, 01zulfi commented
> How will URLs be handled for links to other lessons in the course, specifically the ones that are brand new files in the express/ directory (and not the ones that are updating existing lesson files), e.g. the new deployment lesson which is linked in line 34 of the blog project? Will they retain the same URL as the lessons they're replacing?

I'm not sure if they'll retain the same URL. We can update those URLs when the revamp goes live though. In case, we do miss some, we can rely on the community to submit issues/PRs.

2024-07-17 09:42 UTC, MaoShizhong commented
> > How will URLs be handled for links to other lessons in the course, specifically the ones that are brand new files in the express/ directory (and not the ones that are updating existing lesson files), e.g. the new deployment lesson which is linked in line 34 of the blog project? Will they retain the same URL as the lessons they're replacing?
> 
> I'm not sure if they'll retain the same URL. We can update those URLs when the revamp goes live though. In case, we do miss some, we can rely on the community to submit issues/PRs.

In that case, I'll make a note of all relevant links in the new lessons and once they go live, do a check and PR href changes as necessary.

2024-07-17 10:03 UTC, MaoShizhong approved these changes
:rocket:

2024-07-17 12:46 UTC, MaoShizhong requested changes
Oops, nearly missed this one!

OdinBook line 46 currently still references the Inventory Application project for Cloudinary, but Cloudinary will be moved to the File Uploader project instead.

We should edit that line to:

```md
1. Make posts also allow images (either just via a URL or by uploading one). If you did the extra credit from [File Uploader project](https://www.theodinproject.com/lessons/nodejs-file-uploader), then you may recall [Cloudinary](https://cloudinary.com/documentation/node_integration) or [Supabase storage](https://supabase.com/docs/guides/storage) being good options for hosting user-uploaded images. The URLs they provide you can then be stored in your database instead of the raw image binary data.
```

2024-07-18 18:46 UTC, MaoShizhong approved these changes

2024-07-18 18:54 UTC, merged