Project_mini_message_board: brief description change
TheOdinProject/curriculum pull request #28653
Opened 2024-08-17 15:38 UTC by mikeyCos

Use a open button or link for message details page.

## Because

Provides creators the option to use a link, anchor tag for opening a message details page.

## This PR

- Included "or link" after "open button".

## Issue

Closes #28638

## Additional Information

The [Discord discussion starts here](https://discord.com/channels/505093832157691914/597796701650026517/1273435243592024124).

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-08-17 15:43 UTC, MaoShizhong requested changes

2024-08-17 15:43 UTC, MaoShizhong commented on nodeJS/express/project_mini_message_board.md
> +1. Add a "open" button or link next to every message to open a new page with the message details.
Does need to beed "an" 
```suggestion
1. Add an "open" button or link next to every message to open a new page with the message details.
```

2024-08-18 03:59 UTC, mikeyCos reviewed
Resolved requested change; 'a' to 'an'.

2024-08-18 09:07 UTC, KevinMulhern approved these changes
Thanks @mikeyCos

2024-08-18 09:46 UTC, MaoShizhong approved these changes

2024-08-18 09:47 UTC, merged