Update intro-to-css.md
TheOdinProject/curriculum pull request #28754
Opened 2024-09-07 09:56 UTC by abhilash15500

A warning would be as i see people in discord everyday asking doubts about animation exercise. They solve 1to5 exercises and then in flow they start animation even when its instructed. I think a warning should make them aware to not touch anything else except foundations 1 to 5 exercises.

## Because

## This PR

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-09-07 10:41 UTC, XAJX179 commented
hello xplozion! just a heads up remove the blank lines at line numbers - 364 , 373 to avoid markdown lint errors and following style guide.

Now on topic -
 i think we should add some writing about reading instructions more carefully in future too, if we add this warning.

2024-09-07 11:44 UTC, MaoShizhong commented
Thanks for the PR. Honestly, I'm not too sure this will change much. The assignment very clearly already states to go to the foundations folder and complete the listed exercises. People have generally only done differently when they get carried away and/or just straight up forget the instructions after reading the README but don't go back to check them (so they assume).

In those cases, given the explicit instructions they read to get to that repo had been forgotten, I'm not convinced a note box repeating those instructions beforehand will change this. I'll see what other maintainers have to say though, if any have differing opinions.

I will point out though that [your note box doesn't follow the correct syntax](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#note-boxes). The heading should be a level 4 heading placed inside the div, and should also ideally be more descriptive than a generic "warning".

2024-09-08 08:41 UTC, Eduardo06sp commented
@MaoShizhong Is it okay to openly discuss some potential solution to this problem here? 

I share the same concern as the author and have seen multiple users (in the Discord) accidentally go to the more advanced exercises.

2024-09-08 08:46 UTC, abhilash15500 commented
One solution i can think is directly redirecting them to foundations folder instead of css exercises? That would be better I guess

2024-09-08 10:28 UTC, MaoShizhong commented
@Eduardo06sp Please do fire away. If there is a solution, I'm not sure a note box would be it but perhaps there's another solution that's suitable.

And @abhilash15500 we need people to read the README first (and even when we say it clear and link to it, some people still don't read it and we can't really help prevent those cases).

Perhaps we could split the assignment into 2 steps. The first one instructs to read the repo README, linking as it currently does. The second step then links to the Foundations folder and instructs to do exercises 1-5 as it currently does. I'd love to hear what Eduardo wants to say as well

2024-09-08 10:37 UTC, abhilash15500 commented
Splitting assignment would work nicely. 
Also mb for not raising issue first i was unaware of the workflow for this. 
Just shared what i felt like is an issue.

I would be happy with whatever steps TOP management and core members take for this 😄

2024-09-08 10:57 UTC, MaoShizhong commented
Yes ideally an issue is created first so the proposal can be made (examples if appropriate) then it can be discussed, just in case things either don't get approved or perhaps a different solution is more appropriate through discussion, especially if you haven't had a lot of experience with contributing here. Of course if it's a super obvious fix like a typo or broken link, then by all means go straight to a PR if there isn't already an open issue/PR for it.

2024-09-08 11:22 UTC, abhilash15500 commented
I will remember it next time. 

Im happy to follow whatever steps needed if any from my side / or any decision which top members take which they think its for the betterment of TOP! :)

2024-09-09 04:55 UTC, Eduardo06sp commented
@MaoShizhong I think that small change would help a lot.

I also believe that structuring the `css-exercises` repo like the curriculum is structured would serve as another "fail-safe".

I.e.
Instead of the folders being laid out like they currently are
```bash
animation  flex  foundations  grid  margin-and-padding
```

we can structure them just like they appear in the curriculum
```bash
foundations  intermediate-html-and-css  advanced-html-and-css
```

and the nesting can go deeper if deemed necessary,
but the drawback is that any potential, future updates to the curriculum's structure will require an update in the `css-exercises` repo as well

just an idea :}

2024-09-09 11:35 UTC, MaoShizhong commented
Thanks @Eduardo06sp. Could you open an issue about that in the [css-exercises repo](https://github.com/TheOdinProject/css-exercises) please? I think that's something better proposed and discussed there (and I'd like input from other team members), and if it gets approved, there will also be a sibling PR here to amend any lessons to reference the right folders and files etc.

2024-09-09 11:37 UTC, MaoShizhong requested changes
Regarding this PR, @abhilash15500, could you remove the note box changes you originally made then do the following?

- Split the assignment step into 2 steps:
  1. Link to the CSS exercises repo and instruct to read the README
  2. Link to the foundations directory and carry on with the rest of the instructions.

2024-09-09 12:32 UTC, MaoShizhong commented on foundations/html_css/css-foundations/intro-to-css.md
> +1. Then, once you know how to use the exercises, navigate to the [foundations](https://github.com/TheOdinProject/css-exercises/tree/main/foundations) directory. Review each README file prior to compl
Also just for future reference, if someone has left a review, they'll appear in the top right corner. Once you've addressed any requested changes, you can hit the rerequest review button to indicate it's ready to be rereviewed.

![Screenshot_2024-09-09-13-31-35-19_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/e324d2e1-f47d-48e6-9861-67f1a9d0e4ad)

2024-09-09 12:48 UTC, MaoShizhong approved these changes
:pray:

2024-09-09 12:48 UTC, merged

2024-09-09 12:52 UTC, abhilash15500 commented
Appreciated! ☺️

2024-09-10 07:00 UTC, Eduardo06sp commented
Relevant Issue: https://github.com/TheOdinProject/css-exercises/issues/593