Ruby : Files and Serialization : Format unreadable article in assignment
TheOdinProject/curriculum pull request #28897
Opened 2024-10-03 06:40 UTC by XAJX179

## Because
The [article](http://www.skorks.com/2010/04/serializing-and-deserializing-objects-with-ruby/) linked in poorly formatted.

## This PR
- Adds a links to a [pastebin](https://pastebin.com/DZTegAqP) of well formatted version of article.
- Advises to use Odin Project's [Markdown Preview](https://www.theodinproject.com/lessons/preview) tool on it.

## Issue

Closes #XXXXX

## Additional Information
the article was very hard to read so i decided to format it correctly for myself and now am just sharing it with other students :)

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-12-13 19:06 UTC, XAJX179 commented
bump.

2025-01-09 07:15 UTC, XAJX179 commented
@KevinMulhern  sorry for the ping , just making sure did u get notified ?

2025-01-27 06:12 UTC, XAJX179 commented
@KevinMulhern

2025-02-17 22:31 UTC, JoshDevHub requested changes
Just one little wording change, but otherwise this seems fine to me.

2025-02-17 22:31 UTC, JoshDevHub commented on ruby/files_and_serialization/files_and_serialization.md
> +  1. Copy this [pastebin](https://pastebin.com/ZixCHcWk) and open [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview), paste it and click on preview and start reading. becaus
```suggestion
  1. Skim [Alan Skorkin's article about object orient serialization in Ruby](http://www.skorks.com/2010/04/serializing-and-deserializing-objects-with-ruby/). The article isn't well formatted and some code examples are outdated, but this post still contains relevant information. To view in a better format, you can copy the contents of this [pastebin](https://pastebin.com/ZixCHcWk) and paste them into the [Odin Markdown Preview Tool](https://www.theodinproject.com/lessons/preview).
```
Suggested wording change. Let me know if it seems good to you.

2025-02-20 19:52 UTC, JoshDevHub approved these changes

2025-02-20 19:52 UTC, merged