Add Neon and Koyeb to list of PaaS options in Rails deployment lesson
TheOdinProject/curriculum pull request #29148
Opened 2024-12-04 01:44 UTC by DrantDumani

## Because

The Rails lesson on Deployment didn't list Koyeb and Neon as PaaS options, which are listed on the NodeJS version of the lesson

## This PR

- Lists Koyeb and Neon's info as PaaS options for users.

## Issue

Closes #28862

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-12-04 22:49 UTC, JoshDevHub requested changes
Thank you for adding these!

Just have a couple of requested changes. Since this is in the context of the Rails course, it doesn't make sense to point learners to the documentation around working with node/express.

2024-12-04 22:49 UTC, JoshDevHub commented on ruby_on_rails/rails_basics/deployment.md
> +- [Guide: Official getting started with Node/Express on Koyeb guide](https://www.koyeb.com/docs/deploy/express)
```suggestion
- [Guide: Official getting started with Ruby on Rails on Koyeb guide](https://www.koyeb.com/docs/deploy/ruby-on-rails)
```

2024-12-04 22:49 UTC, JoshDevHub commented on ruby_on_rails/rails_basics/deployment.md
> +- [Guide: Connect a Node.js application to Neon](https://neon.tech/docs/guides/node)
```suggestion
- [Guide: Connect a Ruby on Rails application to Neon](https://neon.tech/docs/guides/ruby-on-rails)
```

2024-12-07 10:45 UTC, MaoShizhong commented
Perhaps should also close #28491?

2024-12-07 20:07 UTC, DrantDumani commented
My bad on just copy pasting from the node section. The links have been updated to the ruby on rails docs!

2025-01-03 19:22 UTC, JoshDevHub approved these changes
:rocket:

2025-01-03 19:22 UTC, merged