Typo and details
TheOdinProject/curriculum pull request #29156
Opened 2024-12-06 19:29 UTC by OmegaGinga

## Because

Linked the questions of the Knowledge Check to the tag document, this will help to speed up where the students can find the information or the answer to the questions. Additionally, merged the latest updates from the upstream main branch to keep this branch up to date.

## This PR

In ruby/automated_testing/rspec_part_two_code_sharing.md I've made the link of the questions to the document.

## Issue

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-12-06 20:29 UTC, xandora requested changes

2024-12-06 20:29 UTC, xandora commented on .codespellignore
> +enumerables
The Because and Why? sections of the PR don't explain what this change is doing. Can you elaborate on this?

2024-12-06 20:29 UTC, xandora commented on ruby/automated_testing/rspec_part_two_code_sharing.md
> +~~~~ruby
Code fences need to be wrapped with 3 tildes, not 4. This seems like an incorrect change.

2024-12-06 20:29 UTC, xandora commented on ruby/automated_testing/test_driven_development.md
> +
This is fine.

2024-12-06 20:29 UTC, xandora commented on ruby/automated_testing/test_driven_development.md
> +
This is fine.

2024-12-06 20:29 UTC, xandora commented on ruby/automated_testing/test_driven_development.md
> +
This is fine.

2024-12-06 20:29 UTC, xandora commented on ruby/automated_testing/test_driven_development.md
> +- [How much code should be written when going from the `red` state to the `green` state of the red-green-refactor cycle?](#what-is-tdd-and-why-do-it)
Having link backs in the Knowledge Check section is good, but if they all point to the same section, then they might cause confusion when they all end up at the same place.

Additionally, you've missed a period at the end of the second check.

2025-02-17 21:42 UTC, JoshDevHub commented
Closing this due to inactivity.

2025-02-17 21:42 UTC, closed without merging