JavaScript Basics Course: Replace Replit exercises
TheOdinProject/curriculum pull request #29161
Opened 2024-12-07 18:18 UTC by Eduardo06sp

## Because

we are removing Replit, so we have to replace the Replit exercises with new content from our `javascript-exercises` repo.

## This PR

* Adds a very simple overview of `javascript-exercises` with a brief explanation of `return` in the Data Types and Conditionals lesson
* Adds the introductory exercise `01_helloWorld` to the Data Types and Conditionals lesson
* Replaces the Replit exercises in the Data Types and Conditional lesson
  - The new ones come from our `javascript-exercises` repo
  - `02_addNumbers` replaces Replit exercise 1 (troubleshooting)
  - `03_numberChecker` replaces Replit exercise 2 (enter a number)
  - `04_mathEquations` replaces Replit exercise 3 (lets do some math)
  - `05_joinStrings` replaces Replit exercise 4 (direction follow)
* Removes introductory exercise `01_helloWorld` from Arrays and Loops lesson
* Renumbers/rewords the exercises/assignment in the Arrays and Loops lesson
* **Adds reminder to ensure that user has already completed Node.js installation, exercise set up and `01_helloWorld`** in the Arrays and Loops lesson
  - This is to account for moving the Installing Node.js lesson further back, in case some users were still doing lessons before they could get to Installing Node.js
* Renumbers/rewords exercises/assignment in the Object Basics lesson

## Issue

Related to https://github.com/TheOdinProject/curriculum/issues/29054

## Additional Information

Since multiple repos are affected simultaneously, it may be ideal to merge all 3 PRs at once:

**Blockers:**
* Need to add the four new exercises to the `javascript-exercises` repo - https://github.com/TheOdinProject/javascript-exercises/pull/509
* Need to move Installing Node.js lesson so it is before the lesson where these are going to be introduced (Data Types and Conditionals) - https://github.com/TheOdinProject/theodinproject/pull/4870

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-12-07 18:19 UTC, Eduardo06sp commented
I will update some formatting for the Arrays and Loops lesson to match the style guide

2025-05-03 12:44 UTC, KevinMulhern requested changes
Sorry for the delay @Eduardo06sp, this is looking great 🔥  nice work!

Just one small suggestion with the instruction to install Node

2025-05-03 12:44 UTC, KevinMulhern commented on foundations/javascript_basics/arrays_and_loops.md
> +1. If you already completed our [Installing Node.js lesson](https://www.theodinproject.com/lessons/foundations-installing-node-js), you may move on to the next step!
Nit: With the node installation lesson coming before this now, learners should have already done this. I think we can safely drop this branch of instructions and simplify this list.

2025-05-04 15:15 UTC, KevinMulhern approved these changes
Great stuff, thanks for all your effort on this @Eduardo06sp

2025-05-04 15:18 UTC, merged

2025-05-09 06:33 UTC, Eduardo06sp commented
@KevinMulhern my pleasure, really excited to do a little part in improving the curriculum!!!! :}

I'll try to keep an eye out these upcoming weeks for any issues other may come across, though I did test everything multiple times.