Add creation of backlink to recipes tutorial
TheOdinProject/curriculum pull request #29238
Opened 2024-12-27 03:46 UTC by Keiferton

add instructions for back link from recipes to homepage (index.html)

## Because

## This PR

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project curriculum contributing guide](https://github.com/TheOdinProject/curriculum/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [ ] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

2024-12-28 03:03 UTC, zachmmeyer requested changes
Hello there! Thank you for contributing.
You checked off several items in the PR description. Here are three of them that I'd like to call out:
1. The title of this PR follows the location of change: brief description of change format, e.g. Intro to HTML and CSS lesson: Fix link text
2. If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
3. The Because section summarizes the reason for this PR

Please go over these bullet points and make sure you're adhering to the guidelines you agreed to. I'd look at some of the other active or merged PRs. 

Thanks!

2024-12-28 23:35 UTC, Keiferton commented
Thank you Zach! I've addressed the issues and will update shortly.

2024-12-29 14:53 UTC, zachmmeyer approved these changes
Ideally I'd say to match the style of the rest of the page and bullet points here, but I appreciate your emphasis and code block. Thanks for contributing!

2024-12-29 14:55 UTC, zachmmeyer requested changes
As soon as I approved it the linter found some issues, if you could update your work here and re-request, I'll can re-approve afterwards. Thanks!

2024-12-31 17:35 UTC, zachmmeyer commented
@Keiferton looks like the linter caught another issue.

2025-01-02 03:13 UTC, zachmmeyer approved these changes
Thanks for all of your hard work here!

2025-01-02 03:13 UTC, merged